### ISSUE TITLE
DokanNet NuGet dokan.dll error

### ISSUE THREAD

**Issue by gmreburn** [dokan-dev/dokan-dotnet#1]
Dokan version = v0.7.3-beta
DokanNet version = v1.0.6.0 (via NuGet)

When you call mount on the IDokanOperations instance the following error occurs:

```
An unhandled exception of type 'System.EntryPointNotFoundException' occurred in DokanNet.dll

Additional information: Unable to find an entry point named 'DokanMain' in DLL 'dokan.dll'.
```

I then downloaded the dokan-dotnet master branch and compiled the dokannet locally and then ran the sample successfully; however, the reference via the NuGet package still does not work.

**Comment by gmreburn** [comment]
Actually, this has nothing to do with the NuGet package. It is occurs when using the 4.5.1 .NET framework.

**Comment by Maxhy** [comment]
I believe it's because your using a 64-bit operating system, build your application in AnyCPU **but** with "Prefer 32-bit" option checked? But in that case it should had use the 32-bit dokan.dll automatically.

**Comment by gmreburn** [comment]
I am using a 64-bit OS. I modified the build to use the "prefer 32-bit" option; however, the same error occurred. 

Are the 32-bit assemblies always installed? I used the release installer and I seem to remember the options were all disabled, with being 32-bit unchecked.
