### ISSUE TITLE
DebugMode

### ISSUE THREAD

**Issue by 63489681** [dokan-dev/dokan-dotnet#101]
When I use the dokan drive's MirrorFS(mirror.exe /d /s /r C:\Users /l m),I can get the usermode log in the Dbgview,but when I use the Dokandotnet's sample ex.Mirror(mirror.Mount("n:\\",DokanOptions.DebugMode, 5)) ,I can't get the usermode log in the Dbgview.
Why is like that?
  Thanks

**Comment by Liryna** [comment]
Hi @63489681,

I have no issue using DokanNetMirror `mirror.Mount("n:\\", DokanOptions.DebugMode, 5);` and DbgView debug output. 
See the screenshot:

![debug](https://cloud.githubusercontent.com/assets/4311419/17830310/55342904-66c8-11e6-8c2a-9de572b684e7.png)


Are you sure you have enable correct option in DbgView ?
