### ISSUE TITLE
Any chance to add NLog as a logging backend?

### ISSUE THREAD

**Issue by Kimi-Arthur** [dokan-dev/dokan-dotnet#105]
Not sure whether this aligns with the project's vision. But having NLog as a possible logging backend, we can do other logging tweaks without modifying the server code.

One possible solution is to provide a built-in class, like the `ConsoleLogger` that implements the `ILogger` interface with the NLog backend inside the package so that we can pass it in.

**Comment by marinkobabic** [comment]
You mean to have the ILogger as driver logger? The driver is written as C code and we can't pass ILogger in. The only option is that driver calls usermode dll which calls ILogger but this is something I wouldn't suggest.

**Comment by Liryna** [comment]
I personally use log4net for the c# logs and I preferred not to include it in dokan library for keeping dokan light.
If we begin to add every logger solution in dokan we will never finish :smiley: 
It is easier for the dev to simply use ILogger and implement his favorite logger.

**Comment by Kimi-Arthur** [comment]
Thanks, that makes sense.
