### ISSUE TITLE
Missing flags in FileAccess

### ISSUE THREAD

**Issue by magol** [dokan-dev/dokan-dotnet#117]
This continue the discussion initiated in #116

In [`DokanNet.FileAccess`](https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/FileAccess.cs) are following flags missing:
 
| Constant          | Value      | Description                                                                                                |
|-------------------|------------|------------------------------------------------------------------------------------------------------------|
| FILE_DELETE_CHILD | 0x0040     | For a directory, the right to delete a directory and all the files it contains, including read-only files. |
| MAXIMUM_ALLOWED   | 0x02000000 | All the access rights that are valid for the caller.                |
| GENERIC_ALL       | 0x10000000 | All possible access rights                                                                                 |

Should we add them, or should the flags be filtrated out?

**Comment by Liryna** [comment]
It seems like there a comment values for now. Thats strange :(

**Comment by magol** [comment]
Do you mean [this](https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/FileAccess.cs#L95)?

They were [added](https://github.com/dokan-dev/dokan-dotnet/commit/b07fa24a3796fadd656004c9c3669103c71e07ac) by me when I commented the code. I saw that they were missing, and added those comments for further diskution. But then I forgot them

**Comment by Liryna** [comment]
Ok !

I think we can add them, it will hurt no one.

**Comment by magol** [comment]
I agree with you.
I add them and create a PR :-)
