### ISSUE TITLE
IDokanOperations.OpenDirectory() with a blank filename (string.Empty)

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokan-dotnet#12]
From @viciousviper

During FileInfo.MoveTo(), DirectoryInfo.MoveTo(), and FileInfo.Replace() there is an irritating call to IDokanOperations.OpenDirectory() with a blank filename (string.Empty) and no associated cleanup calls.

Test Sample C#
```
FileInfo test = new FileInfo("M:\\test.txt");
test.MoveTo("M:\\test2.txt");
```

Mirror.c
```
###Create 0070
   CreateDisposition 0x00000001
CreateFile : C:\Users\test.txt
  AccountName: liryna, DomainName: DESKTOP-RBPTIQA
        OPEN_EXISTING
        ShareMode = 0x7
        FILE_SHARE_READ
        FILE_SHARE_WRITE
        FILE_SHARE_DELETE
        AccessMode = 0x110080
        DELETE
        FILE_READ_ATTRIBUTES
        SYNCHRONIZE
        FlagsAndAttributes = 0x0

CreateFile status = 0
###GetFileInfo 0070
GetFileInfo : C:\Users\test.txt
        GetFileInformationByHandle success, file size = 3

###GetFileInfo 0070
GetFileInfo : C:\Users\test.txt
        GetFileInformationByHandle success, file size = 3

SL_OPEN_TARGET_DIRECTORY specified
###Create 0071
OpenDirectory : C:\Users

CreateFile status = 0
###SetFileInfo 0070  10
MoveFile C:\Users\test.txt -> C:\Users\test2.txt

###Cleanup 0071
Cleanup: C:\Users\test2.txt

###Close 0071
Close: C:\Users\test2.txt

###Cleanup 0070
Cleanup: C:\Users\test2.txt
        invalid handle

###Close 0070
Close: C:\Users\test2.txt
```

With the C mirror there is no OpenDirectory() with a blank filename (string.Empty).

**EDIT:** OpenDirectoryProxy is called with (string.Empty) so there should be a issue in C->C#

**Comment by viciousviper** [comment]
What happens in the .NET Mirror sample?

**Comment by Liryna** [comment]
Ah yes sorry forgot to add it:
MirrorNet: OpenDirectoryProxy ->OpenDirectory  are called with blank name.

I am rebuilding the kernel in debug to check the sys calls. (See if it come from dokany or from du communication dokany->DokanNet).

**Comment by viciousviper** [comment]
I'd be really surprised if Dokan.NET were the culprit. The proxy doesn't really do anything but convert some parameters and forward the calls to the `IDokanOperations` implementation.

**Comment by Liryna** [comment]
I added to DokanNet https://github.com/dokan-dev/dokan-dotnet/commit/a2a53c5f6619b5510685bbe94c57b71065673cb6. Like that I could compare and see what is happening during a `.MoveTo("M:\\liryna\Desktop\test2.txt");`

```
CreateFileProxy :  \liryna\Desktop\test.txt
        CreationDisposition Open
        FileShare ReadWrite, Delete
        FileAccess ReadAttributes, Delete, Synchronize
        FileOptions None
        FileAttributes 0
CreateFileProxy : \liryna\Desktop\test.txt Return :  Success

GetFileInformationProxy :  \liryna\Desktop\test.txt
        FileName :  \liryna\Desktop\test.txt
        Attributes :  Archive
        CreationTime :  8/28/2015 1:11:05 AM
        LastAccessTime :  8/28/2015 1:11:05 AM
        LastWriteTime :  8/28/2015 1:11:13 AM
        Length :  3
GetFileInformationProxy : \liryna\Desktop\test.txt Return :  Success

GetFileInformationProxy :  \liryna\Desktop\test.txt
        FileName :  \liryna\Desktop\test.txt
        Attributes :  Archive
        CreationTime :  8/28/2015 1:11:05 AM
        LastAccessTime :  8/28/2015 1:11:05 AM
        LastWriteTime :  8/28/2015 1:11:13 AM
        Length :  3
GetFileInformationProxy : \liryna\Desktop\test.txt Return :  Success

OpenDirectoryProxy :  \liryna\Desktop
OpenDirectoryProxy : \liryna\Desktop Return :  Success

MoveFileProxy :  \liryna\Desktop\test.txt
        NewFileName :  \liryna\Desktop\test2.txt
        ReplaceIfExisting :  False
MoveFileProxy : \liryna\Desktop\test.txt Return :  Success

CleanupProxy :  \liryna\Desktop\test2.txt
CleanupProxy : \liryna\Desktop\test2.txt Return :  Success

CloseFileProxy :  \liryna\Desktop\test2.txt

CleanupProxy :  \liryna\Desktop\test2.txt
CleanupProxy : \liryna\Desktop\test2.txt Return :  Success
CloseFileProxy : \liryna\Desktop\test2.txt Return :  Success

CloseFileProxy :  \liryna\Desktop\test2.txt
CloseFileProxy : \liryna\Desktop\test2.txt Return :  Success
```

There is no empty string :cry: .
There should be another reason why string.empty happen.

**Comment by viciousviper** [comment]
What is the sequence
> OpenDirectoryProxy :  \liryna\Desktop
> OpenDirectoryProxy : \liryna\Desktop Return :  Success
doing there?

The unit tests for the `MoveTo()` method run in the virtual root directory - so it might well be that this is the corresponding call in your example. Can you try running your test in `M:\` instead of `M:\liryna\Desktop` ?

**Comment by Liryna** [comment]
Sorry >< I even not seen

```
CreateFileProxy :  \test.txt
        CreationDisposition Open
        FileShare ReadWrite, Delete
        FileAccess ReadAttributes, Delete, Synchronize
        FileOptions None
        FileAttributes 0
CreateFileProxy : \test.txt Return :  Success

GetFileInformationProxy :  \test.txt
        FileName :  \test.txt
        Attributes :  Archive
        CreationTime :  8/28/2015 1:11:05 AM
        LastAccessTime :  8/28/2015 1:11:05 AM
        LastWriteTime :  8/28/2015 1:11:13 AM
        Length :  3
GetFileInformationProxy : \test.txt Return :  Success

GetFileInformationProxy :  \test.txt
        FileName :  \test.txt
        Attributes :  Archive
        CreationTime :  8/28/2015 1:11:05 AM
        LastAccessTime :  8/28/2015 1:11:05 AM
        LastWriteTime :  8/28/2015 1:11:13 AM
        Length :  3
GetFileInformationProxy : \test.txt Return :  Success

OpenDirectoryProxy :
OpenDirectoryProxy :  Return :  Success

MoveFileProxy :  \test.txt
        NewFileName :  \test2.txt
        ReplaceIfExisting :  False
MoveFileProxy : \test.txt Return :  Success

CleanupProxy :  \test2.txt
CleanupProxy : \test2.txt Return :  Success

CloseFileProxy :  \test2.txt
CloseFileProxy : \test2.txt Return :  Success

CleanupProxy :  \test2.txt
CleanupProxy : \test2.txt Return :  Success

CloseFileProxy :  \test2.txt
CloseFileProxy : \test2.txt Return :  Success
```

So yes there is an OpenDirectory directoy.
I also understood that Mirror.c have the same behaviour (C:\Users is the mirror mount point so the call is empty too)
```
SL_OPEN_TARGET_DIRECTORY specified
###Create 0071
OpenDirectory : C:\Users
```
This call is special because it have the special flag SL_OPEN_TARGET_DIRECTORY.
Information about it:
https://msdn.microsoft.com/en-us/library/windows/hardware/ff548630%28v=vs.85%29.aspx
http://fsfilters.blogspot.fr/2011/01/about-irpmjcreate-and-minifilter-design_20.html

**Comment by viciousviper** [comment]
Ok, so the driver wants to send an additional `OpenDirectory` on the target directory to the filesystem - that's fine.
I'm only wondering if *dokany* - or possibly the *DokanOperationsProxy* - could map the `string.Empty` to `\` so that the root directory is handled consistently with respect to other API calls (`CreateFile()` and the close/cleanup calls use `\` rather than `string.Empty`).
I know that the root directory is a special case that in itself is not quite consistent with other path expressions. Nevertheless I find it very uncommon to identify root wih `string.Empty`.

**Comment by viciousviper** [comment]
On the other hand, I see two unexplained calls to
`OpenDirectory("\Dir\")` and 
`GetFileInformation("\Dir\")` (only if the previous call returned `DokanResult.Success`)
in the `SetAccessControl_CallsApiCorrectly()` test. Note the additional trailing `\` character.
Could it be possible that in some cases the intended paths get mangled by dokany? I missing `\` for `MoveTo(...)` and `Replace(...)` calls while in the root directory and a surplus `\` for `SetAccessControl(...)` in non-root paths?
Or it may be that this is just the way that low-level file system drivers work. Please enlighten me :grin:

**Comment by Liryna** [comment]
It is dokany who change the fileName in case of SL_OPEN_TARGET_DIRECTORY
https://github.com/dokan-dev/dokany/blob/457bb8a002ba777f3769af5ea50a467104309585/dokan/create.c#L95

EventContext->Operation.Create.FileName '\' become ''

**Comment by Liryna** [comment]
Fixed https://github.com/dokan-dev/dokany/commit/b5e7a2c9ad624e2510dbf995c5bde0a1f6acc75e
