### ISSUE TITLE
Solution mess

### ISSUE THREAD

**Issue by maurosampietro** [dokan-dev/dokan-dotnet#122]
Lately downloading the code and getting started has become a real mess.
Dependencies and some other project settings are forced somehow by fancy code in the .csproj (i guess) and it' not easy to get the solution working. I noticed this since you provide support for framework 4.0 and 4.6 separately.

For example for the Mirror sample project I ended up creating a new project within which i copied the two .cs file needed (Program.cs and Mirror.cs) to make it work.

Hope you opt for simpler and more stable managing of the solution.

**Comment by Liryna** [comment]
Hi @maurosampietro ,

It is true that mirror .csproj use platform check to select the proper library to reference.
https://github.com/dokan-dev/dokan-dotnet/blob/master/sample/DokanNetMirror/DokanNetMirror.csproj#L81-L92
This is an official option in visual studio.

But I see no issue for making it work, even appveyor build all framework.
https://ci.appveyor.com/project/Liryna/dokan-dotnet
It can happen that sometimes you need to build the solution a second time to get all work.
