### ISSUE TITLE
Doc files cannot be saved

### ISSUE THREAD

**Issue by g-fusion** [dokan-dev/dokan-dotnet#124]
Environment

Windows version: Win 10 (MS Word 2013)
Processor architecture: x64
Dokany version: 1.0.0 RC4
Library type (Dokany/FUSE): Dokany

Description

Create *.doc file
Put some content in it
Open *.doc file
Edit it
Save it and error appears a. in UI (The save failed due to out of memory or disk space ( )
C implementation works, .NET implementation does NOT !

[Doc_files_cannot_be_saved.txt](https://github.com/dokan-dev/dokan-dotnet/files/493106/Doc_files_cannot_be_saved.txt)

**Comment by willy-wu** [comment]
Make sure that SetFileAttributes & SetFileTime return Success result.
MS Word will call these functions when saving files. It is work for my file system.

**Comment by g-fusion** [comment]
Hello,

I will try this and will provide feedback.
Thank you.
