### ISSUE TITLE
Notepad save file issue

### ISSUE THREAD

**Issue by adoconnection** [dokan-dev/dokan-dotnet#125]
When saving simple txt file in notepad, almost every time dokan and notepad freezes.

Environment
Windows version: Win 10
Processor architecture: x64
Dokan version: 1.0.0.5000

Steps to reproduce:
1. Create new console app
2. Install-Package DokanNet (v1.1.0)
3. Take sample files Mirror.cs and Program.cs
4. Build & Run app
5. Using Explorer create new text file on mounted drive
6. Edit and save several times

**Comment by Liryna** [comment]
@adoconnection Hi, 

This is a dokan issue on 1.0.0.
It has been fixed already. 

Thanks for the feedback!

**Comment by adoconnection** [comment]
@Liryna thank you for fast reply 👍 
any plans on next release?

**Comment by Liryna** [comment]
End of the week on next one 👍

**Comment by adoconnection** [comment]
great!
