### ISSUE TITLE
The folder isn't created when debugging the Mirror 

### ISSUE THREAD

**Issue by Zhu35** [dokan-dev/dokan-dotnet#126]
During debugging the Mirror in VisualStudio I can't create the folder. There are exceptions:
`"System.IO.FileNotFoundException" in mscorlib.dll.`
Errors in the Mirror log:
`11/08/2016 14:21:29 - [Mirror] CreateFile('\NEW_DIR_NAME', {<null>, False, False, False, False, #10216, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [None], [0]) -> ObjectNameNotFound`
At the same time method CeateFile with `mode='CreateNew'` is absent in the Mirror log

**Comment by Liryna** [comment]
Hi @Zhu35 ,

I just tested it and I have no issue creating a folder with the mirror.
How can I reproduce the issue ?

**Comment by Zhu35** [comment]
I checked it on two computers with windows 7, but this error appears only on one. Therefore I don't know as to you to repeat this issue on your computer. But on my computer the problem arises in 80% in attempt to create the new folder

**Comment by Liryna** [comment]
Exceptions are normal because it is a way to see if the file exist or not.
Otherwise a full logs could help here to see what is happening.

**Comment by Zhu35** [comment]
This is miiror log

[mirror.txt](https://github.com/dokan-dev/dokan-dotnet/files/578146/mirror.txt)

**Comment by Liryna** [comment]
Thank you, I see nothing special in it unfortunatly 😢

**Comment by Zhu35** [comment]
Maybe these logs will help identify the problem. 

This log from the mirror which is installed with the driver dokan areas:
[mirror.log.txt](https://github.com/dokan-dev/dokan-dotnet/files/580208/mirror.log.txt)

This log from kernel output dokan driver (received for this manual - https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan):
[debug.log.txt](https://github.com/dokan-dev/dokan-dotnet/files/580223/debug.log.txt)

**Comment by Liryna** [comment]
Thank you @Zhu35 for the logs.
The kernel logs are empty because debug output are only enable in debug build. You will need to install the debug version of dokan.
