### ISSUE TITLE
Open files as read-only in Office 2007

### ISSUE THREAD

**Issue by willy-wu** [dokan-dev/dokan-dotnet#127]
Hi,
When I use DokanNetMirror example, I encounter a tricky problem in opening Office files.
I have tested the following cases in Windows 7 64-bit:

- Office 2007 + Dokany 1.0.1 + Dokan.NET 1.1.0.1 + DokanNetMirror => Read-Only PowerPoint
- Office 2016 + Dokany 1.0.1 + Dokan.NET 1.1.0.1 + DokanNetMirror => OK
- Office 2007 + Dokany 0.8.0 + Dokan.NET 1.0.8.0 + DokanNetMirror => Read-Only PowerPoint & Word
- Office 2016 + Dokany 0.8.0 + Dokan.NET 1.0.8.0 + DokanNetMirror=> OK
- Office 2007 + Dokany 1.0.1 + Dokan.NET 1.1.0.1 + dokan_mirror=> OK
- Office 2007 + Dokany 0.8.0 + Dokan.NET 1.0.8.0 + dokan_mirror=> OK

It seems to be some problem in DokanNET or DokanNetMirror.
Does anyone have a idea to solve this problem?
Many thanks.

**Comment by Liryna** [comment]
Hi @willy-wu ,

I don't have office 2007. Could you give the mirror C# debug logs :) ?

**Comment by marinkobabic** [comment]
During the file open office writes some files temporarily. I can imagine
that this exception may not be handled properly.

**Comment by willy-wu** [comment]
Hi @Liryna ,

This is my test procedure:

1. There is a Office file "PowerPoint.pptx" in the "OfficeFile" folder. (This file is not Read-Only!)
2. Use DokanNetMirror mount the disk.
3. Mouse double-click "PowerPoint.pptx" to Open file. It show "[Read-Only]" in window's title bar of PowerPoint.
4. Close PowerPoint application.

Please view the mirror C# debug logs.
[DokanNetMirror-v1.0.8.0.log.txt](https://github.com/dokan-dev/dokan-dotnet/files/585171/DokanNetMirror-v1.0.8.0.log.txt)
[DokanNetMirror-v1.1.0.1.log.txt](https://github.com/dokan-dev/dokan-dotnet/files/585172/DokanNetMirror-v1.1.0.1.log.txt)

BTW,
If I execute the DokanNetMirror.exe in Command Prompt directly (don't debug in VS2015), it seems to have no any problem.
Is it possible that VS2015 interfere with Dokan.NET operations?

Thanks.

**Comment by Liryna** [comment]
@willy-wu thank you for the logs.
I guess if it shows the file as read-only is because for him the temporary file has not been created as he wanted.

We see in the logs that it creates it, close it and try again to open it with failure.

Probably this is an issue of synchronization since like you say it works without debugging.
Can you compare the logs without debug enable and see what he do more with the temporary file ?
