### ISSUE TITLE
Windows FS encryption and System Volume Information

### ISSUE THREAD

**Issue by Rambalac** [dokan-dev/dokan-dotnet#129]
When I add ```FileSystemFeatures.SupportsEncryption``` and set encryption for some **file** ```textfile.txt``` in the root I get request for CreateNew ```\textfile.txt\System Volume Information\EFS0.LOG```. Is it correct? According some documentation about NTFS encryption it should create ```\System Volume Information\EFS0.LOG```.

**Comment by Liryna** [comment]
never tested this 👍 
Could you look with procmon what is the request path made exactly ? (to see if it is not dokan that set the path incorrect)

**Comment by Rambalac** [comment]
Checked procmon. Removed all default filters.  There is no any ```textfile.txt\System Volume Information``` in the Path. There is no any path with '''System Volume Information''' at all

**Comment by Liryna** [comment]
There is just \textfile.txt ?

**Comment by Rambalac** [comment]
Yes, there are some ```\textfile.txt```, but ReadAttributes

**Comment by Rambalac** [comment]
As NTFS encryption is transparent probably none of processes can see such disk operation, so not procmon?

**Comment by Liryna** [comment]
I have absolut no idea 😢 do you have a documentation about it to give ?
Probably would need to enable logs and look at the file names to see if we also get `textfile.txt\System Volume Informatio`

**Comment by Rambalac** [comment]
Ok, then maybe later. Do you want to close this ticket?

**Comment by Liryna** [comment]
I think yes if you don't really plan to use it.
Otherwise you can open a ticket on dokany repository directly since it is not related to c# and we will look more about it.
