### ISSUE TITLE
Improper parameter name "used" in the Mirror example.

### ISSUE THREAD

**Issue by sqc1999** [dokan-dev/dokan-dotnet#130]
The parameter `used` [here](https://github.com/dokan-dev/dokan-dotnet/blob/8778863bfcd65f5997dbf6b2144280d61f0e3502/sample/DokanNetMirror/Mirror.cs#L540) seems to be misleading.
According to the Dokany document of this method([link](https://dokan-dev.github.io/dokany-doc/html/struct_d_o_k_a_n___o_p_e_r_a_t_i_o_n_s.html#a640f8ea90833fcd8885f59e63a58f3a7)), the third parameter is `the total amount of free space available to the user that is associated with the calling thread`, not the used space.

**Comment by Liryna** [comment]
Hi @sqc1999 ,

You are right the mirror was not using the correct variables names: https://github.com/dokan-dev/dokan-dotnet/blob/f449c892adf750754d992a9d29b8cf7d3dcdae5f/DokanNet/IDokanOperations.cs#L309-L313

I fixed it 👍 Thanks for the report ! https://github.com/dokan-dev/dokan-dotnet/commit/278c74eaabbe5e9f135b12afe039a95a62f03542
