### ISSUE TITLE
DeleteFile not working.

### ISSUE THREAD

**Issue by sqc1999** [dokan-dev/dokan-dotnet#131]
The `DeleteFile` method is not called.
The break point on this method in my code is never triggered.
I also tested the Mirror example. The one in this repo written in C# can't delete files, but the one in the Dokany repo written in C works.
So I think it is related to this project, not Dokany.
OS version: Windows 10 Enterprise x64 Build 10514
Dokany version: 1.0.1.1000
Dokan.NET version: 1.1.0.1

**Comment by Liryna** [comment]
Hi @sqc1999 ,

The mirror C# can delete files for sure. DeleteFile is not always called. A file can be deleted in CloseFile if it was open with delete on close options in CreateFile.

Also we have tested that run at every build, and all delete test passed.

**Comment by sqc1999** [comment]
@Liryna
Oh, I used the Mirror in C# to delete a file that the current user doesn't have rights to access. Sorry.
Thank you for your information the delete on close option.
