### ISSUE TITLE
Can't work with 7-zip.

### ISSUE THREAD

**Issue by sqc1999** [dokan-dev/dokan-dotnet#132]
Trying to open a zip archive with 7-zip.
If I just right-click the file and extract it using the `7-zip -> Extract files...` button, everything works fine.
But if I open it with 7-zip's GUI, select the files in the archive and extract it, 7-zip reports `Headers Error`.
I even dumped all the bytes returned by my `ReadFile` method and compare it with my zip file, but no difference found.

**Comment by Liryna** [comment]
Hi @sqc1999,

Can you reproduce the issue with the C Mirror from installer ?

**Comment by sqc1999** [comment]
No, I can't reproduce this with C or C# Mirror. I'm just wondering why this will happen even if I returned the correct data.

**Comment by Liryna** [comment]
I cannot tell you. You should compare the results of the Mirror and your application. See if there is any difference.
It can be totally not related to ReadFile but by getfileinformation or getsecurity, ....

**Comment by sqc1999** [comment]
I can play videos with WMP, extract zip using Windows Explorer, open text files with Notepad++, but I can't play videos with VLC, extract zip using 7-zip.
Maybe related to dokan-dev/dokany#34?

**Comment by Liryna** [comment]
Yes, this is not releated to 7-zip so but more about VLC issue that you linked.

**Comment by sqc1999** [comment]
@Liryna
I've figured it out. 7-zip may call `CreateFile` on the archive file with `DokanFileInfo.IsDirectory = true`, then I should return `NtStatus.NotADirectory`. But I forgot to handle this, I just opened the file and return `DokanResult.Success`.
I think it is something easy to forget, maybe mention it in the document?

**Comment by Liryna** [comment]
Thank you for the feedback @sqc1999 ! 
I added to the documentation as requested https://github.com/dokan-dev/dokany/commit/6a1f67f41f2be58b0e735bbcbba5d61f802c67c5
and 
https://github.com/dokan-dev/dokan-dotnet/commit/1fbb7d077e3f643d6c785ece86778768e50a645d

**Comment by sqc1999** [comment]
Happy to see this!
And I've noticed a typo: In the other **hande** => In the other **hand**.

**Comment by Rondom** [comment]
*On* the other hand ☺

**Comment by sqc1999** [comment]
@Rondom I'm not very good at English, thank you for the correction 😄

**Comment by Liryna** [comment]
https://github.com/dokan-dev/dokany/commit/0fb2ddd0a139b8834d9648b0c0cfa13a8216e982 
https://github.com/dokan-dev/dokan-dotnet/commit/80278ee221144df8ba2b0f8be6807bf3d170981c

Thank you guys 👍 😢

**Comment by Rondom** [comment]
That's teamwork 😊
