### ISSUE TITLE
Strange search pattern "<

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokan-dotnet#133]
So... I was experimentig with some softwares and mirror fs.
One of those got stuck in an infinite loop of trying to save a file.
It turns out that the software tries to backup the old file using this pattern: `filename.[\d{4,4}].ext`, before doing so, it asks for all the files matching that pattern, max the matches and move the old file.
it was failing because the search pattern it was using was `filename."<.ext`.
Now... that software works fine outside dokan mirror fs, substituting the `"<` with an `*` also makes it work again.
My doubt is that somewere in dokan there might be a double encoding, or an encoding error in general, any idea how to find it out ?

**Comment by Rondom** [comment]
Before I try several different possibilities.... Can give a more concrete example on how to reproduce this?

**Comment by TrabacchinLuigi** [comment]
Never tried c-mirror.
The software that does that is not open source, long to download and to install and very costly ... so i won't suggest trying with that, but i could try it for you, also i could try to build a demo software that behaves the same...

**Comment by TrabacchinLuigi** [comment]
I've sent you an email with some details.

**Comment by TrabacchinLuigi** [comment]
So i figured out how to test with mirror.c and it works, but the strange search pattern is still there

`###FindFiles 0384
FindFiles :C:\test\source\
	FindFiles return 7 entries in C:\test\source\*

index from 0
FileMatch? : New Text Document.txt (Project1"<.rvt,0,0)
FileMatch? : Project1.0001.rvt (Project1"<.rvt,0,0)
  =>return single entry
index to 1
index from 1
FileMatch? : New Text Document.txt (Project1"<.rvt,1,0)
FileMatch? : Project1.0001.rvt (Project1"<.rvt,1,0)
FileMatch? : Project1.0002.rvt (Project1"<.rvt,1,1)
  =>return
FileMatch? : Project1.0003.rvt (Project1"<.rvt,1,2)
  =>return
FileMatch? : Project1.rvt (Project1"<.rvt,1,3)
index to 3
index from 3
FileMatch? : New Text Document.txt (Project1"<.rvt,3,0)
FileMatch? : Project1.0001.rvt (Project1"<.rvt,3,0)
FileMatch? : Project1.0002.rvt (Project1"<.rvt,3,1)
FileMatch? : Project1.0003.rvt (Project1"<.rvt,3,2)
FileMatch? : Project1.rvt (Project1"<.rvt,3,3)
  STATUS_NO_MORE_FILES`

**Comment by Liryna** [comment]
Hi @TrabacchinLuigi ,

I don't know if you contacted @Rondom already but is it possible to reproduce this ourself ?
Otherwise there is processmonitor https://technet.microsoft.com/fr-fr/sysinternals/processmonitor.aspx that can display the request and probably can give some information about it.

**Comment by TrabacchinLuigi** [comment]
Hi @Liryna 
![image](https://cloud.githubusercontent.com/assets/136717/22654419/f7c68e56-ec8c-11e6-8979-2d9aab065c12.png)
Actually yes, just download a copy of Revit from Autodesk, start a trial and try.
As you can see in this screenshot accordingly to procmon it search for `filename.*.ext` not `filename."<.ext`

**Comment by Liryna** [comment]
Ok thanks you !
I don't have my computer right now with me.
Do you think you can try to reproduce this with a sample C win32 ?

**Comment by TrabacchinLuigi** [comment]
The output i've attached before it was from `mirror.c`, i just started the one that get deployed with dokan and attached a debugger to it

**Comment by Liryna** [comment]
I understood :heart: I was meaning a sample to execute a read dir with the same regex that I can use on the mirror later to reproduce it easily.

**Comment by TrabacchinLuigi** [comment]
I can't 😭 i don't know how to code in c...
I could do it in C# but i fear that since every string is unicode in C# this won't happen...

**Comment by Liryna** [comment]
Ok I see @TrabacchinLuigi , It will take some time until I find some :cry:

**Comment by Rondom** [comment]
Sorry, forgot to report back here.

I tried reproducing by running

    echo foo > Project1.0001.rvt
    dir "Project1.*.svt

and I got the strange output in the mirror log. But the output of `dir` is as expected. So I thought that this is a display error.
Also from the procmon-screenshot you posted I can see that the response looks quite normal, from what I can see. It returns Project1.0001.rvt, Project1.0002.rvt, Project1.0003.rvt. Project1.0004.rvt. Or am I misunderstanding something? I think I do, because you write that replacing `"<` with `*` makes it work, i.e it is NOT "only a display error"

@Liryna Btw, do you know of any tool that takes a recording from ProcMon and converts it to code?. This would be extremely useful for reproducing things and creating regression tests.

**Comment by TrabacchinLuigi** [comment]
Great!! i didn't expected that using cmd it would have failed too. thanks @Rondom 👍 
I do actually get wrong string in `Mirror.cs->FindFilesWithPattern`, so, yes it's a problem...
![image](https://cloud.githubusercontent.com/assets/136717/22660040/40f1bea8-eca0-11e6-8196-2337f553008f.png)

**Comment by TrabacchinLuigi** [comment]
I've managed to fork, clone, install WindowsSDK, WDK and build dokany 😌, but no way i can debug it 😞, i just don't have enough experience with building/debugging drivers...
But i do really think the problem could be [here](https://github.com/dokan-dev/dokany/blob/master/dokan/directory.c#L533).

**Comment by Rondom** [comment]
I read the C-Code that you linked and the replacement of characters seems to be by design, because that is how MS handles the filters internally (@Liryna correct me, if I am wrong). This is not documented anywhere. :-(
See https://github.com/dokan-dev/dokany/blob/062d80474d90627364d52fee437fe18d1c1c0442/dokan/directory.c#L616-L635

The problem does not occur with the C-Mirror, because it does not implement FindFilesWithPattern and the Dokan library does the filtering itself. So, I think that the C#-Mirror has to be fixed to account for the filtering characters and the filtering characters itself should be documented in both the C and the C# documentation of `FindFilesWithPattern()`.

**Comment by TrabacchinLuigi** [comment]
Some more details: 
The string does change between the calls, if i set a break point [here](https://github.com/dokan-dev/dokan-dotnet/blob/master/sample/DokanNetMirror/Mirror.cs#L71) i get the right string
![image](https://cloud.githubusercontent.com/assets/136717/22690963/7bf9c1ce-ed38-11e6-9756-68a5bdaab856.png)
Instead setting a break point [here ](https://github.com/dokan-dev/dokan-dotnet/blob/master/sample/DokanNetMirror/Mirror.cs#L647) i get the wrong string. Going back in the call stack i can see this:
![image](https://cloud.githubusercontent.com/assets/136717/22691082/007a5b34-ed39-11e6-873d-2f1a384db765.png)
That's why i think it is a problem of c implementation not dotnet

**Comment by Rondom** [comment]
As I said above I think the "wrong string" is in fact the right string, because this is how the filter-string looks in the kernel. See the link to the Microsoft-documentation described in the Dokan-Library-source-code I linked in my previous comment.  (This my knowledge gained from reading the comments in the C-Code linked and highlighted in the pervious comment)

Thus, the C#-Mirror needs to fixed. It might be difficult/impossible to convert from a Kernel-Pattern to a pattern supported by the .NET-API (because the `<`-character (`DOS_STAR`) has no equivalent in the .NET API [DirectoryInfo.GetFiles Method (String)](https://msdn.microsoft.com/en-us/library/8he88b63(v=vs.110).aspx)

**Comment by TrabacchinLuigi** [comment]
Oh... I think I understood... so those chars have been mapped as DOS_DOT = " and DOS_STAR = < and the other one as > 
So... Those chars are invalid as part of a path and could be safely substituted? I can provide a quick fix very soon and maybe a test too

**Comment by Liryna** [comment]
Hi guys 😃 ,

Looks like you guys worked a lot on this 👍 
I agree that it would be great to convert the DOS to regex that can be used in C# but we have to be sure to not make things "worst".
>DokanIsNameInExpression is in the C-API, but is not exposed in the C#-API. Instead of calling the C-version from C# and induce overhead for converting types, it might be faster to use the C#-version, but it might also be the other way round. No matter what (C# or C), it would be useful to have that method in the dokan-dotnet as well.

I totally agree with this. If we cannot make a safe conversion we should use DokanIsNameInExpression.
I had no time to look on the PR @TrabacchinLuigi . I seen your second commit and it is alright ❤️ ^^.

**Comment by TrabacchinLuigi** [comment]
I could write some unit test if we find out what should match and what not 🔨

**Comment by nguyendotuong** [comment]
Could you guy please tell me why searchPattern is always "*" when I try to use search box for searching (top right explorer)? In this case, I input "test". My expectation is searchPattern equal to "test*".
![search_pattern](https://cloud.githubusercontent.com/assets/9045009/25473245/e6d5e6ae-2b58-11e7-8461-081cfdad4674.jpg)
Thanks!

**Comment by TrabacchinLuigi** [comment]
What windows does isn't open sourced, so there is no sure answer.
We can guess that windows search enumerate folders, and open files to search the content of them.
By the way your statement is false, the pattern isn't always an empty string, i just tested, try to use a conditional breakpoint instead of a normal one

**Comment by nguyendotuong** [comment]
Sorry Luigi! I mean the pattern is * (the text editor has an issue for displaying *).

**Comment by TrabacchinLuigi** [comment]
So it's just windows search enumerating files in folders and sub folders.
I guess this is because, windows search won't just look for the name of file but also content and metadata, so it will just ask the operating system for everything and internally do it's search with it's own criteria.

**Comment by magol** [comment]
@TrabacchinLuigi, @Liryna
Is it any tests for this functionality (in unit tests and/or winfstest)?

**Comment by Rondom** [comment]
I posted some links to tests in the PR or the issue, but they are under am incompatible licence

**Comment by TrabacchinLuigi** [comment]
@magol There where, we removed them because licence as @Rondom said.

**Comment by magol** [comment]
Ahh, now I remember. I have short memory 😣. 

But it should not be that difficult to implement these tests ourselves. Incomplete tests are better than no tests at all.

**Comment by Rondom** [comment]
Indeed. I have plans to run Microsoft's IFSTest which might cover come cases in a black-box manner. Challenge is to find a selection of tests that are sensible to support. There are quite a few more NTFS-specific tests in there.
