### ISSUE TITLE
Wrong version string dll on Nuget

### ISSUE THREAD

**Issue by jhlee8804** [dokan-dev/dokan-dotnet#135]
The build date is correct, but the version text is not `1.1.0.1`.  
Thanks.

Nuget: https://www.nuget.org/packages/DokanNet/1.1.0.1  

![image](https://cloud.githubusercontent.com/assets/8110371/22741565/f61c6550-ee56-11e6-95dd-e84ad8b9d1a3.png)

**Comment by Liryna** [comment]
Hi @jhlee8804 ,

Yes you are right. Thanks for the report.
This has already been fixed in a commit https://github.com/dokan-dev/dokan-dotnet/commit/6d967bede09e793d81e77df0e2f7ad7a48c1407c
