### ISSUE TITLE
SetTime while stream is open

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokan-dotnet#136]
I found out that some software update the last write time while they still have the stream opened, this cause it to fail because of the simplified API the framework exposes.
The framework open a stream to obtain a file handle and use it to pinvoke windows api, obviously it can't if there is another stream already opened ... 
I've already implemented a solution for that. I've copied what the framework does, Seems that it works... I will update you with some code, and maybe some failure examples...
You can reproduce it using Revit and the mirror.cs saving some workshared projects it will fail.

**Comment by TrabacchinLuigi** [comment]
Some documentation:
[System.IO.File.SetCreationTimeUtc](https://referencesource.microsoft.com/#mscorlib/system/io/file.cs,63bd669b43be5f17,references)
From this we can understand that this data is not in the file, but in the filesystem, so if we want to mirror it using .net we need to use the file handle and windows API

**Comment by Liryna** [comment]
Hi @TrabacchinLuigi ,

This is true, it is how windows filesystem work. I don’t think we can improve the situation.
FileStream give access to the handle so it is "easy" to call the win32 API like you said.

Otherwise it is still possible to not open the file with the proposed to share access and override it by something that would let the SetCreationTimeUtc.

**Comment by TrabacchinLuigi** [comment]
My proposal is to fill a bug to the .net team and create a method in SafeFileHandle to set the time, meanwhile i'm creating a nuget packet that have an extension method to do that... what you think ?

**Comment by TrabacchinLuigi** [comment]
I can't find where to fill this proposal/bugfix to the .net team 🙄

**Comment by magol** [comment]
I think https://github.com/dotnet/corefx is the right place for proposal to  .Net. But i can be wrongly.

**Comment by TrabacchinLuigi** [comment]
I gave it a shot, I'll be happy if you guys could join the [discussion](https://github.com/dotnet/corefx/issues/16187) and say what you think.
