### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by magol** [dokan-dev/dokan-dotnet#137]
On March 7 is Visual Studio 2017 [launched](https://blogs.msdn.microsoft.com/visualstudio/2017/02/09/visual-studio-2017-launch-event-and-20th-anniversary/) . One of the big news is that csproj file will be greatly simplified and supports multi-targets.

Additionally, Microsoft now recommend that we should use [.NET standard](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) for packages. In this case, we should replace the .NET Framework 4.6 with .NET 1.3 Standard 

Today we have two separate projects, one for .NET 4.0 and .NET 4.6. I recommend that we replace these with a single project in VS2017-format that multi-target to `net4.0` and `netstandard1.3` (the same as .NET 4.6).

## Open questions
* When do AppVeyor support Visual Studio 2017?
* Is it possible to open the new csproj-file in older Visual Studio (probably not). 
  * If not possible to open in older Visual Studio, is it a problem?
     * If it is a problem, how long should we wait for all devs to update to Visual Studio 2017?
* Should we maybe have a separate csproj file in the old format to make it possible for users of old Visual Studio to compile? It is enough that there is a project file only for .NET 4.6 (or .NET 4.0). The downside is that the environment becomes more complicated when we have to make sure to keep this project file up to-date when we do not use it.

**Comment by Rondom** [comment]
> When do AppVeyor support Visual Studio 2017?
They do have a beta and I think I have read that they plan to make it official soonly after VS2017 is released.

**Comment by Liryna** [comment]
👍 This is a good idea, it should be made when VS2017 is released. I guess they will make a community version for people to get it in any case.
(hope that VS 2017 will be more stable that VS 2015)

**Comment by Liryna** [comment]
What about nuget, is it already capable to install properly  .NET standard library ?

**Comment by magol** [comment]
@Liryna Yes, VS2017 do properly install .NET standard libraries from NuGet.
But it is still some bugs in VS2017 :-(

**Comment by TrabacchinLuigi** [comment]
Net standard and xprojs have been a pain, but now it looks like they are not going to change much more, new csprojs are quite easy to configure and I think a retro compatibility for vs2015 patch will enable to build those projects soon... Also vs2015 and 2017 live side by side with no issues, we will install vs2017 as soon as it is released.
Kinda worth to target more projects...

**Comment by Rondom** [comment]
[AppVeyor's VS2017-image is available to the public](https://www.appveyor.com/docs/build-environment/#pre-installed-software)

**Comment by magol** [comment]
I'm getting happy with it now. I have not yet been able to test netstandard1.3, MStest lacks functionality for DataRow when running under .NET Core 1.X. Perhaps we can fix this in a separate PR.

Can you please review what I have done. When everything is ready for merge, I'll clean up all the commits.

**Comment by Liryna** [comment]
Can be closed with @magol PR 👍 
Thanks a lot for your work !
