### ISSUE TITLE
Clear mirroring folder after stop application

### ISSUE THREAD

**Issue by morozovcookie** [dokan-dev/dokan-dotnet#140]
Hello! I use dokan for mirroring directory from my PC. In my application, I can caching files from some directory or remote disk, like Google Drive, in some application folder. Then I mirroring my application folder into virtual drive.
When my application is starting I creating files with zero length with same name like in original folder. When my application is stopping, I want to delete this files. How I can detect when my application is stopped? I think I need to use Unmount(), but this method is not callable.
Thank you.

**Comment by Liryna** [comment]
Hello @morozovcookie ,

Do you mean your application need to unmount the virtual drive created by Dokan ?
This can be done by calling [DokanNet.Dokan.RemoveMountPoint](https://dokan-dev.github.io/dokan-dotnet-doc/html/class_dokan_net_1_1_dokan.html#a5b3d76480ead72d65b4083ff45ff5d4a) with the mount path used during the mount.

Tell me in case I miss understood your need

**Comment by morozovcookie** [comment]
Seems it like what I need, but it still does not work :C 
I wrote this:
```csharp
var virtualDrive = new VirtualDrive(ApplicationFolder, options.Label);
virtualDrive.Mount(@"Y:\", DokanOptions.DebugMode | DokanOptions.MountManager);
Dokan.RemoveMountPoint(@"Y:\");
```
and I don't see Unmounted() log (VirtualDrive class inherited IDokanOperations).

Ok, I use dokany v1.0.3 and dokan-net v1.1.0.3 and your example from dokan-net repo. When I try write like this:
```csharp
var mirror = new Mirror("C:");
mirror.Mount("n:\\", DokanOptions.DebugMode, 5);
Console.WriteLine(@"Success");
```
I don't see "Success" message after mount and after shutdown my application. What I need to do:

1. I have some folder on my PC
2. When I start my application, I read this folder and create empty directories and files in TEMP folder
3. Then I mirroring TEMP folder using by Dokan
4. When I shutdown my application using by CTRL+C or "Stop" button in IDE I need to remove empty files and directories from TEMP.

I want to catch unmounted event or on_exit event for deleting empty folders and directories.

**Comment by morozovcookie** [comment]
Okay, I found solution with some magic to catch OnExit event when I shutdown application using by CTRL+C. I think this is good and in the future when I create button "Unmount" in my application (now it's just a console application) I try to use RemoveMountPoint().
Thank you very much for your help!
