### ISSUE TITLE
Help git is confusing me

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokan-dotnet#142]
Hi guys...
I know this isn't GIT help desk... but ... 
I need some help with GIT, since the last merge, i'm unable to merge back to my fork, is like the history is broken ... i'd like to go on with my contributions but i don't know how 🤕 🆘

**Comment by Liryna** [comment]
Hi @TrabacchinLuigi ,

What is your issue exactly ?
Most simple could be to refork and copy your changes manually sometimes 😢

**Comment by TrabacchinLuigi** [comment]
Actually it says i have nothing to merge back, it's just like if it thinks i'm ahead with commits... 
It was a solution i had in mind, but i feared losing my part of history... but maybe not ...

**Comment by Liryna** [comment]
Keep a local copy before doing something 👍 in case of

**Comment by TrabacchinLuigi** [comment]
Thanks! i'll do like this!

**Comment by Rondom** [comment]
it's always good to have a backup :-)
Git makes it pretty hard to really loose committed data. Before doing dangerous operations it is always a good idea to to create a new-branch as a backup (a branch is basically a pointer to a commit).
If something went wrong, you can recover old commits using `git reflog` (`git show` and `git log` are useful for inspecting those commits). Checking out the one of the refs printed there into a new branch makes it reachable again.

If you are rebasing/merging/cherry-picking `git status` will usually tell you what to do in case of conflicts. You will need to resolve the conflicts and then `git add` the files to mark the conflict as resolved. `git checkout --ours` / `git checkout --theirs` can be useful to discard one or the other side of the change. If you just want to give up and return to before you invoked the merge or rebase , `git status` will also tell you how to do that (`git <merge/rebase/cherry-pick> --abort` usually).

**Comment by TrabacchinLuigi** [comment]
Thanks, next time i'll work with that in mind 👍
