### ISSUE TITLE
Hanged file streams

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokan-dotnet#146]
Hello guys, since we noticed something weird lately: some file streams where not closed,
I've started my quest to discover why.
This lead to the horrific branch f333ee619a81ccef0faaa7665efda54748c589b1 that i've just pushed in my fork, where i've built a WPF inspector to discover what was going on...
What i've discovered is that if we return `AccessDenied` in `CreateFile` there isn't a following call to `Cleanup`.
Also in [Mirror.cs->CreateFile](https://github.com/dokan-dev/dokan-dotnet/blob/master/sample/DokanNetMirror/Mirror.cs#L205) an actual file stream has already been created and will never be disposed because of that.
In my branch i've added some logic to avoid leaving the stream there, but maybe calling `Cleanup` even if we returned `AccessDenied` could be a nicer idea!

**Comment by Liryna** [comment]
Hello @TrabacchinLuigi ,

Return an error like `AccessDenied` make the kernel request stop. It mean there is going to be no cleanup / close because normally there is nothing to clean.
Does that mean somewhere in our createfile we have a valid stream created but we return acces denied ?

**Comment by TrabacchinLuigi** [comment]
On the line I've linked in the actual implementation of mirror.cs, there it could happen

**Comment by Liryna** [comment]
Oh ! So it could be something like the stream open but `File.SetAttributes` fail ?

**Comment by TrabacchinLuigi** [comment]
Exactly!

**Comment by TrabacchinLuigi** [comment]
In my branch you can also see the pinvoke for setting the file times, I'm still thinking how to share this

**Comment by Liryna** [comment]
Your fork changes: https://github.com/dokan-dev/dokan-dotnet/compare/master...TrabacchinLuigi:Feature-StructuredContext?expand=1
Having `SetFileTimeUtc` could be interesting yes !

What does the tools is doing ?

There is lots of changes in the mirror like TryAndLog that seems to do the same as DokanOperationProxy that try catch all operations ?
About FileStream leak during `File.SetAttributes`, this is our fault, we should clean the Context if we return an error.

**Comment by TrabacchinLuigi** [comment]
the tool group the calls by context, and change colors to make it clear if closed or cleanup is called, or if an exception has been thrown, then starts a timer to clean the cleaned/closed groups if they don't have any errors, kind of logger but visual one

**Comment by Liryna** [comment]
Ok I see !
Do you think this could be integrated in DokanNet.Tests without the graphic part ?

**Comment by TrabacchinLuigi** [comment]
The fix ? sure, i will make a pull request as soon as i have a little spare time!

**Comment by Liryna** [comment]
The fix is interesting but I was meaning the WPF tools you made if it could be integrated in DokanNet.Tests without the graphic part to make it integrated to the CI build.

**Comment by TrabacchinLuigi** [comment]
Uhm ... maybe adding some events we could write some tests ... need to think about it ...

**Comment by Liryna** [comment]
@TrabacchinLuigi can this be closed ?

**Comment by TrabacchinLuigi** [comment]
I'm opening a pull request to fix mirror.cs... BUT i think that  returning AccessDenied should not prevent CleanUp from being called... it's misleading...
Also i can't think how to make this testable, because we are saying 

> you should not close your streams because we gonna clean them up

but then i'm expecting ppl who implement IDokanOperations to close their streams in particular cases ... 

Maybe we should use the context in a different way, enforcing every call to open/close their streams, maybe the context should be a dictionary of "filesystem handles" (a dictionary of relative paths) that we consider opened, instead of actual streams...

**Comment by Liryna** [comment]
OK I see what you mean with the PR.
Cleanup will not be called because CreateFile failed, for the kernel, this means no context could be created so nothing to cleanup.
Here it is the mirror fault to not cleanup properly. We should check before to return if a context exists and if we are in failure, if so, need to dispose as you did but also handle all other cases.

**Comment by TrabacchinLuigi** [comment]
Maybe if no more calls needed and context is not null call cleanup?

**Comment by TrabacchinLuigi** [comment]
P.s. maybe we can enforce that context should be disposable and dispose it when it's out of context?

**Comment by Liryna** [comment]
We try to follow the kernel workflow, adding an extra call would probably create more issues. All implementation should handle their context cleanly => Create in CreateFile and cleanup in cleanup.
Context is linked to dokan C library, we cannot know if it is disposable or not.

**Comment by Liryna** [comment]
Hi @TrabacchinLuigi ,

I hope I have answered your question, do not hesitate otherwise and I will reopen the issue.
