### ISSUE TITLE
[Mirror] SetFileAttributes/SetFileTime while copying a file.

### ISSUE THREAD

**Issue by Deathspike** [dokan-dev/dokan-dotnet#149]
When doing a file copy in Windows Explorer on Windows 10, the function `SetFileAttributes` is called while the file is open. The `Mirror.cs` calls `File.SetAttributes` which fails with a `FileNotFoundException` due to the file being in copy. Since the file does not exist. `SetFileTime` is not called at all. This results in a copied file without its original attributes (e.g. read-only or hidden) and with the current time, rather than the original file creation / access / modified time. What would be the correct way to handle this?

**Comment by Liryna** [comment]
Hi @Deathspike ,

This seems to be duplicate with https://github.com/dokan-dev/dokan-dotnet/issues/136
Is that the case ?

**Comment by Deathspike** [comment]
Possibly. But since SetFileAttributes happens earlier, SetTime is not called at all. It might be a little different.

I'll look into a PR then.
