### ISSUE TITLE
[Mirror] Delete a file in use

### ISSUE THREAD

**Issue by Deathspike** [dokan-dev/dokan-dotnet#150]
When you delete a file that is in use in Windows Explorer on Windows 10, the error message will appear that the file is in use, but the file will be removed from the file listing. I'm guessing this is something that Windows Explorer does as an assumption, but this does not happen on a real drive. Is there a way to tell Windows Explorer that the delete actually failed?

**Comment by Liryna** [comment]
Can you give a screenshot and logs of the mirror ?
I never got such message.

**Comment by Deathspike** [comment]
This is what I see happening.

Gif:
http://imgur.com/N5Ky74x

Log:
https://gist.githubusercontent.com/Deathspike/189adf220932546860b38a5c776184bb/raw/8844f46c17b63f6c55e4128bb2f693aac0f580b0/gistfile1.txt

**Comment by Liryna** [comment]
Thank you for the informations @Deathspike 

This is an issue on the mirror. It should check if the on DeleteFile if it is not already opened and can be removed.
https://github.com/dokan-dev/dokan-dotnet/blob/master/sample/DokanNetMirror/Mirror.cs#L408-L423

This would need to keep in memory the file count usage and return a proper failure if used.

When you refresh explorer, the file is still here right ?

**Comment by Deathspike** [comment]
Yes, the file is not actually removed. 

Since `DeleteFile` essentially acts like a 'CanDeleteFile', all it would take is a reference counter?

**Comment by Liryna** [comment]
Yes, track every CreateFile / CloseFile and use this tracking in DeleteFile to see if it can be removed or still used.

**Comment by Deathspike** [comment]
This doesn't appear to work. I tried rewriting:

`return Trace(nameof(DeleteFile), fileName, info, DokanResult.Success);`

To:

`return Trace(nameof(DeleteFile), fileName, info, DokanResult.AccessDenied);`

And nothing appears to change. The file still disappears from Windows Explorer. So even if my reference counting would work, explorer is still convinced that the file is deleted.

**Comment by Liryna** [comment]
Hi @Deathspike ,

Does this also happen with the C mirror ? (sorry to write the same message but it is important to see if it is not a C# implementation issue).

**Comment by Deathspike** [comment]
Yes. I added a

`return STATUS_SHARING_VIOLATION;`

In DeleteFile at the top. Same result. It's never called.

**Comment by Liryna** [comment]
Oh it is never called ? 
This is different so ! when you delete a file, this can be made by a CreateFile with DeleteOnClose option or by a set delete flag after the createfile.

It is possible that here the CreateFile pass with the delete and therefore the close happen to delete. CreateFile should fail if we do not want to remove it.

**Comment by Deathspike** [comment]
Alright. Handling CreateFile's FileOption.DeleteOnClose seems do something.

What does `DeleteFile` actually do? Perhaps it works only on older OS than Win8/10?

**Comment by Liryna** [comment]
DeleteFile is called when app call `SetFileInformationByHandle ` with FILE_DISPOSITION_INFO with the DeleteFile member set to TRUE on a handle previsouly opened NOT with the deleteonclose.
Even, this can be called a multiple time if the app want to clear the delete flag and such.

**Comment by Deathspike** [comment]
Thanks for the information. I'll test that out.

I tried doing it properly in `CreateFile`, but is not called when trying to delete a running `.exe`. I added:

            if (info.DeleteOnClose || options.HasFlag(FileOptions.DeleteOnClose))
                Debugger.Break();

At the top of `CreateFile`. It never triggers the break point.

**Comment by Liryna** [comment]
does `deletefile` function is called ?
