### ISSUE TITLE
[Mirror] SetAttributes does not receive original attributes

### ISSUE THREAD

**Issue by Deathspike** [dokan-dev/dokan-dotnet#152]
*Problem:*
When I copy a file from a regular volume into a Dokan mirror volume, the attributes are not copied.

*Steps to reproduce:*
1. Create a file with and set the read-only and hidden attributes.
2. Copy the file to a Dokan mirror.
3. See that the file does not receive the attributes.

*Expectation*:
The file copied into the Dokan mirror will have the read-only and hidden attributes.

**Comment by Deathspike** [comment]
It seems like this is mostly due to SetAttributes being called with 0 after a file copy, clearing the attributes that were set in CreateFile

**Comment by Liryna** [comment]
Hi @Deathspike ,

To you have the same behavior with the C mirror ?

**Comment by Deathspike** [comment]
Yes, this also happens in the C mirror. (Using `l M /n` as per the powershell script)

**Comment by Liryna** [comment]
@Deathspike Sorry for the delay. SetAttributes with 0 according to Microsoft doc is not a value. It just means that the attribute should not be updated.
