### ISSUE TITLE
Access Dokan mount as administrator?

### ISSUE THREAD

**Issue by Deathspike** [dokan-dev/dokan-dotnet#153]
This is more of a question than anything else:

I am running the mirror and put an executable that requires Administrative privileges inside. When I launch that executable, I receive the UAC prompt for administrative privileges and click to continue. At that point, Windows tells me that `N:\..` does not exist. I presume this is because the dokan mount is specific to my user account? If so, is there a way to tell dokan to mount the drive for everyone using the computer?

**Comment by marinkobabic** [comment]
Except you specify the drive as network or current session the drive is by
default visible to all users logged in on this machine.

Am 06.08.2017 14:57 schrieb "Roel van Uden" <notifications@github.com>:
