### ISSUE TITLE
Wrapper .NET core

### ISSUE THREAD

**Issue by easlure** [dokan-dev/dokan-dotnet#154]
Hello,

First, thanks for your work and your implementation of Dokan.NET.
I would like to know if Dokan.NET can be wrapped for .NET Core or if i can encounter some instabilities or performances issues.

best regards.

**Comment by Liryna** [comment]
Hello @easlure ,

Some features were missing in .NET Core when @magol tried to migrate it https://github.com/dokan-dev/dokan-dotnet/pull/138#issuecomment-296466559
Now that 2.0 is released, maybe we can take a look.

**Comment by magol** [comment]
The missing features was only used in the unit tests. The implementation is alredy in .net standard, but it is not released yet. 

I will see if i can fix the unit tests now, so we can release it.

**Comment by easlure** [comment]
Ok, Thanks for everything, we will begin our migration soon as released is published.

**Comment by hali15845** [comment]
I also want to express interest in a .Net core release. Thanks,

**Comment by Jotune** [comment]
While the final realese isn't read, here is a [Dokan wrapper for .NET core](https://github.com/Jotune/dokan-dotnet-core). It works on my projects, no problems encountered so far. I've been using it since Sept. 2017.

**Comment by Liryna** [comment]
Hi @Jotune ,

That seems to be a great job you just did here ! Do you think you can apply these changes in a pull request for this repository to see exactly the difference and also to integrate them ?

**Comment by Jotune** [comment]
@Liryna : sure 😃

**Comment by CiriousJoker** [comment]
It's almost exactly a year later, what was the outcome of this discussion?

**Comment by Liryna** [comment]
Hi @Jotune ,

Are you still planning to do a PR ?

**Comment by Jotune** [comment]
Hi @Liryna,

No. This project already is compatible with .NET Standard which is the way to go when working with .NET  Core. I still have my fork in the link above if someone is interested in comparing the sources but I see no point in doing a PR anymore.

**Comment by Liryna** [comment]
Thank you for the answer @Jotune 👍
