### ISSUE TITLE
CreateFile with Empty filename

### ISSUE THREAD

**Issue by Youngdore** [dokan-dev/dokan-dotnet#157]
I'm working on my individual project utilising dokan-dotnet.

When I tried to put a file on the root directory of the mount point  by drag&drop,
I caught the trace, **CreateFile('', {<null>, False, False, False, False, #9460, False, False}, [ReadData, DeleteChild], [None], [CreateNew], [SequentialScan], [Archive])**.

What's the meaning of this? How can I properly deal with this?

(Environment Windows 10 Pro 16299/ DokanNet 1.1.0.3 from Nuget Package)

**Comment by Liryna** [comment]
Hi @Youngdore ,

Empty file name is the same as the root folder `M:\`

**Comment by Youngdore** [comment]
Thank for such fast reply, @Liryna.

So this means "creating a new directory M:\".
Should I have to return "success" or "already exist"?

**Comment by Liryna** [comment]
@Youngdore already exist would be good here !
You should probably run the C# mirror https://github.com/dokan-dev/dokan-dotnet/tree/master/sample/DokanNetMirror with logs enabled to reproduce the main calls behavior.

**Comment by Liryna** [comment]
Humm could it be possible that you provide during a listing an empty file name ?

**Comment by Youngdore** [comment]
@Liryna I'm not sure but it could be possible.

The project I'm working on is to make a remote file system accessible as a local drive in Windows.
After the system got AccessDenied against the CreateFile with the new file,
it produces the problematic call with an empty filename.

**Comment by Liryna** [comment]
@Youngdore have you been able to find what create this call ?

**Comment by Youngdore** [comment]
@Liryna The problem was that kernel keeps creating file handles of root and my software was written to simply pass those requests to fetch root item and its children on remote. But, remote side was not able to process all the requests properly. So erroneous processing results make the problematic call.
It's because of lack of understanding how dokan behaves.  

You can close this! Very appreciate!

**Comment by Liryna** [comment]
@Youngdore good to see you could fix the issue !
