### ISSUE TITLE
Error in .NET Mirror sample when copying a file to the mirror volume

### ISSUE THREAD

**Issue by viciousviper** [dokan-dev/dokan-dotnet#16]
The following trace is the result of trying to copy the 3 MB file "BouncyCastle.1.7.0.nupkg" from a different drive into a Dokan.Net mirror volume (Mirror sample, drive D: mapped as R:, standard settings with 5 threads, Dokan 0.7.4 x64 on Windows 8.1 x64).

There is an epic failure at the end of the call sequence when Dokan tries to set the file date while the target file is still in use by another operation.

There is also at least one curious thread interference in the partial call sequence 
> CloseFileProxy : \Temp\Source
>
> CreateFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		CreationDisposition     Open
> 		FileAccess      ReadData, ReadExtendedAttributes, ReadAttributes, ReadPermissions, Synchronize
> 		FileShare       Read
> 		Context <null>
> 		FileOptions     None
> 		FileAttributes  Normal
> 		Context <null>
> CreateFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : FileNotFound
> CloseFileProxy : \Temp\Source Return : Success

Has anyone ever tested writing into a Mirror volume?

**Trace below**
> D:\dokan-dotnet\sample\DokanNetMirror\bin\Debug>DokanNetMirror.exe
>
> OpenDirectoryProxy : \
> 		Context <null>
> OpenDirectoryProxy : \ Return : Success
>
> GetVolumeInformationProxy
> 		Context <null>
> 		VolumeNameBuffer        DOKAN
> 		FileSystemNameBuffer    DOKAN
> 		VolumeSerialNumber      21083178
> 		FileSystemFlags CaseSensitiveSearch, CasePreservedNames, UnicodeOnDisk, PersistentAcls, SupportsRemoteStorage
> GetVolumeInformationProxy Return : Success
>
> CleanupProxy : \
> 		Context <null>
> CleanupProxy : \ Return : Success
>
> CloseFileProxy : \
> 		Context <null>
> CloseFileProxy : \ Return : Success
>
> CreateFileProxy : \autorun.inf
> 		CreationDisposition     Open
> 		FileAccess      ReadAttributes
> 		FileShare       ReadWrite, Delete
> 		FileOptions     None
> 		FileAttributes  0
> 		Context <null>
> CreateFileProxy : \autorun.inf Return : FileNotFound
>
> CreateFileProxy : \autorun.inf
> 		CreationDisposition     Open
> 		FileAccess      ReadData, ReadExtendedAttributes, ReadAttributes, ReadPermissions, Synchronize
> 		FileShare       ReadWrite, Delete
> 		FileOptions     None
> 		FileAttributes  0
> 		Context <null>
> CreateFileProxy : \autorun.inf Return : FileNotFound
>
> CreateFileProxy : \autorun.inf
> 		CreationDisposition     Open
> 		FileAccess      ReadData, ReadExtendedAttributes, ReadAttributes, ReadPermissions, Synchronize
> 		FileShare       ReadWrite, Delete
> 		FileOptions     None
> 		FileAttributes  0
> 		Context <null>
> CreateFileProxy : \autorun.inf Return : FileNotFound
>
> CreateFileProxy : \
> 		CreationDisposition     Open
> 		FileAccess      ReadAttributes
> 		FileShare       ReadWrite, Delete
> 		FileOptions     None
> 		FileAttributes  0
> 		Context <null>
> CreateFileProxy : \ Return : Success
>
> GetFileInformationProxy : \
> 		Context Object
> 		FileName        \
> 		Attributes      Hidden, System, Directory
> 		CreationTime    08.10.2012 23:11:19
> 		LastAccessTime  04.09.2015 20:53:03
> 		LastWriteTime   04.09.2015 20:53:03
> 		Length  0
> GetFileInformationProxy : \ Return : Success
>
> CleanupProxy : \
> 		Context Object
> CleanupProxy : \ Return : Success
>
> CloseFileProxy : \
> 		Context <null>
> CloseFileProxy : \ Return : Success
>
> CreateFileProxy : \AutoRun.inf
> 		CreationDisposition     Open
> 		FileAccess      ReadAttributes
> 		FileShare       ReadWrite, Delete
> 		FileOptions     None
> 		FileAttributes  0
> 		Context <null>
> CreateFileProxy : \AutoRun.inf Return : FileNotFound
>
> OpenDirectoryProxy : \
> 		Context <null>
> OpenDirectoryProxy : \ Return : Success
>
> GetVolumeInformationProxy
> 		Context <null>
> 		VolumeNameBuffer        DOKAN
> 		FileSystemNameBuffer    DOKAN
> 		VolumeSerialNumber      21083178
> 		FileSystemFlags CaseSensitiveSearch, CasePreservedNames, UnicodeOnDisk, PersistentAcls, SupportsRemoteStorage
> GetVolumeInformationProxy Return : Success
>
> CleanupProxy : \
> 		Context <null>
> CleanupProxy : \ Return : Success
>
> CloseFileProxy : \
> 		Context <null>
> CloseFileProxy : \ Return : Success
>
> CreateFileProxy : \Temp\Source
> 		CreationDisposition     Open
> 		FileAccess      ReadAttributes
> 		FileShare       ReadWrite, Delete
> 		FileOptions     None
> 		FileAttributes  0
> 		Context <null>
> CreateFileProxy : \Temp\Source Return : Success
>
> GetFileInformationProxy : \Temp\Source
> 		Context Object
> 		FileName        \Temp\Source
> 		Attributes      Directory
> 		CreationTime    30.05.2014 21:33:09
> 		LastAccessTime  04.09.2015 22:12:28
> 		LastWriteTime   04.09.2015 22:12:28
> 		Length  0
> GetFileInformationProxy : \Temp\Source Return : Success
>
> CleanupProxy : \Temp\Source
> 		Context Object
> CleanupProxy : \Temp\Source Return : Success
>
> CloseFileProxy : \Temp\Source
>
> CreateFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		CreationDisposition     Open
> 		FileAccess      ReadData, ReadExtendedAttributes, ReadAttributes, ReadPermissions, Synchronize
> 		FileShare       Read
> 		Context <null>
> 		FileOptions     None
> 		FileAttributes  Normal
> 		Context <null>
> CreateFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : FileNotFound
> CloseFileProxy : \Temp\Source Return : Success
>
> CreateFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		CreationDisposition     Open
> 		FileAccess      ReadAttributes
> 		FileShare       ReadWrite, Delete
> 		FileOptions     None
> 		FileAttributes  0
> 		Context <null>
> CreateFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : FileNotFound
>
> CreateFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		CreationDisposition     Create
> 		FileAccess      ReadData, WriteData, AppendData, ReadExtendedAttributes, WriteExtendedAttributes, ReadAttributes, WriteAttributes, Delete, Rea
> dPermissions, ChangePermissions, Synchronize
> 		FileShare       None
> 		FileOptions     None
> 		FileAttributes  Archive
> 		Context <null>
> CreateFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : Success
>
> GetVolumeInformationProxy
> 		Context <null>
> 		VolumeNameBuffer        DOKAN
> 		FileSystemNameBuffer    DOKAN
> 		VolumeSerialNumber      21083178
> 		FileSystemFlags CaseSensitiveSearch, CasePreservedNames, UnicodeOnDisk, PersistentAcls, SupportsRemoteStorage
> GetVolumeInformationProxy Return : Success
>
> GetFileInformationProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		Context FileStream
> 		FileName        \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		Attributes      Archive
> 		CreationTime    04.09.2015 22:12:47
> 		LastAccessTime  04.09.2015 22:12:47
> 		LastWriteTime   04.09.2015 22:12:47
> 		Length  0
> GetFileInformationProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : Success
>
> SetEndOfFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		ByteOffset      3234973
> 		Context FileStream
> SetEndOfFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : Success
>
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		NumberOfBytesToWrite    524288
> 		Offset  0
> 		Context FileStream
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : Success NumberOfBytesWritten : 524288
>
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		NumberOfBytesToWrite    524288
> 		Offset  524288
> 		Context FileStream
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : Success NumberOfBytesWritten : 524288
>
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		NumberOfBytesToWrite    524288
> 		Offset  1048576
> 		Context FileStream
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : Success NumberOfBytesWritten : 524288
>
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		NumberOfBytesToWrite    524288
> 		Offset  1572864
> 		Context FileStream
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : Success NumberOfBytesWritten : 524288
>
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		NumberOfBytesToWrite    524288
> 		Offset  2097152
> 		Context FileStream
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : Success NumberOfBytesWritten : 524288
>
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		NumberOfBytesToWrite    524288
> 		Offset  2621440
> 		Context FileStream
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : Success NumberOfBytesWritten : 524288
>
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		NumberOfBytesToWrite    89245
> 		Offset  3145728
> 		Context FileStream
> WriteFileProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : Success NumberOfBytesWritten : 89245
>
> SetFileAttributesProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		Attributes      0
> 		Context FileStream
> SetFileAttributesProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Return : Success
>
> SetFileTimeProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg
> 		CreateTime
> 		AccessTime
> 		WriteTime       12.08.2015 21:33:48
> 		Context FileStream
> SetFileTimeProxy : \Temp\Source\BouncyCastle.1.7.0.nupkg Throw : The process cannot access the file "D:\Temp\Source\BouncyCastle.1.7.0.nupkg" because it is being used by another process.
>
> Unhandled Exception: System.IO.IOException: The process cannot access the file "D:\Temp\Source\BouncyCastle.1.7.0.nupkg" because it is being used by another process.
>    in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    in System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, Fi
> leOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    in System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
>    in System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
>    in System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
>    in System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
>    in DokanNetMirror.Mirror.SetFileTime(String fileName, Nullable\`1 creationTime, Nullable\`1 lastAccessTime, Nullable\`1 lastWriteTime, DokanFileInfo
> info) in D:\dokan-dotnet\sample\DokanNetMirror\Mirror.cs:Line 296.
>    in DokanNet.DokanOperationProxy.SetFileTimeProxy(String rawFileName, FILETIME& rawCreationTime, FILETIME& rawLastAccessTime, FILETIME& rawLastWrit
> eTime, DokanFileInfo rawFileInfo) in D:\dokan-dotnet\DokanNet\DokanOperationProxy.cs:Line 668.

**Comment by viciousviper** [comment]
... and while trying out the Mirror sample I got a lot more BSODs than I care for.
Could it be possible that the Dokan driver is unable to cope with .NET Exceptions - which is what the `DokanOperationsProxy` produces while in DEBUG mode - and should only be fed `DokanResult.ExceptionInService`?

**Comment by Maxhy** [comment]
I believe this and your recent issue https://github.com/dokan-dev/dokany/issues/53 is related. Reading your explanation I also believe it is related to Debug mode / timeout issue as explained by @marinkobabic on https://github.com/dokan-dev/dokany/issues/46#issuecomment-134758792
Everything working fine on release without debugger?

**Comment by viciousviper** [comment]
Yes, the two issues may very well be related, although I experienced the specific BSOD reported as https://github.com/dokan-dev/dokany/issues/53 while actively debugging in VS 2015 whereas the problems reported in this issue occured while executing `DokanMirror.exe` from the command line. I was using the .NET Debug build in both cases, however.
Next thing I'll try is to modify the Mirror example to return `DokanResult` values instead of directly throwing .NET Exceptions. I have found some situations - particularly Exceptions during calls with `fileName == "\"` to almost certainly result in a BSOD.

**Comment by marinkobabic** [comment]
I'm actually working on custom timeout support. Will make a pull request until monday, hopefully. I have also realized a performance issue if you are working a while with the drive. The multiple threads you started initial get lost and all becomes slower and slower until a hung (last thread terminated). This happens only under special conditions where the system has not enough resources. Will also be fixed. Fighting actually also with a BSOD. As soon as I have fixed it, I will make the pull request.

**Comment by viciousviper** [comment]
@marinkobabic 
Thanks for the update. I appreciate any contributions that improve OS stability and reduce the frequency of BSODs.

@all
Changing the behavior of `DokanOperationsProxy` from throwing .NET Exceptions to returning `DokanResult.ExceptionInService` will definitely take some pressure off the driver. I didn't experience a single BSOD after the change although I'm still using the DEBUG assemblies.

**Comment by voltagex** [comment]
>Changing the behavior of DokanOperationsProxy from throwing .NET Exceptions to returning DokanResult.ExceptionInService will definitely take some pressure off the driver. I didn't experience a single BSOD after the change although I'm still using the DEBUG assemblies.

I wonder if this should be a new issue on its own.

**Comment by Liryna** [comment]
The throw should be remove for stability issue and because anyway it is useless...
It was probably made to help debugging with high sensibility.

This issue is totally linked with what marinkobabic have report and explain https://github.com/dokan-dev/dokany/issues/46#issuecomment-134758792

**Comment by Liryna** [comment]
fixed with https://github.com/dokan-dev/dokan-dotnet/pull/18
