### ISSUE TITLE
Can't unmount a repository running in its own thread

### ISSUE THREAD

**Issue by The-E** [dokan-dev/dokan-dotnet#160]
In my project, I am mounting a Dokany directory in its own thread. When trying to unmount that directory, I am receiving the following error: 
`send global release for C:\Users\fwoltermann\Desktop\ginui-test\Test`
`DokanError: Ioctl failed with code 122`
`Failed to unmount: C:\Users\fwoltermann\Desktop\ginui-test\Test`

What does that mean, and how can I correct this?

**Comment by Liryna** [comment]
Do you provide the correct path for the unmount ?

**Comment by The-E** [comment]
Yes. Both paths are identical, as far as I know; here's the full dokan-related output I have from mounting and then trying to unmount:
```
Dokan: debug mode on
Dokan: use stderr
AllocationUnitSize: 512 SectorSize: 512
device opened
The thread 0x1330 has exited with code 0 (0x0).
CreateMountPoint C:\Users\fwoltermann\Desktop\ginui-test\Test\ -> \??\Volume{d6cc17c5-1711-4085-bce7-964f1e9f5de9}\ success
mounted: C:\Users\fwoltermann\Desktop\ginui-test\Test\ -> \Volume{d6cc17c5-1711-4085-bce7-964f1e9f5de9}
###QueryVolumeInfo -001
'GinClientApp.exe' (CLR v4.0.30319: GinClientApp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GinClientApp.exe' (CLR v4.0.30319: GinClientApp.exe): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
send global release for C:\Users\fwoltermann\Desktop\ginui-test\Test
DokanError: Ioctl failed with code 122
Failed to unmount: C:\Users\fwoltermann\Desktop\ginui-test\Test
```

**Comment by Liryna** [comment]
Does it work by using dokanctl.exe ?
https://github.com/dokan-dev/dokany/blob/ba2109895215e57c8da646d18ecf532413df4263/dokan_control/dokanctl.c#L41

**Comment by The-E** [comment]
No. Dokanctl fails with 
```
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
send global release for 0:
DokanError: Ioctl failed with code 122
Failed to unmount: 0:
Unmount status = 1
```

**Comment by marinkobabic** [comment]
Driver log would be helpful

**Comment by Liryna** [comment]
@The-E I did the test and it work
>mirror.exe /r C:\Users /l C:\Users\liryna\Desktop\test

>.\dokanctl.exe /u C:\Users\liryna\Desktop\test
Driver path: 'C:\WINDOWS\system32\drivers\dokan1.sys'
send global release for C:\Users\liryna\Desktop\test
DeleteMountPoint C:\Users\liryna\Desktop\test\ success
Unmount status = 0

**Comment by Liryna** [comment]
Ok @The-E I see what is probably happening here.
If you mount => `C:\Users\fwoltermann\Desktop\ginui-test\Test\`
You need to unmount `C:\Users\fwoltermann\Desktop\ginui-test\Test`

 `C:\Users\fwoltermann\Desktop\ginui-test\Test\` is "inside" your device but your device is  `C:\Users\fwoltermann\Desktop\ginui-test\Test` to unmount 👍

**Comment by The-E** [comment]
That did not change anything, unfortunately.

```
Dokan: debug mode on
Dokan: use stderr
AllocationUnitSize: 512 SectorSize: 512
device opened
CreateMountPoint C:\Users\fwoltermann\Desktop\ginui-test\Test\ -> \??\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}\ success
mounted: C:\Users\fwoltermann\Desktop\ginui-test\Test\ -> \Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}
###QueryVolumeInfo -001
'GinClientApp.exe' (CLR v4.0.30319: GinClientApp.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'GinClientApp.exe' (CLR v4.0.30319: GinClientApp.exe): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
send global release for C:\Users\fwoltermann\Desktop\ginui-test\Test
DokanError: Ioctl failed with code 122
Failed to unmount: C:\Users\fwoltermann\Desktop\ginui-test\Test
```

**Comment by Liryna** [comment]
Great that it solved your problem ! 👍 
I know it is a little weird but there is a difference between both path :'(
