### ISSUE TITLE
'System.AccessViolationException' occurred in DokanNet.dll

### ISSUE THREAD

**Issue by donid** [dokan-dev/dokan-dotnet#162]
I tried to build the dokan-dotnet solution and its samples, but that failed with "error : Assets file '...\project.assets.json' not found."
So I created a fresh C# console-project and added the DokanNet nuget package 1.1.0.3 and the code from sample\RegistryFS\Program.cs.
When I start the application and it executes rfs.Mount() the exception mentioned in the title immediately occurs with the following message: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."
While the program is waiting in the debugger, the windows explorer shows the newly created drive, but when you click on it, explorer freezes.
The text in the console window is:

Dokan: debug mode on
Dokan: use stderr
AllocationUnitSize: 512 SectorSize: 512
device opened
###QueryVolumeInfo -001
###Create 0000

and after the exception it still adds:

###Create 0001
###Create 0002
###Create 0003
###Create 0004

I am using DokanSetup_redist.exe 1.1.0 on Win10 x64 in version 1703 and 1709.
I have tried to build and run the sample in x86 and x64 configuration, but both show the same problem.

**Comment by Liryna** [comment]
Hi @donid ,

I just released the new version for dokan 1.1.0
https://github.com/dokan-dev/dokan-dotnet/releases/tag/v1.1.1.0
https://www.nuget.org/packages/DokanNet/1.1.1

Can you update and see if it fix your issue ?

**Comment by donid** [comment]
Hi @Liryna ,
updating the nuget package to 1.1.1 fixed the problem.
Thanks for your (and the other contributors) great work!
