### ISSUE TITLE
DokanNet "Unable to load DLL 'Dokan1.dll'

### ISSUE THREAD

**Issue by TonyValenti** [dokan-dev/dokan-dotnet#163]
Hi All,
I'm trying to get started with Dokan using the .NET package and it seems like it might be missing the Dokan1.dll.  What do I need to do to get this DLL?

**Comment by Liryna** [comment]
Hi @TonyValenti ,

The dll is in the dokan folder install. You will need to include it in your installer.
See https://github.com/dokan-dev/dokany/wiki/How-to-package-your-application-with-Dokan
