### ISSUE TITLE
RegistryFS - RFS.Mount

### ISSUE THREAD

**Issue by 3cooper** [dokan-dev/dokan-dotnet#166]
I’m new to C#.  I see in the main method that an instance of RFS is created.  On the next line RFS.Mount() is called. RFS does not have a Mount method.  It implements an interface.  That interface is part of the DokanNet namespace, but the Mount method belongs to the Dokan class.  What is allowing rfs.Mount() to work?  I’ve been searching but can’t find anything.  I also see that Dokan is a public static class and according to documentation, they do not allow inheritance.  Any help would be great.

**Comment by Liryna** [comment]
Hi @3cooper ,

Here is the Mount function that will be called:
https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/Dokan.cs#L86

You can see that there is `this` as param.
See https://stackoverflow.com/questions/846766/use-of-this-keyword-in-formal-parameters-for-static-methods-in-c-sharp

**Comment by 3cooper** [comment]
Thank you.
