### ISSUE TITLE
Share Virtual Drive on Network?

### ISSUE THREAD

**Issue by mnadareski** [dokan-dev/dokan-dotnet#167]
I'll be honest that I'm not sure if I should be posting this question here or on the Dokan main project, but here it goes:

A program that I use daily is built on the Dokan.NET library to create a virtual drive as a local drive. Recently, while using this program through the virtual drive, I attempted to share the drive on my network using the built-in sharing features in Windows 10. Unfortunately, even though Windows 10 reported that it was shared properly, when I went to access the share on another Windows 10 machine on the same network, it said that the "device was not ready". Has anyone else successfully gotten a Dokan.NET/Dokan drive to be shared across a Windows network? If so, how?

For reference, here is a link to the GitHub for the program that I am using (my personal fork of it): [https://github.com/mnadareski/RomVaultX](https://github.com/mnadareski/RomVaultX) with the relevant code being here: [https://github.com/mnadareski/RomVaultX/blob/master/RomVaultX/VDrive.cs](https://github.com/mnadareski/RomVaultX/blob/master/RomVaultX/VDrive.cs) and [https://github.com/mnadareski/RomVaultX/blob/master/RomVaultX/VFile.cs](https://github.com/mnadareski/RomVaultX/blob/master/RomVaultX/VFile.cs)

**Comment by mnadareski** [comment]
It's been the better part of a year and I've updated Dokan and Dokan .NET to the newest versions since then. The bad news is that I'm still running into the issue that I described above with `device not ready` both from other Windows 10 machines and an equivalent error from my Ubuntu MATE laptop.

I did find a somewhat related issue on the main project that seems to say that the issue had been seen before but it was fixed: https://github.com/dokan-dev/dokany/issues/200 and https://github.com/dokan-dev/dokany/pull/373/files respectively. I don't mean to bother, but if anyone else has gotten this to work using Dokan .NET, I would appreciate assistance.

**Comment by Liryna** [comment]
Hi @mnadareski ,

Have you tried to reproduce with the C mirror sample ? (just to be sure it is related to dokan .net)

**Comment by mnadareski** [comment]
I used the same DLLs and the `mirror.exe` sample which resulted in the same issue. I guess I'll open an issue on the main project, then.

**Comment by Liryna** [comment]
See https://github.com/dokan-dev/dokany/issues/763#issuecomment-491625326
