### ISSUE TITLE
rawMaximumComponentLength in GetVolumeInformationProxy

### ISSUE THREAD

**Issue by cdisti** [dokan-dev/dokan-dotnet#169]
Why is rawMaximumComponentLength hard coded to 256 ? Shouldn't be there a possibilty to define a bigger value to support long paths in Windows 10?

**Comment by Liryna** [comment]
Hi @cdisti ,

Yes, it is possible to set it to another value.
See mirror that changes it to the mirrored device: https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L1333

**Comment by cdisti** [comment]
Hi @Liryna,

I understand, but ist it also possible if I am using the .NET Wrapper?
IDokanOperations defines the interface like this:

NtStatus GetVolumeInformation(out string volumeLabel, out FileSystemFeatures features, out string fileSystemName, DokanFileInfo info);

No MaximumComponentLength available?

**Comment by Liryna** [comment]
You are right @cdisti ! There is no reason of this 😞 

Do you think you can make a PR to add the missing parameters with the documentation ?

**Comment by cdisti** [comment]
Just tried to get a VS2017 environment working, but didn't suceeded so far....

**Comment by cdisti** [comment]
Can't get my VS2017 running...
Is there a possibilty for somebody else to improve GetVolumeInformation and add a parameter for MaximumComponentLength ?

**Comment by Liryna** [comment]
Hi @cdisti ,

I made the changes: https://github.com/dokan-dev/dokan-dotnet/commit/c0e439851763a3e42923018bcc67f49b9eea6d9a

**Comment by Liryna** [comment]
Also made the release and published it: https://github.com/dokan-dev/dokan-dotnet/releases/tag/v1.1.1.1

**Comment by cdisti** [comment]
Hi @Liryna ,

that's great! I am gonna make a Windows 10 test as soon as possible!

thanks again!!

**Comment by Liryna** [comment]
@cdisti have you been able to make some test ?
