### ISSUE TITLE
DokanOperationsProxy should not throw .NET Exceptions back to Dokan driver

### ISSUE THREAD

**Issue by viciousviper** [dokan-dev/dokan-dotnet#17]
The behavior of `DokanOperationsProxy` in build mode DEBUG should be changed to return one of the `DokanResult` error values instead of rethrowing the .NET Exception back to the calling Dokan driver.
The present behavior leads to driver instabilities and an inacceptable number of BSODs when debugging Dokan.NET.

Originally suggested by **voltagex** in https://github.com/dokan-dev/dokan-dotnet/issues/16#issuecomment-137952740

**Comment by viciousviper** [comment]
I'd be happy to submit a PR later today.
Would it be acceptable to aim for VS 2015 (`nameof(...)`, string formatting via `$"..."`) or do we need to preserve compatibility with earlier VS versions?

**Comment by Liryna** [comment]
It would be nice to stay in vs 2013. We will switch all projects to vs 2015 when dokany will use the WDK 10.

I will :heart: to see your PR !

**Comment by viciousviper** [comment]
And how could that happen with the *DokanNet.Tests* project being C#6? :grin:
Anyway, I'm glad you let me get away with a bit of innovation for the Tests project but I totally understand that the main Dokan.NET project has to remain accessible to people without the latest VS.
BTW: Did I mention that I'm doing quite allright with VS 2015 Community Edition? :eyes:

**Comment by Liryna** [comment]
I am not against VS 2015. I also use it :smiley: with DokanNet.
I just wait to test dokany with wdk 10 and migrate the project when dokany get stable.

**Comment by marinkobabic** [comment]
@Liryna 
.Net wrapper should be redisigned, without any breaking changes:
* Create own internal wrapper which talks to the driver
* The new wrapper talks only directly to the driver
* The new wrapper will catch all exceptions of the "customers" wrapper and translate them to NTSTATUS code
* Add optional ILogger interface, so that the wrapper logs everything. If an instance of ILogger is not passed in, the NullLogger will do nothing.

Actually I did not analyze all the details :grin:

This way, we have:
* no differences between throwing exceptions and returning the ErrorResult. 
* callbacks never fail
* Applications never crashes because of callback issues
* The is no need to log the operations, because dokan provides all the logs

In .Net I would generally not suggest to throw exceptions, because those make the whole process slow. If an exception happens, I would return INVALID_PARAMETER to the driver, except in case of Close and CleanUp. The developer should always return ErrorResult, except an Exception happens and we do not provide an ErrorResult for this case.

ErrorResult should anyway represent the NTSTATUS :stuck_out_tongue_winking_eye:

**Comment by Liryna** [comment]
@marinkobabic As I understand, it would be like rewriting the dokan.dll but in C# ?
This could be an idea but it will ask some work.

With @viciousviper contribution, Throws are now catch and replace by DokanResult.ExceptionInService.

DokanResult will be replace by NTSTATUS in the next dokany release I promise marinkobabic :smile: ! (And remove keep alive flag)

**Comment by marinkobabic** [comment]
The implementation of  @viciousviper looks very good. Well done!!

Possible improvements:
* Catch different exceptions like FileNotFoundException, AccessDenied etc and translate to specific NTSTATUS or actually DokanResult code.
* Create ILogger interface and implement as example the NullLogger, TraceLogger and DebugViewLogger which can be passed in.

**Comment by viciousviper** [comment]
@marinkobabic 
Thanks for the praise - this is what keeps us all coding in our spare time :grinning: 

I have so far limited my modifications to Dokan.NET because I didn't want to interfere with Liryna's or Maxhys intentions for to project. So before I dig deeper into things I'd like to know your ideas on the direction you want to take wih the .NET wrapper.

Personally, I like the idea of reporting back specific `DokanResult` codes depending on which Exception type was caught. I don't know, however, if this will make any difference to the Dokan driver.

Regarding a more elaborate Tracing/Logging scheme, we could certainly profit by joining the presently existing tracing directives - I know of two separate sets, one in Dokan.Net and one in the Dokan.Net Tests project - in one place and replacing the current `printf()`-style tracing with a dedicated logging framework. https://github.com/NLog/NLog comes to mind, which would allow us to configure logging/tracing behavior in an external config file instead of requiring a recompile.
I would certainly want to keep the very compact tracing output format produced by the test project. The more verbose variant from Dokan.Net would then make up the //DebugViewLogger// format.

Any thoughts on this?

**Comment by marinkobabic** [comment]
@viciousviper 
You have a good programing style :-)

**Return value:**
Only in some specific cases the Dokan driver checks if the return value is -1 and then it has a logic to handle it. Generally the full flexibility is there, if the return value is of type NTSTATUS or returns the appropriate codes. To throw an exception is never a good idea, but if it happens we can report it properly to the driver and an appropriate message will be displayed to the end user. Here an example why it's important to return correct code to the driver: If user wants to delete a folder, it makes a big difference if you return SUCCESS or DIRECTORY_NOT_EMPTY code. The operating system will behave total different.

**Logging:**
The .Net developers don't want to know too much about the C or C++ stuff happening in the background. They feel fine when using .Net Framework. The expectation is to have a clean interface. If dokan provides an interface ILogger with methods Info, Debug, Exception, Error, Warning the consumer can take whatever logging framework they want. Dokan will provide by default the TraceLogger, DebugViewLogger, ConsoleLogger and NullLogger and all those classes just inherit from ILogger dokan logging interface. If somebody wants to use the NLog or log4net they can just implement the interface and pass the instance in, it takes few minutes. This way Dokan has no dependencies to one of this Frameworks.
