### ISSUE TITLE
Limit File Size

### ISSUE THREAD

**Issue by ralmeida96** [dokan-dev/dokan-dotnet#170]
I'm trying to make a virtual file system using the C# version of Dokan.
What I want to do right now is to set the max limit of a file for my filesystem, for example, the filesystem can't have a file with more than 2GB.

At the moment I'm doing this on Operation SetEndOfFile but I can only give DiskFull error and I want to return something like NTStatus.FileTooLarge, but when I do that the filesystem simply ignore that return.

Is there any options to do what I want?

**Comment by Liryna** [comment]
Hi @ralmeida96 ,

Have you tried the ntstatus `STATUS_INSUFFICIENT_RESOURCES` ?

**Comment by ralmeida96** [comment]
That should be done at SetEndOfFile operation right? 
Because it seems that does nothing, after that return the file start copying. 
![untitled](https://user-images.githubusercontent.com/12168649/39040062-8b08971e-447e-11e8-8999-d0513abe89f8.png)

**Comment by Liryna** [comment]
Hi @ralmeida96 ,

By looking at the fastfat code source, seems like STATUS_DISK_FULL can be returned here
https://github.com/Microsoft/Windows-driver-samples/blob/master/filesys/fastfat/fileinfo.c#L4436

**Comment by ralmeida96** [comment]
Yeah, but I don't want to return NtStatus.Diskfull but instead I want to return NtStatus.FileTooLarge.
Is that possible?

**Comment by Liryna** [comment]
@ralmeida96 by looking at the documentation and code sample from microsoft it does not seems to be another error for it. We can do nothing if the kernel windows does not react on FileTooLarge

**Comment by ralmeida96** [comment]
@Liryna thats what I thought.
Thanks anyway

**Comment by Liryna** [comment]
Hi @ralmeida96 ,

Thank you for the feedback 👍  Will sure help someone with the same needs later !
