### ISSUE TITLE
DokanNet.dll tries to load dokan.dll, but the appropriate bindings are in dokan1.dll

### ISSUE THREAD

**Issue by kyanha** [dokan-dev/dokan-dotnet#172]
All of the native methods that DokanNet.dll binds to are located in dokan1.dll, but the p/invoke bindings specify dokan.dll.  I had to copy dokan1.dll from the Dokany installation directory to dokan.dll in my application directory to get it to work.

Version: Dokan.Net v1.0.8
Dokany version: v1.0.5

**Comment by Liryna** [comment]
@kyanha You are using an old version of the dokannet. The name has been changed in a long time.
