### ISSUE TITLE
Dokan Mount always throws exception

### ISSUE THREAD

**Issue by TimJRodgers** [dokan-dev/dokan-dotnet#185]
The recent change to report unknown errors from the Mount routine means it will throw an exception if NativeMethods.DokanMain returns DOKAN_SUCCESS. There needs to be a case statement to ignore this code and not throw an exception.

Thanks!

Tim.

**Comment by Liryna** [comment]
Hi @TimJRodgers ,

Oh ! Sorry ! 😞 
Thank you for the report! I made the change....https://github.com/dokan-dev/dokan-dotnet/commit/6707dfd8e59ea57f73a23e9095ffc0399c4c118f

**Comment by TimJRodgers** [comment]
Hi @Liryna, 

Great, thank you! :)
