### ISSUE TITLE
Getting error - The directory name is invalid.

### ISSUE THREAD

**Issue by imraushan** [dokan-dev/dokan-dotnet#186]
Hi,
Created a file system where i am able to copy/paste to from the virtual drive. But when i try to open a word document directly from the virtual drive getting windows alert that says - 

The directory name is invalid

![image](https://user-images.githubusercontent.com/8289103/41098805-45276744-6a7a-11e8-8b8f-e851ecff9f89.png)

Looks like the driver is not getting recognized here - I am on windows 10 64 bit system. Working with Dokan dotnet. 
Please share how to go about it - if similar issue is observed by anyone.

Thanks,

**Comment by Liryna** [comment]
@imraushan Hi!

Seems like your implementation is return the file path as a directory instead of a file. Be sure to correctly set the variable isdirectory.

**Comment by imraushan** [comment]
Hi @Liryna - Thanks a lot!
Yes - at one point in the FileInformation I was not adding Attribute for marking it as directory or file. After adding it works.
