### ISSUE TITLE
Getting ProcessInfo of process invoking file operations

### ISSUE THREAD

**Issue by imraushan** [dokan-dev/dokan-dotnet#187]
Hi, 

I have created a memory drive and now I have a requirement where the drive should not be accessible from any other process apart from the process that launched it.
The launching process (parent process) I can get but when I copy file or do any other operation - I can't determine the process that is making these calls.
If these calls are coming from other source process then that has to be rejected for security reasons.
Using CurrentSession option I am able to restrict access to current user session - but not able to find a way to control at process level.

Is there a way for achieving this?

Thanks.

**Comment by Liryna** [comment]
Hi @imraushan ,

You can use the processId to know from who the request comes from
https://github.com/dokan-dev/dokan-dotnet/blob/95a630c692bcc559b6fe75aa9e9d76a443beb478/DokanNet/DokanFileInfo.cs#L85

**Comment by imraushan** [comment]
Thanks @Liryna. It was super quick! 
Tested - It gives information I required about the process invoking file operations.
