### ISSUE TITLE
Mounting on a folder should keep that folder handler open

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokan-dotnet#189]
When mounting a dokan drive on a folder anyone can rename or delete that folder rendering the drive unusable.

I'm not sure if this should be a dokany issue
...

**Comment by TrabacchinLuigi** [comment]
We first tried to work around with permissions, but seems like it's not the right approach, also it needs administrator privileges...

**Comment by TrabacchinLuigi** [comment]
this looks like a dokany issue: 
https://github.com/dokan-dev/dokany/issues/700

**Comment by Liryna** [comment]
Hi @TrabacchinLuigi 

Yes this seems to be more like a dokan issue.
I close there to continue on the ticket you linked.
