### ISSUE TITLE
New Release Date

### ISSUE THREAD

**Issue by shlatchz** [dokan-dev/dokan-dotnet#19]
Can you please publish a new release in Git & Nuget?
The last one is from May.

Thanks!

**Comment by Liryna** [comment]
@shlatchz Dokan-net master branch is linked with current dokany master branch that is also currently not release. 

We wait to release dokany before Dokan-net.

**Comment by shlatchz** [comment]
Oh, okay :+1: 
Any ETA?

**Comment by Liryna** [comment]
Pre-release: https://github.com/dokan-dev/dokany/releases/tag/v0.8.0
This is a pre-release, so probably unstable - We would like some feedback about it !
