### ISSUE TITLE
How to set a fake 'FileSystemSecurity' object and use the .NET Wrapper for file system entry that doesn't really exists?

### ISSUE THREAD

**Issue by HristoKolev** [dokan-dev/dokan-dotnet#192]
Hello, 

My colleague and I are trying to implement a file system that is entirely backed by a relational database.

The issue that we are encountering is that when the `IDokanOperations.GetFileSecurity` method gets called we don't know what to assign to the `security` `out variable`. It is defined as `FileSystemSecurity` which is an `abstract` class and all of its constructors are `internal` and we cant extend it...

What we can do is to get the `FileSystemSecurity` of a regular file or directory from disk and assign that... but we want to create our own and set whatever permissions we see fit. 

How can we do that? Are we doing anything wrong?

**Comment by Ravenheart** [comment]
I can confirm that we have the same problem as @HristoKolev

**Comment by Liryna** [comment]
Hi @HristoKolev @Ravenheart ,

As far as I know, create your own permission will be required to use win32 api function like `ConvertStringSecurityDescriptorToSecurityDescriptor`

When `IDokanOperations.GetFileSecurity` is not implemented, dokan library is calling `DefaultGetFileSecurity` that create his own permission (even if it is C, it should be possible to rewrite it for c#)
https://github.com/dokan-dev/dokany/blob/83be68351c70d916e58bdae8e3424e521fe07b04/dokan/security.c#L29

**Comment by HristoKolev** [comment]
The thing is that even if we generate our own permissions, we have no way of assigning them to the FileSystemSecurity object since it is `abstract` and all of it's constructors are `internal` so there is no way for you to get your hands on an actual object except if you decide to get it from a real file.

Is our case outside of what's supported by Dokan and the .NET wrapper?

**Comment by Liryna** [comment]
If GetFileSecurity return `STATUS_NOT_IMPLEMENTED`, `DefaultGetFileSecurity` will be called see
https://github.com/dokan-dev/dokany/blob/83be68351c70d916e58bdae8e3424e521fe07b04/dokan/security.c#L156
This point was clearly missing from the documentation 👍 https://github.com/dokan-dev/dokan-dotnet/commit/8bee5fb5ca64dd90677c163aa75ea51bb3a41f57

I agree `FileSystemSecurity` creation is limited by the framework.
afaik it is the only object we can use to build the binary security descriptor that we need
https://github.com/dokan-dev/dokan-dotnet/blob/85165d5da69f51b9b6ae0df5e2ce35d8e0a1bb51/DokanNet/DokanOperationProxy.cs#L1099
I would in this case get this object from a known file that has the most near wanted rights and adapt it.
