### ISSUE TITLE
EncoderFallbackException

### ISSUE THREAD

**Issue by IvanKonov** [dokan-dev/dokan-dotnet#195]
Sometimes there is such an exception. Cyrillic encoding (Ru).

System.Text.EncoderFallbackException
   в System.Text.EncoderExceptionFallbackBuffer.Fallback(Char, Int32)
   в System.Text.EncoderFallbackBuffer.InternalFallback(Char, Char* ByRef)
   в System.Text.UTF8Encoding.GetBytes(Char*, Int32, Byte*, Int32, System.Text.EncoderNLS)
   в System.Text.EncoderNLS.GetBytes(Char[], Int32, Int32, Byte[], Int32, Boolean)
   в System.IO.StreamWriter.Flush(Boolean, Boolean)
   в System.IO.StreamWriter.Write(Char[], Int32, Int32)
   в System.IO.TextWriter+SyncTextWriter.WriteLine(System.String)
   в System.Console.WriteLine(System.String)
   в DokanNet.Logging.ConsoleLogger.WriteToConsole(System.ConsoleColor, System.String, System.Object[])
   в DokanNet.DokanOperationProxy.FindFilesWithPatternProxy(System.String, System.String, IntPtr, DokanNet.DokanFileInfo)

**Comment by Liryna** [comment]
Hi @IvanKonov ,

Yes this can be done here: https://github.com/dokan-dev/dokan-dotnet/blob/85165d5da69f51b9b6ae0df5e2ce35d8e0a1bb51/sample/DokanNetMirror/Mirror.cs#L28

Different logger are available here: https://github.com/dokan-dev/dokan-dotnet/tree/master/DokanNet/Logging You are probably looking at Nullloger
