### ISSUE TITLE
Is the file/stream size known on CreateFile?

### ISSUE THREAD

**Issue by jchristn** [dokan-dev/dokan-dotnet#198]
Hi, is the file/stream size/length known at the time CreateFile is entered?  If so where can this property be accessed, specifically for FileMode.Create, OpenOrCreate, etc?

**Comment by Liryna** [comment]
@jchristn Hi!

We cannot know at the time of CreateFile this inform unfortunately.

**Comment by jchristn** [comment]
Got it, thank you.  Do most/all applications reliably close the file?  Trying to figure out how/when I can go back to the object and measure its length to store in my own metadata layer.  Thanks!

**Comment by Liryna** [comment]
@jchristn You could keep if write happened on the handle / file and get the length on the file in close. Be aware that write can happen after close (windows feature) so maybe write should store the file length only if the write was outside the original length :D

**Comment by jchristn** [comment]
Semantically should I consider the file length to be zero on CreateFile, and then update after each WriteFile if offset + buffer.Length > previous size?

**Comment by Liryna** [comment]
@jchristn If it is a new file or truncated yes, otherwise if already existing file, will need to get the current length.

**Comment by jchristn** [comment]
ok thank you!
