### ISSUE TITLE
Error with DokanNetMirror Sample

### ISSUE THREAD

**Issue by landrix** [dokan-dev/dokan-dotnet#2]
any known problems with VirtualBox? The DokanNetMirror sample can't find dokan.dll

-<OSVersionInformation>
<WindowsNTVersion>6.1</WindowsNTVersion>
<Build>7601 Service Pack 1</Build>
<Product>(0x30): Windows 7 Professional</Product>
<Edition>Professional</Edition>
<BuildString>7601.18839.amd64fre.win7sp1_gdr.150427-0707</BuildString>
<Revision>1130</Revision>
<Flavor>Multiprocessor Free</Flavor>
<Architecture>X64</Architecture>
<LCID>1031</LCID>
</OSVersionInformation>

![23-06-_2015_13-46-34](https://cloud.githubusercontent.com/assets/3299479/8305391/df9ca6ce-19ae-11e5-8c44-51f6e1d0dd5f.jpg)

**Comment by Liryna** [comment]
Is everything well installed ?
https://github.com/dokan-dev/dokany/wiki/Installation#manual-installation

I do not think VirtualBox is the problem.
DokanNetMirror just cannot found dokan.dll

**Comment by landrix** [comment]
i have installed the latest release from here. on my real windows 8.1 it works fine, but not in virtualbox Win7 32bit or 64bit. 

I'll look at them tomorrow again

**Comment by landrix** [comment]
ok, m( , Visual C++ redistribuables wasn't installed
