### ISSUE TITLE
Doubt - No operations, just mount the drive

### ISSUE THREAD

**Issue by fds13** [dokan-dev/dokan-dotnet#20]
Hello, good afternoon!

It's possible just mount the drive without any operation feature (Create, Delete, etc)?

For example, if I try copy a file to mounted drive, nothing happens.

My idea is use another application to manage this operations, not the Windows Explorer.

I was understandable?

Thank you!

**Comment by Liryna** [comment]
Hi,

If I understood well:
You can create a FS that check the ProcessIdof every request (https://github.com/dokan-dev/dokan-dotnet/blob/194ddbb866188c6df1201c7aadb18b5c3027c315/DokanNet/DokanFileInfo.cs#L53) 
Accept them if it come from your application or to refuse if it come from another.

I already made it and it work :smiley: 
(But as I remember, there is a minmum of request to accept from explorer, to not make him unstable)

**Comment by fds13** [comment]
Hi Liryna! Thanks again, for your attention. Appreciate that. 

I questioned this because of the problem of copy large files yet (remember?).

I'm trying to do like the software at the bottom did. When you copy something to the virtual drive, the software handles this, not the Windows Explorer. If I can do this, a workaround is possible for me.

Software:
http://dw.cbsi.com/redir?ttag=restart_download_click&ptid=3001&pagetype=product_pdl&astid=2&edid=3&tag=link&siteid=4&destUrl=&onid=18500&oid=3001-18500_4-10907413&rsid=cbsidownloadcomsite&sl=en&sc=us&topicguid=internet%2Fonline-storage-data-backup&topicbrcrm=&pid=13072867&mfgid=6312728&merid=6312728&ctype=dm&cval=SPIGOTWIN&devicetype=desktop&pguid=1f7095a946fee6d24dc1abe1&viewguid=YEUGGZUJgfwS5TQr0JEltO5y8e73SIeUnHKV&destUrl=http%3A%2F%2Fsoftware-files-a.cnet.com%2Fs%2Fsoftware%2F13%2F07%2F28%2F67%2FGladinetSetup_4.0.1027_x64.msi%3Ftoken%3D1443159297_4e1a64016978b6f82ed62314645be62f%26fileName%3DGladinetSetup_4.0.1027_x64.msi

**Comment by Liryna** [comment]
Oh ok I see, unfortunately I cannot help you on this :(

**Comment by fds13** [comment]
Ok Liryna. Thank for your time. :+1:

**Comment by Liryna** [comment]
@fds13 , can I close this ticket ?

**Comment by fds13** [comment]
Yes.

Thank you again.
