### ISSUE TITLE
How to change count of options in context menu of file?

### ISSUE THREAD

**Issue by kovtunenkoa17** [dokan-dev/dokan-dotnet#200]
Hi All! I'm using dokan to write virtual disk in scope of c# project. And for now I'm interesting in possibility
to change context menu for file after right click on it. For example leave only "copy" and  "paste". Also is it possible to do using only dokan-dotnet part?
Thank you in advance!

**Comment by Liryna** [comment]
Hi @kovtunenkoa17 ,

Context menu are not managed by Dokan. It is a Windows feature for all the devices.
https://docs.microsoft.com/en-us/windows/desktop/shell/context-menu-handlers

I am not sure it is possible to remove the generic option menu. If you or someone could come up with an idea, it would be great to share it. Seems like a couple of people are interested in this.

**Comment by kovtunenkoa17** [comment]
Thank you @Liryna for quick answer!
