### ISSUE TITLE
Q: moving a directory to its own child

### ISSUE THREAD

**Issue by samokhodkin** [dokan-dev/dokan-dotnet#201]
Hi, guys
When a user tries to move a directory to its own child directory, what should be an NtStatus?

When I try this in explorer on a normal filesystem, it shows a message box with correct indication of what happened, so there should be a dedicated NtStatus. But I cannot find it judging by constant names.

Thanks

**Comment by Liryna** [comment]
@samokhodkin Hi,

**Comment by marinkobabic** [comment]
Use filemon when working with ntfs and you will get all the details

**Comment by samokhodkin** [comment]
Hi,
don't see anything useful in procmon log:
[procmon.txt](https://github.com/dokan-dev/dokan-dotnet/files/2362400/procmon.txt)

**Comment by marinkobabic** [comment]
I think in ProcMon you can turn on advanced mode. It may be
STATUS_OBJECT_NAME_COLLISION
according to your log

**Comment by Liryna** [comment]
Hi @samokhodkin ,

Have you been able to test the @marinkobabic answer ?

**Comment by samokhodkin** [comment]
Hi @Liryna <https://github.com/Liryna>,

Not, I'm now reworking my application, cannot run it yet. Will try it quite
soon

**Comment by samokhodkin** [comment]
Checked @marinkobabic's idea, yes, STATUS_OBJECT_NAME_COLLISION did the trick. Thanks.
