### ISSUE TITLE
Can't handle source path of file when drag&drop to my virtual disk

### ISSUE THREAD

**Issue by kovtunenkoa17** [dokan-dev/dokan-dotnet#203]
hi All!
I'm trying to paste file from local disk C: to my virtual dokan disk and can't get correct source path of this file. One that I can see  - fileName=" \\SomeVirtualFolder\Example.txt" in CreateFile method.
Let me know please if you have some ideas!)

**Comment by Liryna** [comment]
@kovtunenkoa17 Hi!

You will not see the source file but only the destination on your driver folder. The device has no knowledge from where explorer takes information. Juste that explorer is asking to create a new file on your drive and later to write in it.
