### ISSUE TITLE
CreateFile is not working.

### ISSUE THREAD

**Issue by softpot9** [dokan-dev/dokan-dotnet#205]
Hi Dokan Team !

Please check the screenshots. I can see error message when create a new file in explorer.

![image](https://user-images.githubusercontent.com/26469987/45770491-330f2600-bc4b-11e8-9028-9075ea3ba56e.png)
![image](https://user-images.githubusercontent.com/26469987/45770524-47532300-bc4b-11e8-943f-909ae3cfbf98.png)

If you possible, please let me know about this reason.

Thanks

**Comment by Liryna** [comment]
@softpot9 Hi,

Is it your app or the mirror? If it is the mirror, can you provide the logs? If it is your app, be sure to return the correct information like the mirror.
