### ISSUE TITLE
AccessViolationException under high stress

### ISSUE THREAD

**Issue by pp111** [dokan-dev/dokan-dotnet#207]
When my application is writing large files it crashes with an AccessViolationException or some other internal .NET exception indicating that something went wrong with the memory handling.

Trying to narrow the issue down I found that when the system opened repeatedly a high stressed file to read its attributes was causing the issue. The open/close is successful but the memory is corrupted.

So checking the CreateFile code in the Mirror example when the system wants to read file attributes there is the following code (line 163):

`info.Context = new object();
 // must set it to someting if you return DokanError.Success`

An unused object is assigned to the context. In my code I did the same. However if I change it to

`info.Context = null`

then the memory issue goes away and everything works ok. 

So my questions are why is this unused object assigned to the context, how can it cause a memory corruption and if setting it to null can have other bad consequences.

**Comment by Liryna** [comment]
Hi @pp111 ,

Normally there is no need to set a Context. Do you have the callstack of the AccessViolationException  ?

**Comment by pp111** [comment]
Usually it crashes in 
mscorlib.dll!System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback

no more call stack is shown. My code is doing a lot of I/O operations using the threadpool with a several GB file. It crashes if I read the file attributes while working with the file. My code is only managed code.

Sometimes instead of an AccessViolationException  the exception is FatalExecutionEngineError. Somehow the stack seems to be damaged.

I can confirm that setting the context to null instead of new object() in CreateFile when reading attributes fixes the issue.

**Comment by pp111** [comment]
Hi @Liryna finally I discovered the cause of the heap corruption.

My application was setting the info.Context to null at the end of  some read calls (the memory mapped reads). Setting the Context to null instead of new object() on CreateFile did the trick but that was not the cause.

So it seems to me that setting the context should only be done in CreateFile (or in CloseFile and Cleanup if we are setting it to null). Otherwise the heap can become corrupted. 

Does it make sense to you?

**Comment by Liryna** [comment]
Hi @pp111 ,

Yes the Context should only be done in CreateFile since it can be used by different thread right after leaving the CreateFile.

Thank you for find out and sharing it ! 👍

**Comment by pp111** [comment]
Hi @Liryna , I am still getting a few of memory corruption reports from some users. Is it really safe to set the Context to null in both CloseFile and Cleanup ?

**Comment by Liryna** [comment]
Hi @pp111 ,

Context is really just a memory space for the user FS. Dokan does not touch it 😢 Are you sure to safely (lock) us it ?
