### ISSUE TITLE
ReadFile offset income not successively

### ISSUE THREAD

**Issue by kovtunenkoa17** [dokan-dev/dokan-dotnet#208]
Hi All! During implementing local drive  from cloud (google cloud) I faced with
problem in ReadFile(). When I try to get file from network I create Stream (httpClient.GetStream)
and write bytes from stream to buffer in ReadFile(), but I observed problem that offset
comes not successively realatively to file. If I have file with 800000 length first call will be with offset = 0 and buffer size = 200000, but second will be offset = 600000 and buffer size = 200000. Main Problem that I can't set Position of Stream or set Seek(). Maybe you can advise what to do to have "synchronous" read from file? How to force Explorer read file buffer by buffer, not jumping to the end?
Thank you in advance, Dokan is greate api!

**Comment by Liryna** [comment]
Hi @kovtunenkoa17 ,

Unfortunately, there is not way to ask explorer to read only from offset 0 or "synchronous". The only possibility that I see would be to cache the file at the first request to be able to answer the next one.

**Comment by kovtunenkoa17** [comment]
Hi @Liryna, thanks for answer!

In my case files will more than 2Gb and caching will be very slow from net. I tried to play with BufferToSmall return value, but nothing.
