### ISSUE TITLE
Buffer size 576 not a power of 2?

### ISSUE THREAD

**Issue by Rinkwraith** [dokan-dev/dokan-dotnet#210]
Hiya,

I was hoping someone could offer a pointer in the right direction here. Got a problem when I try to open a file on my DokanNet-mounted device. Before the execution hits my own ReadFile() method, the following error is generated:

ReadFileProxy: \25000097.100
Buffer Length 576
Offset 0
Context {\<null\>, False, False, False, False, #10832, True, False}
Buffer size 576 not a power of 2 or too large, returning unpooled buffer.
-1 (size 576) outside pool range, discarding buffer.
ReadFileProxy : \25000097.100 Return : ObjectNameNotFound ReadLength : 0

Listing and browsing through directories, getting file info etc. is working great. But, obviously, this results in the file read failing.

I've no idea where this buffer size comes from, why it's happening, or what to do about it. Would be grateful for any help.

Cheers.

**Comment by Liryna** [comment]
Hi @Rinkwraith ,

The logs or not errors, they come from RentBuffer & ReturnBuffer.
https://github.com/dokan-dev/dokan-dotnet/blob/fa556dfc3631eb8feed374322f4285cf17194f88/DokanNet/DokanOperationProxy.cs#L402-L411
https://github.com/dokan-dev/dokan-dotnet/blob/fa556dfc3631eb8feed374322f4285cf17194f88/DokanNet/BufferPool.cs#L78-L152

You should not have a corrupted buffer, especially that ObjectNameNotFound is not returned by dokan-net. Could it be in your code ?

**Comment by Rinkwraith** [comment]
Well, I don't think it's anywhere in ReadFile(), as the debugger etc. shows that the call to ReadFile() never even happens.

I really don't have anything interesting going on in this class - very little happens - so am not sure. Can post the whole thing in a bit.  SetAllocationSize() got anything to with this? Also, I didn't think to try setting breakpoints on LockFile() to see if that's at all related.

**Comment by Rinkwraith** [comment]
Aahhh sh*t. Visual Studio's debugging is having some issue with ReadFile(). Heh.

Changed the Not Found error message inside that function, and it gets changed in the RealFileProxy() trace. So I guess that a) the stream read error isn't related to the weird buffer message, and b) can't rely on the debugging tool. :-)

**Comment by Rinkwraith** [comment]
Yeah, I'm dumb.

It legit cannot find the file when it runs through ReadFile(). I just thrown off track.

Thanks for the advice Liryna!

**Comment by Liryna** [comment]
Pleasure @Rinkwraith 👍
