### ISSUE TITLE
Question about file locking

### ISSUE THREAD

**Issue by jchristn** [dokan-dev/dokan-dotnet#211]
Not an issue, but I didn't know who else to ask.  When it comes to LockFile() and UnlockFile(), do you ever encounter applications that will lock a particular range, but then unlock only a subset of that given range?  Or are most applications well-behaved and lock a specific range, and then unlock that exact range?

**Comment by Liryna** [comment]
@jchristn Mob r

**Comment by jchristn** [comment]
Thanks @Liryna - this makes my life sooo much easier!  Cheers
