### ISSUE TITLE
Error "The directory name is invalid"

### ISSUE THREAD

**Issue by jchristn** [dokan-dev/dokan-dotnet#213]
Hi all, I checked the closed cases and found this issue, and already implemented this solution (https://github.com/dokan-dev/dokan-dotnet/issues/186) for CreateFile and GetFileInformation (setting info.IsDirectory appropriately).  

I have created a Sqlite database abstraction holding file and directory metadata.  My code is integrated with my own object storage (https://github.com/kvpbase/storage-server) and is translating file system requests into object storage requests.  I can successfully mount the volume and open it with explorer.  I can right-click, create a new file (text document), and the document appears, allowing me to enter the name (I'm using test.txt).  The document appears in the folder.

When I double-click the file, I get "The directory name is invalid."  

I checked the data I'm holding/managing in Sqlite and the metadata for both the directory and the file are in tact and accurate.  I checked the kvpbase instance and I can see where calls were made correctly to verify whether or not the object exists and also when it was created.  It was also successfully subsequently retrieved.  

I hate to be a burden, and I know it's a lot to ask, but is there anyone that would be willing to look through the Dokan debug output I have in this gist?  https://gist.github.com/jchristn/0e647905058337df6cab47446f6fdfde

The exact steps captured in the gist were as below.  There were no other extraneous operations other than those performed naturally by explorer:
1) start my application
2) open explorer
3) navigate explorer to my drive (Z:)
4) right-click and create new text document
5) type the name of the document (test.txt)
6) press enter (the file appears in explorer)
7) double-click the file
8) receive the error

Sorry to ask so much, hope it's not a huge burden.  I can't figure out what I'm doing wrong.

Thanks, Joel

**Comment by marinkobabic** [comment]
It may be related to

Return : ObjectNameNotFound


In your log

**Comment by jchristn** [comment]
Thanks @marinkobabic.  The first instance I see is on line 1701.  This is a CreateFile with FileMode.Open to initially create the file.  I was under the impression (per https://docs.microsoft.com/en-us/dotnet/api/system.io.filemode?view=netframework-4.7.2) that FileMode.Open should return a file not found if the file does not exist.  Is this not correct?

This happens again subsequently on line 2534 (again FileMode.Open) when I set the name to ```test.txt```.

For FileMode.Open, should I be creating the file if it does not exist?  

Thanks!
Joel

**Comment by marinkobabic** [comment]
If the file does not exist, then the return value is fine. Initially this
file name was there and then renamed. This should be the normal behaviour.

Please can you do the same using mirror and check if we have the same log?

**Comment by jchristn** [comment]
I tested mirror and know it works.

**Comment by marinkobabic** [comment]
Can you see in the mirror log the same return codes like in your log?

**Comment by jchristn** [comment]
Ah, my apologies, I see what you are asking.  I will test it right now.

**Comment by marinkobabic** [comment]
Please can you test the following. Create a file and don't give it the
test.txt name. Keep it like proposed by Windows. Try then to open the file.
Please create a fresh log file.

**Comment by jchristn** [comment]
I can confirm that mirror will also return ObjectNameNotFound:
```
02/06/2019 12:56:25 - [Mirror] CreateFile('\Test\New Text Document.txt', {<null>, False, False, False, False, #1116, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [None], [0]) -> ObjectNameNotFound
02/06/2019 12:56:25 - [DokanNet] CreateFileProxy : \Test\New Text Document.txt Return : ObjectNameNotFound
```
and
```
02/06/2019 12:56:28 - [Mirror] CreateFile('\Test\test.txt', {<null>, False, False, False, False, #1116, False, False}, [WriteData, Synchronize], [ReadWrite], [Open], [None], [0]) -> ObjectNameNotFound
02/06/2019 12:56:28 - [DokanNet] CreateFileProxy : \Test\test.txt Return : ObjectNameNotFound
```

**Comment by Liryna** [comment]
@jchristn Hi,

The error seems to show the file is a directory for him. Be sure to have the flag IsDirectory correctly always set and that getfileinformation gives proper data.

**Comment by jchristn** [comment]
Hi @Liryna I have set ```info.IsDirectory = true``` for all directory operations and ```info.IsDirectory = false``` for all file operations in both CreateFile and GetFileInformation.  Are there other methods where I should set this?  Thanks!

**Comment by jchristn** [comment]
@marinkobabic testing that now, thanks - one sec.

**Comment by jchristn** [comment]
@marinkobabic Just tested and even without renaming, I still get 'The directory name is invalid.'  Log file here: https://gist.github.com/jchristn/3bb073daf80a0a9645653eafb95d75e5

**Comment by marinkobabic** [comment]
Please can you run the process monitor so that we can see what is there
going on. https://download.sysinternals.com/files/ProcessMonitor.zip

**Comment by jchristn** [comment]
Yes, I have it open.  Is this what you need?  https://gist.github.com/jchristn/9ef310e5be95969005edb5b470756b68

Thanks!

**Comment by marinkobabic** [comment]
Now you can set the filter to path starts with and then your drive letter.
The process monitor should display all the file activities on your drive.
Please switch the view mode to expert.

**Comment by marinkobabic** [comment]
https://youtu.be/pjKNx41Ubxw

**Comment by jchristn** [comment]
Got it - saved the logfile here: https://www.dropbox.com/s/cnhkrufyghof92c/Logfile.PML?dl=0

**Comment by jchristn** [comment]
Hi @marinkobabic I just realized I had not filtered the output, so I deleted it.  New link here: https://www.dropbox.com/s/ljf4zo9esek6vaw/Logfile.PML?dl=0  - I had to start the app, get the PID from Task manager, and then filter based on the PID.  Thanks!

**Comment by jchristn** [comment]
I can see where file system calls are continually being called to retrieve file information:
```
Debug [Z: 1GB] GetFileInformation('\New Text Document.txt', {System.Object, False, False, False, False, #1116, False, False}) -> Success
02/06/2019 17:50:06 - [DokanNet]        FileName        Z:\New Text Document.txt
02/06/2019 17:50:06 - [DokanNet]        Attributes      Archive, Normal
02/06/2019 17:50:06 - [DokanNet]        CreationTime    2/6/2019 5:50:06 PM
02/06/2019 17:50:06 - [DokanNet]        LastAccessTime  2/6/2019 5:50:06 PM
02/06/2019 17:50:07 - [DokanNet]        LastWriteTime   2/6/2019 5:50:06 PM
02/06/2019 17:50:07 - [DokanNet]        Length  0
02/06/2019 17:50:07 - [DokanNet] GetFileInformationProxy : \New Text Document.txt Return : Success
```

And that it succeeds in opening the file:
```
02/06/2019 17:50:09 - [DokanNet] CreateFileProxy : \New Text Document.txt
02/06/2019 17:50:09 - [DokanNet]        CreationDisposition     Open
02/06/2019 17:50:09 - [DokanNet]        FileAccess      ReadAttributes
02/06/2019 17:50:09 - [DokanNet]        FileShare       ReadWrite, Delete
02/06/2019 17:50:09 - [DokanNet]        FileOptions     None
02/06/2019 17:50:09 - [DokanNet]        FileAttributes  0
02/06/2019 17:50:09 - [DokanNet]        Context {<null>, False, False, False, False, #1116, False, False}
Debug [Z: 1GB] CreateFile('\New Text Document.txt', {System.Object, False, False, False, False, #1116, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [None], [0]) -> Success
```

Closing also succeeds:
```
02/06/2019 17:50:07 - [DokanNet] CloseFileProxy : \New Text Document.txt
02/06/2019 17:50:07 - [DokanNet]        CreationDisposition     Open
02/06/2019 17:50:07 - [DokanNet]        FileAccess      Synchronize
02/06/2019 17:50:07 - [DokanNet]        FileShare       ReadWrite
02/06/2019 17:50:07 - [DokanNet]        FileOptions     None
02/06/2019 17:50:07 - [DokanNet]        FileAttributes  0
02/06/2019 17:50:07 - [DokanNet]        Context {<null>, False, True, False, False, #1116, False, False}
Debug [Z: 1GB] CreateFile('\', {<null>, False, True, False, False, #1116, False, False}, [Synchronize], [ReadWrite], [Open], [None], [0]) -> Success
```

Could the issue be that I've implemented a custom Stream class (that implements the Stream interfaces) and should be implementing FileStream instead?  I've tested the class I've created thoroughly and don't think it itself has any issues, but I don't know if there's a compatibility problem with Dokan or something.

By the way, I found the source of the ObjectNameNotFound.  It was exactly as you both suggested, my intent to set info.IsDirectory to false in all places was thwarted by a copy/paste issue and in one condition it was returning true.

I am still however getting the "Directory name is invalid" error.  Thanks for your help.

**Comment by marinkobabic** [comment]
With the driver log we should normally  have all the needed information.

**Comment by marinkobabic** [comment]
What I could imagine is that you are having not allowed chars in your
filename. One of them would be the slash. Maybe you are returning somewhere
the full path instead of just the name of the file. Please check this as
well.

**Comment by jchristn** [comment]
Thanks @marinkobabic - so using a standard stream instead of a filestream for info.Context is fine?

**Comment by jchristn** [comment]
Regarding having invalid characters, where would that occur?  I'm saving the full path and filename (including the slashes) in my metadata layer, and returning this information as is on GetFileInformation.  Thanks for your help.

**Comment by marinkobabic** [comment]
Dokan does not care about the context. It's your pointer you have to take
care off.

A driver log would be in any case helpful. So we can check if the status is
returned by user library or if the os doing this.

Please check mirror if the returned path is just a file name, relative path
or full path.

At some point Windows is requesting you to provide a list of files. Check
this method as well.

We will find the source of your problem for sure.

**Comment by jchristn** [comment]
Hi @marinkobabic could you clarify when you say "returned path" are you referring to the response (file name, relative path, or full path) to GetFileInformation or some other method, and which one should be returned (file name, relative path, or full path)?

Also when you say driver log is this the output from Process Monitor (the link I supplied above) or do I need to amend it in some way?  

Really appreciate your persistence and willingness to help.

**Comment by marinkobabic** [comment]
Hi Joel

I'm talking about exactly this methods you mentioned. Maybe somewhere is
just the file name expected and you are returning the full path. This would
cause exactly this issue.


When I'm talking about the driver log then I mean the Dokany sys driver. In
wiki it's described how you can turn the logging on.

You have your. Net application which represents the user land. Your app is
communicating with the Dokany filesystem driver. And the Dokany filesystem
driver is talking to the os.

Hope this helps.

Thanks
Marinko

**Comment by jchristn** [comment]
Thank you @marinkobabic - I can confirm that GetFileInformation will always return the *full* path and never a filename alone or relative path.

I'll look into the Wiki and get logging turned on, re-run the exact test, and save it to a Gist.  I should be able to do it in the next two hours (locked down on conference calls right now).  Really appreciate the help.

**Comment by jchristn** [comment]
Also changed my code to return just filenames to GetFileInformation, behavior stayed the same.

In terms of debugging Dokan and the wiki article, is this what you're referring to?  https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan 

If so, do you have a link to the debug version I can download?

**Comment by marinkobabic** [comment]
Dokan Driver
<https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#enable-logs>Enable
logs

Debug output are only enable in debug build. You will need to install the
debug version of dokan.

After we will need to enable DbgPrint Output into Windows and dokan sys.
<https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#windows>Windows

As explain on OSROnline <https://www.osronline.com/article.cfm?article=295>,
you will need to create the key Debug Print Filter (if it already does not
exist) and the DWORD IHVDRIVER = 0x0d.

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session
Manager\Debug Print Filter]
"IHVDRIVER"=dword:0000000d

Dokan sys

You need to run this command at launch of Dokan (or Windows boot).

dokanctl.exe /d 9
 <https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs>Get logs

Download DbgView
<https://technet.microsoft.com/en-us/library/bb896647.aspx>. Enable
kernel output with CTRL + K.

You should now be able to see DokanFS output!

**Comment by jchristn** [comment]
Where do I download the debug version of Dokan?  Thanks
