### ISSUE TITLE
Outside pool range, discarding buffer

### ISSUE THREAD

**Issue by jchristn** [dokan-dev/dokan-dotnet#214]
Hi all,

Any idea why I might be getting this message?

```
[Z: 1GB] WriteFile('\somefile.txt', {ProjectX.Classes.StreamProxy.KvpbaseStream, False, False, False, False, #24200, True, False}, out 19, 0) -> Success
02/08/2019 14:55:08 - [DokanNet] -1 (size 19) outside pool range, discarding buffer.
02/08/2019 14:55:08 - [DokanNet] WriteFileProxy : \somefile.txt Return : Success NumberOfBytesWritten : 19
```

**Comment by jchristn** [comment]
I think I see.  I was passing a buffer of size 19.  Looks like I'll need to amend my backend to work around this.
```
/// <summary>
        /// Returns a previously rented buffer to the buffer pool.
        /// If the buffer size is not an exact power of 2, the buffer is ignored.
        /// </summary>
```

**Comment by jchristn** [comment]
Agh - reopening because it doesn't look like I have control over the issue of the size of the buffer being passed into WriteFile.  Any help appreciated.  Thanks!

**Comment by Liryna** [comment]
@jchristn Hi,
This is not an issue. Yes you have no hands on this. The message is more like a warning debug. We should not print it in normal usage.

**Comment by jchristn** [comment]
Thanks @Liryna - the issue I have is that the data I was writing to the file doesn't get written as a result.

**Comment by jchristn** [comment]
I even tried writing a number of bytes that was a power of 2 to the file:
```
02/09/2019 09:51:14 - [DokanNet] WriteFileProxy : \asdf.txt
02/09/2019 09:51:14 - [DokanNet]        NumberOfBytesToWrite    4
02/09/2019 09:51:14 - [DokanNet]        Offset  0
02/09/2019 09:51:14 - [DokanNet]        Context {ProjectX.Classes.StreamProxy.KvpbaseStream, False, False, False, False, #33552, True, False}
02/09/2019 09:51:14 - [DokanNet] Pool 2 empty, creating new buffer.
[Z: 1GB] WriteFile('\asdf.txt', {ProjectX.Classes.StreamProxy.KvpbaseStream, False, False, False, False, #33552, True, False}, out 4, 0) -> Success
```

**Comment by Liryna** [comment]
Do you think it is an dokan issue ? Could you make a sample to reproduce it (mirror sample changed)

**Comment by jchristn** [comment]
Nope, it wasn't.  I guess I'm the king of fire drills for you and the team.  I worked through this and several other issues - would love to give you a demo of what I've built if you would be interested!  Thanks!

**Comment by Liryna** [comment]
We can add your project on the main dokan page website if you would like and feel that ready for the public 👍
