### ISSUE TITLE
Seems like Info.Context still leaks gc handles

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokan-dotnet#216]
After updating to last version we found out that info.context was becoming some random variables (sometimes an exception, sometimes null, sometimes some other values)
our implementation was not setting info.context to null during cleanup, so i've read the changelog i've found out about issue #178 and it's fix if i've understood the handle is released after CloseFile
But a question rose in my head: if CloseFile isn't always called shouldn't be the GC.Handle be released during Cleanup ?
Also i was wondering: shouldn't the file life cycle be different ? won't be better if cleanup was called after CloseFile ? And always, even after CreateFile returns something different from NtStatus.Success ?

For instance we use a dictionary to keep track of the context, so we pass back to dokan-net only the dictionary key (seem to work quite faster like that) and if we set if to null we can't relate the CloseFile call to his predecessor calls... this seems somehow wrong...
I say somehow because we can just close the stream and handles during cleanup, and forget about CloseFile, but then what's the purpose of close file ?

I'll try to change the implementation to set the context to null during cleanup (now we substitute it when a new CreateFile is called) and provide feedback

**Comment by Liryna** [comment]
@TrabacchinLuigi Hi,

Context life time is not handle by dokan since it can be whatever the user FS needs.

Cleanup and close logic are Microsoft FS driver design. Cleanup is made to clean the handle and other resources but close is made to finish any context on the query.

If context need to be cleaned in close at very last or it will leak.

**Comment by TrabacchinLuigi** [comment]
Ok I think I've understood: so dokany can't decide what will be called next, is the kernel, based on ntstatus that decides, right?
Also closefile is my last chance to clean the context...

Is there any chances that closefile won't be called after cleanup?

**Comment by Liryna** [comment]
@TrabacchinLuigi No closefile will always be called for sure.

**Comment by TrabacchinLuigi** [comment]
i have the strong sensation that the problem reside in us changing the context...
Is it legit to change Info.Context once set ?
we used to always set info context to keep track of the subsequent calls and group them, but during create file if the creation was not successful we discarded the previous value to replace it with another one, this seems to destroy memory ...
We can easily avoid doing that, but just to keep you guys informed.

**Comment by Liryna** [comment]
Should not an issue to do so. Context is really not touch by dokan. It is fully in the fs user hands.

**Comment by TrabacchinLuigi** [comment]
what i think is happening:
we create something to use as context, we assign it to info.context, then we return `NtStatus.ObjectNameNotFound` so Cleanup isn't called nor CloseFile.
maybe dokan-net won't keep a reference to that Info.Context in this case nor our code, but dokany does, if the GC (which i belive knows nothing of what the kernel does) collects that object, on next call dokany will pass back the pointer, but now at that address there is something else (hence the strange values we found).
It is just a guess if you want i can try to reproduce it with the mirror example, with less changes possible.

**Comment by Liryna** [comment]
If you could try this on the mirror C sample would be awesome 👍

**Comment by TrabacchinLuigi** [comment]
Wait, but the c sample lack of a Garbage collector... or not ? i'm not that good in unmanaged code ...

**Comment by Liryna** [comment]
@TrabacchinLuigi https://github.com/dokan-dev/dokan-dotnet/blob/6707dfd8e59ea57f73a23e9095ffc0399c4c118f/DokanNet/Native/DOKAN_OPERATIONS.cs#L23

https://github.com/dokan-dev/dokan-dotnet/blob/fa556dfc3631eb8feed374322f4285cf17194f88/DokanNet/DokanOperationProxy.cs#L33-L41

DokanFileInfo that hold the context is simply marshal, so if there is a leak it should be in the C library

**Comment by TrabacchinLuigi** [comment]
I think the big issue are with managed code because of the GarbageCollector moving memory around (I'm not really aware of what the gc does but i've read it compacts memory too), and the Clr throwing uncatchable exceptions if managed code try to read something outside the heap memory range... 
I will try do to it as soon as i can

**Comment by TrabacchinLuigi** [comment]
I'm having a hard time reproducing this, i guess we can close it for now...
