### ISSUE TITLE
Appear as a local disk

### ISSUE THREAD

**Issue by jchristn** [dokan-dev/dokan-dotnet#217]
Hi all, is there a way to have the disk appear in explorer the same way the C: drive does for example?  I've tried DokanOptions.FixedDrive and DokanOptions.RemovableDrive and these both appear differently.  Reason I ask is I want to run CrystalDiskInfo or similar benchmarking tool against my implementation and these don't support disks as represented by Dokan (at least not the way I have it, perhaps).  Thanks!

**Comment by Liryna** [comment]
@jchristn Have you tried to use the mount manager option?

**Comment by jchristn** [comment]
I have not!  Do you have a link for more information (or example)?  Thanks!

**Comment by Liryna** [comment]
@jchristn Not on computer right now :'( sorry but there should be some documentation linked to the enum and more on Microsoft website.

**Comment by jchristn** [comment]
Hi @Liryna I'm not finding this.  Any help would be appreciated - even a starting point.  Thanks!

**Comment by Liryna** [comment]
https://github.com/dokan-dev/dokan-dotnet/blob/6707dfd8e59ea57f73a23e9095ffc0399c4c118f/DokanNet/DokanOptions.cs#L37

**Comment by jchristn** [comment]
Oh, sorry I didn't think you were referring to DokanOptions.  I will try this!

**Comment by jchristn** [comment]
Weird, still not accessible in CrystalDiskInfo (not seen as a local drive).  What tools do you and the team use to benchmark performance for Dokan-based volumes?  Maybe I just need to align with those tools.

**Comment by Liryna** [comment]
CrystalDiskInfo is probably more looking at a block disk device and not a fs files benchmark.

https://dokan-dev.github.io/dokany-doc/html/ `Testing a File System`

**Comment by jchristn** [comment]
Thanks!  I'll report back if I have any issues.  Appreciate your help.
