### ISSUE TITLE
Gathering directory properties

### ISSUE THREAD

**Issue by jchristn** [dokan-dev/dokan-dotnet#218]
Hi all, which Dokan methods are invoked when a user right-clicks on a directory and goes to properties?  I'm trying to figure out why the number of files and total size of files is not showing up in explorer.  Thanks!

**Comment by Liryna** [comment]
@jchristn GetFileInformations should be called to get such data.

Have you looked at dokan-net and dokany documentation on how the api is working?

**Comment by jchristn** [comment]
Thanks @Liryna I will check it out!
