### ISSUE TITLE
Support for file previous versions

### ISSUE THREAD

**Issue by jchristn** [dokan-dev/dokan-dotnet#219]
Hi all, does Dokan support filesystem previous versions?  If so is there a reference on which Dokan methods are involved or how it works?  Thanks!

**Comment by Liryna** [comment]
@jchristn Hi! 

Dokan library 1.x.x will always be compatible with 1.x.x kernel driver. All broken changes will be made in another major version if that is your question.

**Comment by jchristn** [comment]
Hi @Liryna !  I was referring to the "previous versions" tab in the file properties such as from restore points or backups etc.  Have a great rest of your day!

**Comment by Liryna** [comment]
That's shadow copy feature you are talking about. I think we are far from supporting it.
Would first need to look at if possible to ask windows to enable it on dokan device. If I remember shadow copy is not enabled by default on devices.

**Comment by jchristn** [comment]
Ok - thanks @Liryna !
