### ISSUE TITLE
Error opening PDF documents in mirror example

### ISSUE THREAD

**Issue by MSchmid71** [dokan-dev/dokan-dotnet#227]
Opening PDF documents with Acrobat Reader works via the File Open dialog of Acrobat Reader, but not via a double click in Windows Explorer.

**Comment by Liryna** [comment]
Hi @MSchmid71 ,

Which version of Acrobat Reader are you using ? Have you tried with the C Mirror ?

**Comment by MSchmid71** [comment]
Hi @Liryna,
i use Acrobat  Reader Version: 19.10.20091.315611 on Windows 10 Pro x64. I tested it with the mirror example on drive C on two different systems.
The same problem occurs with a solution that I am currently programming.

**Comment by Liryna** [comment]
@MSchmid71 might be too late but have you tried the mount manager option at mount time ?

**Comment by Liryna** [comment]
Let me know when you have been able to do the test and I will reopen the ticket.
