### ISSUE TITLE
How to identify end of WriteFile when size is not present?

### ISSUE THREAD

**Issue by lasitha-petthawadu** [dokan-dev/dokan-dotnet#228]
I have developed a S3 mounted drive using dokan-dotnet and this allows to mount a S3 bucket as a virtual drive. I have run into an issue where a web application streams uploaded data to my virtual drive and I need to upload it to S3.

Since S3 doesn't support offset writing (https://stackoverflow.com/questions/42675291/aws-s3-write-at-offset), I first sync the file to a temporary location in the local disk and want to upload to S3 once the file is fully saved to the local disk.

But the problem is that I cannot identify when all WriteFile operations have completed. I have tried to access DokanFileInfo to access the length of the file to verify if all the bytes have been written so that I could trigger an upload, but I do not get a size as well.

I also checked if Cleanup or CloseFile is been called but none of them are triggered in this instance as well.

Appreciate if someone could help in identifying a way of finding when a write ends when a size is not defined.

**Comment by Liryna** [comment]
@lasitha-petthawadu Hi!

You are right. There is no way to know if the current write is the last one.

Cleanup and specially close are the right events to conclude all write happened.
In your case you say they are never called?

**Comment by lasitha-petthawadu** [comment]
@Liryna Yes in this instance cleanup and close aren't triggered. Readfile triggers cleanup and close properly, is there a way for me to debug why cleanup or close might not be called?

Any other alternative ways of handling it?

**Comment by Liryna** [comment]
@lasitha-petthawadu The only reason for them to not be called is if the process doing the call did not close the handle and is still alive

**Comment by lasitha-petthawadu** [comment]
@Liryna Thanks for the quick reply! Is there a timeout configuration at the dokany driver level which could force close opened file handlers?

I'm aware of a read timeout which gives out "insufficient resources available" if a read prolongs beyond the timeout period. Is there something similar for write?

**Comment by Liryna** [comment]
the timeout is for all query. It is not only for read so you would also get a timeout if write do not finish in time.
