### ISSUE TITLE
what's the diffrent of open file by user and by system?

### ISSUE THREAD

**Issue by MatriQ** [dokan-dev/dokan-dotnet#229]
I'm developing a network disc client. the files will not auto download to local disk,files download through 'download' item in contextmenu。it will show a messagebox tip user to download content if file isn't downloaded. I wanted to check it when invoke CreateFile method,but I don't know what's the diffrent of open file by user and by system(some type of file will try preview by system,it will invoke CreateFile)?

**Comment by Liryna** [comment]
Hi @MatriQ ,

You can use the processId to differencie explorer / third apps.

**Comment by MatriQ** [comment]
thank you very match @Liryna ，it's work.

**Comment by MatriQ** [comment]
thank you very match @Liryna ，it's work.

but a thread app is already open when dokan-net invoke CreateFile. I need check the operation before thrid app startup.May be I shoud hook some system api , or some other ways.can you help me?

**Comment by Liryna** [comment]
CreateFile is really the first step for us. You will probably need to look for a process watcher for your need.

**Comment by MatriQ** [comment]
Ok,thank you again
