### ISSUE TITLE
Mounted drive as a shared drive

### ISSUE THREAD

**Issue by smcal** [dokan-dev/dokan-dotnet#235]
Is there a way to make a mounted drive a shared drive?  What I'm trying to do is create a 'Dokan' folder and share it across the network.  I tried using ManagementClass to label the root mounted drive and various folders that I included but can't seem to get them to be shared.  Thanks.

**Comment by Liryna** [comment]
Hi @smcal 

Please see https://github.com/dokan-dev/dokany/issues/763#issuecomment-491625326
