### ISSUE TITLE
Clarification of license requested: is it still MIT?

### ISSUE THREAD

**Issue by kyanha** [dokan-dev/dokan-dotnet#237]
Hi, I'm asking for a clarification of the license for Dokany (and dokan-dotnet): is it still MIT?  Hiroki Asakawa hasn't worked on Dokan since 0.6.0, which was released 12 years ago now; since then, a large amount of work (enough to claim copyright protection) has been done and released by the dokany team.

This situation is not unlike the OpenSSL maintainers taking over maintenance of SSLeay and releasing multiple major versions and API changes.  OpenSSL changed their license to refer to their later maintainers, but still maintained the SSLeay license in their license documents as required by the original license they built from.

I'm asking this because I'm looking to change the `<PackageLicenseUrl>` and `<PackageIconUrl>` tags in dokannet.csproj to comply with https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg, and to get the deprecation warnings for those tags out of the build.  Yes, I can simply refer to the existing files in the repository, but I think it might be appropriate to (re?)visit the licensing issue, after over a decade of maintaining only the legacy of the original dokan package.  Of course, I could also be completely off-base.  But the point of raising the issue is to verify that the intention hasn't changed.

Thanks!

**Comment by Liryna** [comment]
Hi @kyanha ,

That's a really good point you bring here.
I haven't really thought about it. I personally would say, we should stay with the MIT license.
Well, we should at least add our copyright in the license 😄 
Do you have in mind another license that would be more appropriate for dokan-dotnet ?

**Comment by kyanha** [comment]
I actually really like the MIT license for dokan-dotnet.  (And for dokany, and all the other associated projects.)  Yes, I think you should add your copyright claim (for the years that you've been doing this) to the license.mit.txt file, since I can't really see any harm to putting newer text above Asakawa-san's notice.  (After all, you're not changing the block of text that is his notice, you're just prepending to it.)

But I'm not a lawyer, and I don't know how easy it is to do that kind of thing in France.

**Comment by Liryna** [comment]
Not a lawyer too :D but I think nothing wrong to add your copyright to the same file
https://github.com/dokan-dev/dokan-dotnet/commit/529544b9a8402b6999206d01003ba3d906020f4c

Thank you @kyanha for sharing your idea👍
