### ISSUE TITLE
Need to make appveyor build succeed for new docs to be pushed

### ISSUE THREAD

**Issue by kyanha** [dokan-dev/dokan-dotnet#249]
The last successful appveyor build was October 1, 2018.  We need updated docs pushed for the 1.3.0 release.  Can we get the tests working properly, or at least comment out the tests that fail, so that the doc auto-push can work?

**Comment by Liryna** [comment]
Wow that's true 😞 Just disabled the two test failing https://github.com/dokan-dev/dokan-dotnet/commit/ebb82b972df4c40d3a209e0b8449425359acf364
until https://github.com/dokan-dev/dokany/issues/822 fix is released

We are green https://ci.appveyor.com/project/Liryna/dokan-dotnet/builds/28576873 😎

**Comment by Liryna** [comment]
https://github.com/dokan-dev/dokan-dotnet/commit/f67ad7a58cdbf70c92865161ddaccce83bce3bf1
