### ISSUE TITLE
AccessViolationException when mounting file system using Windows autostart

### ISSUE THREAD

**Issue by 0x4a616e** [dokan-dev/dokan-dotnet#251]
On a "few" machines, I get an `AccessViolationException` with description `The process was terminated due to an unhandled exception` when trying to mount the file system via the Windows autostart using a Run key. Restarting the app manually afterwards always works es expected.
Unfortunately, the exception cannot be caught so it always crashes the app and I can only see the exception in the Windows event log.

![image](https://user-images.githubusercontent.com/5487722/74131712-42e32d80-4be5-11ea-966b-a396275ff3ee.png)

Also, the following details are logged for the exception:

<img width="741" alt="image" src="https://user-images.githubusercontent.com/5487722/74132334-a1f57200-4be6-11ea-83b4-e9976ad63e11.png">

Is there anything I could do to avoid this or to provide more details on the issue?

**Comment by Liryna** [comment]
Hi @0x4a616e ,

Thank you for the report, have you been able to reproduce the issue using the native mirror with autostart ?
Just to be sure if we do face a dotnet or native issue.

**Comment by 0x4a616e** [comment]
Unfortunately, this time I don't have access to an effected machine at all...

**Comment by Liryna** [comment]
@0x4a616e can this be closed or would you will have the ability to access a machine ?

**Comment by 0x4a616e** [comment]
Unfortunately I don’t see any way to get access to one of the affected machines. I understand that this makes it extremely difficult to find the cause, so please go ahead and close this!

**Comment by Liryna** [comment]
Thank you, please do not hesitate if you face again and we will look at it together.
