### ISSUE TITLE
Create file error(0x800FFFF)

### ISSUE THREAD

**Issue by haDDah** [dokan-dev/dokan-dotnet#254]
Hi,
OS: Windows 10 Enterprice(version 1803, OS build 17134.1365) //cracked :p

Steps: 1) Mount disk
           2) Right-click mouse ->  New -> Text Document

After these steps Windows throw error:

![image](https://user-images.githubusercontent.com/22501914/76712364-3b093280-6729-11ea-9e4c-59e857b67ec3.png)
If press "Try Again" -> file will create, but error reappears.
If press "Cancel" -> file will create and all OK.

Need to fix these error..

In debug mode no errors from debugger, only this error from Windows.

If i copy file(ctrl+v) in directory, no any errors.

If i create file by cmd, file creates, but...
![image](https://user-images.githubusercontent.com/22501914/76712371-49efe500-6729-11ea-92ee-38cfeaae4b6b.png)
Log from Dokan, when error appear in attachments(1,2,3,4).

Code taken from here: https://github.com/HackcatDev/XakepFS/tree/master/XakepFS

Help me please <3

**ATTACHMENTS**

![1](https://user-images.githubusercontent.com/22501914/76712379-583e0100-6729-11ea-8f4c-ab190e5e392c.png)
![2](https://user-images.githubusercontent.com/22501914/76712380-596f2e00-6729-11ea-9093-9c233ce0363e.png)
![3](https://user-images.githubusercontent.com/22501914/76712381-596f2e00-6729-11ea-94cf-cd4af3d4dca2.png)
![4](https://user-images.githubusercontent.com/22501914/76712382-5a07c480-6729-11ea-88f1-0f4f65942a7a.png)

Regards haD.

**Comment by Liryna** [comment]
Hi @haDDah ,

The code might not be updated or compatible with the dokan version you have installed.
https://github.com/HackcatDev/XakepFS/blob/master/XakepFS/packages.config#L3
Dokan 1.2.1 is compatible with it. Try to update the nuget package and install dokan version if that's not the case already.

**Comment by haDDah** [comment]
Hi @Liryna ,
Thanks you for answer. 
I updated version, as you said, but the problem did not resolve.
Sorry to take so long.

**Comment by Liryna** [comment]
Have you tried to directly contact the project owner?
That's not a dokan issue but more how it is used / version.

**Comment by haDDah** [comment]
Hi @Liryna ,
Thanks you for answer.
No, I didn’t contact him. The whole project was in bugs that I fixed gradually and only this remained.
I’ll try to find the error or rewrite the function from scratch.
Maybe you have an example how to use the file creation function correctly?

**Comment by Liryna** [comment]
There is a mirror sample in this repository that might help you. Otherwise you have the documentation in dokany that might contains some hints that are good to know.
