### ISSUE TITLE
Can't assign a drive letter or mount point

### ISSUE THREAD

**Issue by ordinaryorange** [dokan-dev/dokan-dotnet#255]
Trying to mount as an NTFS folder but I'm getting the error per the title.
If I use a drive letter e.g. M the mount occurs without error.
Tried the mount.exe sample application that comes with Dokan, but it also throw error "Cant assign a drive letter" when a directory is specified.
Running on Windows 10.0.018362

Ideas ?

**Comment by Liryna** [comment]
Hi @ordinaryorange ,

How does your mount path / options looks like ?

**Comment by ordinaryorange** [comment]
Tests with mount.exe from Dokan installer ("mount" directory confirmed as not present on machine before execution)
```
mirror /r c:\users /l c:\mount
mirror /r c:\users\ /l c:\mount
mirror /r c:\users /l c:\mount\
mirror /r c:\users\ /l c:\mount\
```

All the above fail with the error _"Cant assign a drive letter"_

This works
`mirror /r c:\users /l x:`

Also tried with the [DokanNetMirror sample](https://github.com/dokan-dev/dokan-dotnet/blob/34a117f0556aae9c3695d5a9053a381b28c5f46c/sample/DokanNetMirror/Program.cs#L23), changing only lines 23 and 27
The stdout produces 

> Using unsafe methods: False
> 04/07/2020 10:57:16 - [DokanNet] GetVolumeInformationProxy:
> 04/07/2020 10:57:16 - [DokanNet]        Context {<null>, False, False, False, False, #4, False, False}
> 04/07/2020 10:57:16 - [Mirror] GetVolumeInformation('<null>', {<null>, False, False, False, False, #4, False, False}, out DOKAN, out CaseSensitiveSearch, CasePreservedNames, UnicodeOnDisk, PersistentAcls, SupportsRemoteStorage, out NTFS) -> Success
> 04/07/2020 10:57:16 - [DokanNet]        VolumeNameBuffer        DOKAN
> 04/07/2020 10:57:16 - [DokanNet]        FileSystemNameBuffer    NTFS
> 04/07/2020 10:57:17 - [DokanNet]        VolumeSerialNumber      4094363
> 04/07/2020 10:57:17 - [DokanNet]        FileSystemFlags CaseSensitiveSearch, CasePreservedNames, UnicodeOnDisk, PersistentAcls, SupportsRemoteStorage
> 04/07/2020 10:57:17 - [DokanNet]        MaximumComponentLength  256
> 04/07/2020 10:57:17 - [DokanNet] GetVolumeInformationProxy Return : Success
> Error: Can't assign a drive letter or mount point

**Comment by Liryna** [comment]
@ordinaryorange Let's try to make it work with the C mirror first. Can you provide the output if mirror.exe /r C:\users /l C:\mount /d /s?

Be sure the mount folder already exist and the user running the command has access to it.

**Comment by ordinaryorange** [comment]
Hi @Liryna, problem solved. Issue was me.

I had made the assumption that the mount path should **not** exist, and that Dokan would create it. But your last comment indicates that the mount folder **should** exist.
When I created the c:\mount folder and then ran Dokan, it all worked perfectly.

Thank you for you assistance.
