### ISSUE TITLE
SharingViolation exception in CreateFile (it is called in many times in one behavior)

### ISSUE THREAD

**Issue by NavigatorXia** [dokan-dev/dokan-dotnet#258]
Today I got an interest problem. (In Dokan-Dotnet Sample Mirror.cs)

As we know, if a new file need to be created, in CreateFile, the following code will create it.
       info.Context = new FileStream(fileName, mode, 
                        readAccess ? System.IO.FileAccess.Read : System.IO.FileAccess.ReadWrite, 
                        share, options);
Parameters: readAccess is false, mode is Create.
When I set break point to track it, I found CreateFile will enter many times with same parameter.
The new FileStream hasn't finish its work(no file created in disk), but the next CreateFile is called.
And which will leads SharingViolation exception, and I noticed they shared one same IDokanFileInfo.ProcessID.

**Comment by Liryna** [comment]
Hi!

This is a normal behavior. An application can call CreateFile multiple times with the same parameters. Each of the calls will have a different context and FileStream.

**Comment by NavigatorXia** [comment]
It has a trick behavior in my two machine, one has SharingViolation problem, the other has not.

the other one may lead error like: "The process cannot access the file 'xxx.xxx' because it is being used by another process"
but no SharingViolation exception

**Comment by Liryna** [comment]
@NavigatorXia This depends on how to app display the error. You can use procmon to track the process activity and see exactly what happens

**Comment by NavigatorXia** [comment]
One question: how to use these data member in IDokanFileInfo, such as NoCache，PagingIo，ProcessId、 SynchronousIo，WriteToEndOfFile

I notice the Mirror doesn't use them in read/wirte operation.

**Comment by Liryna** [comment]
@NavigatorXia You can find the document website on the Readme or the Readme of dokany that is more detailed on the work flow.
