### ISSUE TITLE
Copy File From Dokan To NTFS

### ISSUE THREAD

**Issue by shlatchz** [dokan-dev/dokan-dotnet#26]
Hello,
I tried copying a file from the dokan drive to my NTFS drive and got a weird error:

![oooooo](https://cloud.githubusercontent.com/assets/4594463/10294521/8beaa8c0-6bc3-11e5-844b-8334f4fd56e7.png)

This error appears only when I try to do this action on Win8. On Win7 it works great.
This action worked on Win8 in previous versions (0.7.4 and earlier).

Also, I'll add that reading the file works perfectly. Just copying it to a different disk doesn't work, which is weird, because it still calls the same functions (CreateFile, GetFileInformation, ReadFile, Cleanup, Close).

Oh, and sometimes this action crashes the program...

Thanks!

**Comment by Liryna** [comment]
Hi @shlatchz ,

Did you test with the mirror ?
I have just copy a exe of 30mo from NTFS to Dokan Volume on my Windows 10 without issue.

I do not have Win8 unfortunatly.
Could you provide some logs ? (dokany & mirror)

**Comment by shlatchz** [comment]
NVM, I found the reason for this problem.
It is because I return NtStatus.Error for SetFileSecurity & GetFileSecurity.
Only in Win8, it doesn't let you copy the file to a physical disk...

Thanks! :)
