### ISSUE TITLE
Mirror.cs incorrectly sets attributes on open

### ISSUE THREAD

**Issue by dangibson** [dokan-dev/dokan-dotnet#260]
In the mirror sample, around line 200 it has this:

```
if (mode == FileMode.CreateNew || mode == FileMode.Create) //Files are always created as Archive
                        attributes |= FileAttributes.Archive;
                    File.SetAttributes(filePath, attributes);
```

If you open an existing file with the readonly and/or archive bit set (eg open in Notepad), then attributes is Normal at the start of CreateFile and this line basically removes all attributes, clearing the readonly / archive flag on the file.

**Comment by Liryna** [comment]
@dangibson Yes, this is normal. When the file is created or overwrite, the attributes are removed if a previous one was existing.
See https://github.com/dokan-dev/dokany/blob/a55396bb96f6570838738fb3373ea452a161db33/samples/dokan_memfs/memfs_operations.cpp#L124 memfs sample that is handling more cases with some comments.

When you open a file with notepad as you describe, this lines are not called since it is an open and not a create.

If you want more informations there is a Microsoft doc page on setattributes that describes  this behavior.

**Comment by dangibson** [comment]
It opens the file with access=GenericRead. This means readWriteAttributes is false (line 135) and so does get to the File.SetAttributes call on line 201.
I think maybe this section:
```
if (mode == FileMode.CreateNew || mode == FileMode.Create) //Files are always created as Archive
                        attributes |= FileAttributes.Archive;
                    File.SetAttributes(filePath, attributes);
```
should really be this:
```
if (mode == FileMode.CreateNew || mode == FileMode.Create) //Files are always created as Archive
{
    attributes |= FileAttributes.Archive;
    File.SetAttributes(filePath, attributes);
}
```

**Comment by Liryna** [comment]
Ok I see your point now. Attributes also need to be changed when a file is opened with write rights
see https://docs.microsoft.com/en-us/windows/win32/fileio/creating-and-opening-files

I made a change https://github.com/dokan-dev/dokan-dotnet/commit/c5c067e96bb36920322855a1ab5aa3e9156559a2 Is that what you were expecting ?

**Comment by Liryna** [comment]
Ok I see your point now. I made the change https://github.com/dokan-dev/dokan-dotnet/commit/879ab9c7d3b5e1df708584d1eac76bf84e46fc91 let me know if that's enough for you
For info see https://docs.microsoft.com/en-us/windows/win32/fileio/creating-and-opening-files

**Comment by dangibson** [comment]
I've added some comments to the commit 87ab9c

**Comment by Liryna** [comment]
Thanks for the comments. See the changes https://github.com/dokan-dev/dokan-dotnet/commit/28cbf81644cea9a265f5499e8d2fb33e0b8bd54a

**Comment by dangibson** [comment]
That looks good. Thanks for your help.
