### ISSUE TITLE
NUL in ReadFile

### ISSUE THREAD

**Issue by TekuSP** [dokan-dev/dokan-dotnet#263]
Greetings,

I have problems with NULs appearing in files, corrupting them this way.
![image](https://user-images.githubusercontent.com/13198444/103183117-d6caf000-48b0-11eb-934b-f5dcd0ff7483.png)

I tried everything in my code, to remove trailing zeros, to check WriteFile... Nothing worked.
How does the buffer system work with WinApi?

Can ReadFile create trailing zeros?
Anyone had ever before such issue?

**Comment by Liryna** [comment]
@TekuSP Hi,

Are you able to reproduce the issue with the sample ?
Does the filled buffer size param is correctly set ? Like the read ask for 200bytes, you only set 190 bytes but you set the read field done to 200 still

**Comment by TekuSP** [comment]
Well, I am trusting Stream to read correctly. I can double check bytesRead value.
`bytesRead = cryptoStream.Read(buffer, 0, buffer.Length);`

**Comment by TekuSP** [comment]
Nope. bytesRead is correctly set.
I tried testing with `Debug.WriteLine($"Bytes were read for file {fileName} were: {bytesRead}");`
And it returned `Bytes were read for file \test.txt were: 3`
Which is correct, but result file is: 
![image](https://user-images.githubusercontent.com/13198444/103225703-d8d19500-492a-11eb-86ee-afdaffa66580.png)

**Comment by Liryna** [comment]
@TekuSP Could it be that the file size returned to the file informations is the size of the encrypted data while the plain data is smaller in reality? And then the diff would be filled with nul.

**Comment by TekuSP** [comment]
That is possible, and I will double check that.

**Comment by TekuSP** [comment]
Yes that was the case! Thank you!
