### ISSUE TITLE
DokanNet.Logging.ILogger

### ISSUE THREAD

**Issue by fengjiannan2010** [dokan-dev/dokan-dotnet#265]
I use log4net to implement the interface of DokanNet.Logging.ILogger. How can I get the class name, method name, and line number of the interface call?

Or how to access a third-party log library to display the class, method, etc. of the output log

**Comment by Liryna** [comment]
@fengjiannan2010 Hi,

I imagine log4net has some options to do that.
It might be good to look at their documentation or open issue to their repository.
