### ISSUE TITLE
BSOD when renaming folder

### ISSUE THREAD

**Issue by 3cooper** [dokan-dev/dokan-dotnet#266]
I have a drive mounted as a network drive.  In the root of the drive, I get a BSOD when a rename a folder.  If I disable the real-time protection in Windows Defender, I do not get the BSOD.  I found an older issue that seems similar: https://github.com/dokan-dev/dokany/issues/414 .

Command I use to mount:

```c#
this.Mount(
  this.driveLetter, 
  DokanOptions.DebugMode | DokanOptions.NetworkDrive, 
  0, 
  Dokan.Version, 
  TimeSpan.FromSeconds(20),
  "\\mydrive", 
  logger
);
```
Log for remote kernel logging:
[rootFolderRenameDump.TXT](https://github.com/dokan-dev/dokan-dotnet/files/6038254/rootFolderRenameDump.TXT)

Recovered crash log from Windows VM:
[crashFile.TXT](https://github.com/dokan-dev/dokan-dotnet/files/6038261/crashFile.TXT)

**Comment by Liryna** [comment]
Hi,

Thanks for reporting the issue!
The mount point value that is you are using is invalid. It should be a local path. Network mount need a local path and a UNC path.

**Comment by Liryna** [comment]
@3cooper Sorry I made a mistake on my previous answer. Your call is correct except the unc name that maybe should be \\myfs\\mydrive

Could you give a try ?

**Comment by 3cooper** [comment]
Thank you for the response.  We did that and it fixed the issue.  Thank you again.
