### ISSUE TITLE
I want to connect with storage in the cloud.

### ISSUE THREAD

**Issue by KimMinJunDev** [dokan-dev/dokan-dotnet#267]
I want to connect with storage in the cloud.
Can I use it by specifying a path as a concatenation of String?
(The cloud service you want to use is Azure.)
Is there any example of connecting through an AccountKey using https?

**Comment by Liryna** [comment]
Hi,

The library will help you to create the volume and display/acces whatever you want in it like Azure. But you will need to implement the Azure API yourself.

Let me know if you need further informations.
