### ISSUE TITLE
Linux FUSE Support

### ISSUE THREAD

**Issue by realivanjx** [dokan-dev/dokan-dotnet#269]
Does this library support linux? What do i need to do to make this library also work on linux? Thanks.

**Comment by Liryna** [comment]
@realivanjx The library would build with .net core but the driver needed under is windows only.

**Comment by realivanjx** [comment]
yes im aware of that but is it possible to use this library with linux fuse then? is there any other way to use linux fuse without writing my own wrapper? thanks.

**Comment by Liryna** [comment]
No the library has no compatibility with Linux fuse behind.
I am not aware of a .net core fuse wrapper sorry.
