### ISSUE TITLE
Integrating dokan-dotnet into existing application without blocking it

### ISSUE THREAD

**Issue by lassevk** [dokan-dev/dokan-dotnet#272]
I have an application, that while running I would like for it to publish a custom file system for internal data.

Since this application is doing other things as well, as well as responding to shutdown commands that terminates the application in an orderly fashion I'm looking for how to integrate Dokan into this.

I cloned the dokan-dotnet repository and tried to change the RegistryFS example to do its own unmounting. If I simply run it, and hit Ctrl-C, I see "send global release for r:", no error messages, and the drive disappears.

Now I want to "unblock" the main program, so I tried changing it to this:

```
    internal class Program
    {
        private static void MountDrive()
        {
            try
            {   
                var rfs = new RFS();
                rfs.Mount("r:\\", DokanOptions.DebugMode | DokanOptions.StderrOutput);
            }
            catch (DokanException ex)
            {
                Console.WriteLine(@"Error: " + ex.Message);
            }
        }

        private static void Main()
        {
            Task.Factory.StartNew(MountDrive);

            Console.WriteLine("Hit enter to unmount");
            Console.ReadLine();

            Dokan.Unmount('r');
        }
    }

```
Now, when I hit Enter, this is output:

```
send global release for r:
Ioctl failed for wait with code 995.
Thread will be terminated
Ioctl failed for wait with code 995.
Thread will be terminated
Ioctl failed for wait with code 995.
Thread will be terminated
Ioctl failed for wait with code 995.
Thread will be terminated
Ioctl failed for wait with code 995.
Thread will be terminated
05/31/2021 14:29:50 - [DokanNet] UnmountedProxy:
05/31/2021 14:29:50 - [DokanNet]        Context {<null>, False, False, False, False, #0, False, False}
05/31/2021 14:29:50 - [DokanNet] UnmountedProxy Return : Success
send global release for r:
DokanError: Ioctl 0x92010 failed with code 122 on Device \\.\Dokan_1
Failed to unmount: r:
```

Now, the drive does disappear from Windows Explorer, but all those error messages tells me this isn't how I am supposed to do it.

So my question is this. How can I, from a separate thread in my program, correctly unmount a Dokan-DotNet mounted file system?

**Comment by Liryna** [comment]
Hi @lassevk ,

This is the correct way to do it by calling `Dokan.Unmount('r');` in another thread.
Looks like you have two calls of this one since you have two `send global release for r:` output. The last one is failing since the device no longer exists.

**Comment by lassevk** [comment]
Where would the other one come from? This is literally the changes I did to the registryfs application, everything is as in the repository, so I only have 1 call to unmount. Perhaps I need to check out the main rfs variable, it might need disposing or something.

**Comment by Liryna** [comment]
After double-checking, the first one is yours and the second one is from the dll detach event.
https://github.com/dokan-dev/dokany/blob/31f8381e1efc207e7c02bdea0a47c819e9810c3f/dokan/dokan.c#L943
The second one from dll detach is for safety purpose (in case the app forget to cleanup). Here you get a failure due to the app that quits too quickly. In fact, knowing that, you do not even need to do a `Dokan.Unmount('r');` yourself if you plan to directly exit since it will be done for you.

**Comment by LTRData** [comment]
I would strongly recommend you to design the application so that you wait for all Dokan threads before exiting. In this particular case, since you start a task, assign the returned Task object from StartNew to a variable and call the Wait method of that object before returning from Main method.

**Comment by lassevk** [comment]
OK, good, I will try this later, thanks!

**Comment by lassevk** [comment]
OK, I now waited for the task to complete before terminating the program, this got rid of some of the errors at the end.

```
send global release for r:
Ioctl failed for wait with code 995.
Thread will be terminated
Ioctl failed for wait with code 995.
Thread will be terminated
Ioctl failed for wait with code 995.
Thread will be terminated
Ioctl failed for wait with code 995.
Thread will be terminated
Ioctl failed for wait with code 995.
Thread will be terminated
05/31/2021 20:15:14 - [DokanNet] UnmountedProxy:
05/31/2021 20:15:14 - [DokanNet]        Context {<null>, False, False, False, False, #0, False, False}
05/31/2021 20:15:14 - [DokanNet] UnmountedProxy Return : Success
```

I take it those Ioctl failures are benign and can be ignored? There was no "unmount failed" though.

**Comment by Liryna** [comment]
@lassevk Yes, this is all "normal" error. The mount left and the ioctl (communication) with it.

**Comment by lassevk** [comment]
Good, thanks! Man I have many ideas for the use of this library :) Thanks!
