### ISSUE TITLE
FileRenameInformationEx Not implemented

### ISSUE THREAD

**Issue by siavash79** [dokan-dev/dokan-dotnet#273]
Hi

Please refer to https://github.com/dokan-dev/dokany/issues/611

While testing my final code using dokan.net, I've ran into the very same problem, receiving error while saving excel file.

My test environment is:
Dokan.Net: Tested against official Nuget package 1.5.0.0, as well as latest github source 20210628
Windows: Windows 10 Insider Preview Build 21370.1
Office: 2019

Using .Net framework 4.7.2

Since I've spent over a month for my implementation based on Dokan.Net, your help will be highly appreciated.

**Comment by Liryna** [comment]
@siavash79 Hi,

**Comment by Liryna** [comment]
Hi,

Is that an issue specific to your implementation ? Does the issue reproduce with the C mirror or the C# mirror ?
Could you share the C mirror logs and also the procmon logs to find out what is failing.

**Comment by siavash79** [comment]
Hi Liryna

The issue happened to me on C# mirror. I noticed that I've been using dokan 1.4 library, and switched to 1.5, using x64 msi file.

However, the problem is not yet resolved, and I'm still getting the same error when saving excel files.

**Comment by Liryna** [comment]
@siavash79 What about the C mirror ? https://github.com/dokan-dev/dokany/wiki/Use-Mirror-example
As said before, any logs to share ?

**Comment by siavash79** [comment]
This is the log for C mirror. But it did not reproduce in C mirror.

[dokan.log.txt](https://github.com/dokan-dev/dokan-dotnet/files/6724122/dokan.log.txt)

**Comment by Liryna** [comment]
@siavash79 Great! So this is not a dokan issue but a C# implementation issue.
You will need to compare the C and C# logs to find out what is the difference and where it breaks excel.
