### ISSUE TITLE
XML documentation missing from NuGet package

### ISSUE THREAD

**Issue by Dwedit** [dokan-dev/dokan-dotnet#275]
When I add the NuGet package "DokanNet" to my project, there is no documentation for anything, and there are no XML documentation files anywhere in the package directory.

I managed to find a workaround to get XML documentation working.

I downloaded the DokanNet project, turned on generation of XML documentation (This was not enabled by default), then built the project.  Then I found the 230KB XML file named "DokanNet.xml" that it generated.

Then I went into the project's "Packages" directory, then everywhere I saw a file named "DokanNet.dll", I copy-pasted in the "DokanNet.xml" file.  After doing this, I got XML documentation in Visual Studio.

**Comment by Liryna** [comment]
@Dwedit Hi,

Thank you for the feedback!
Would you like to make a contribution with the change you described to allow other users to also see the documentation?

**Comment by Dwedit** [comment]
Sorry, I don't know how to make the Nuget package generator place the XML files in the correct places, I'll need some more research for that, looking at it right now.

Right now I'm just doing it manually.

**Comment by Liryna** [comment]
Fixed by https://github.com/dokan-dev/dokan-dotnet/pull/276 Thanks again @Dwedit for reporting the issue and providing the fix too 🏆 !!!
