### ISSUE TITLE
Prevent deletion of Directory and Files

### ISSUE THREAD

**Issue by abhilashca** [dokan-dev/dokan-dotnet#278]
Hello,

I am using Dokan to show the files and directories that are on my remote server (or cloud) based on the target endpoint the app points to. I want to prevent the user from deleting Directory and Files that are listed in their virtual file system.

To prevent deletion of files and folder, I am checking for `DeleteOnClose` in `CreateFile`.  Below is the code snippet I have in `CreateFile`.

```
public NtStatus CreateFile(...)
{
	string path = GetPath(fileName);

	if (options == FileOptions.DeleteOnClose)
	{
		info.DeleteOnClose = false;
		return NtStatus.AccessDenied;
	}
	
	// rest of the code follows
}
```

Now, when I try to delete a directory, I get below dialogs or prompts which is as expected.

![image](https://user-images.githubusercontent.com/12084395/145723456-b91279fd-09a8-4fd6-ac4f-caa2789d8fd3.png)

Now, when I try to delete a file, I get below dialog with message - "_Invalid MS-DOS function_":

![image](https://user-images.githubusercontent.com/12084395/145723584-4de8c6c3-d584-4341-becd-d1464ef315eb.png)

I think, the message "_Invalid MS-DOS function_" is shown because I haven't configured something properly.

Can anyone please help on how to show proper access denied error instead of "_Invalid MS-DOS function_".

Thanks in advance.

**Comment by Liryna** [comment]
Hi @abhilashca ,

You could look at the [Procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) logs filtered on the file to see if anything looks suspicious.
It might also be a good idea to implement GetFileSecurity and deny the delete action. You can even set the filesystem readonly at mount if you also do not want the user to write

**Comment by abhilashca** [comment]
Thank you for the reply. Much appreciated. I have enabled `DokanOptions.WriteProtection` at the time of mounting the disk. This has taken care of all the edit/delete scenarios.

Now, when I try to save a text file, I am getting below error message:

![image](https://user-images.githubusercontent.com/12084395/145851948-2af5a99f-a99b-4e62-b7cf-a43eb93b2807.png)

Any idea why the error message talks about bad image instead of access denied.

**Comment by Liryna** [comment]
It looks like you have an invalid installation of dokan. The path for dokannp1 should be in system32.

**Comment by abhilashca** [comment]
I figured out the issue. Within `ReadFile()`, if any the files are outside my remote files, then I was returning `Not Implemented`.

I found this in my console - `12/17/2021 20:41:14 - [DokanNet] ReadFileProxy : \System32\System32\dokannp1.dll Return : NotImplemented ReadLength : 0`

I think, I am good for now. Will reopen the ticket if I get stuck again.
Thank you for the help. Much appreciated.
