### ISSUE TITLE
Google uses Dokan

### ISSUE THREAD

**Issue by fiddyschmitt** [dokan-dev/dokan-dotnet#281]
Hi,

Not an issue, but I'd like to point out that it looks like Google is using Dokan for its Google Drive windows client (Drive for Desktop).

`C:\Program Files\Google\Drive File Stream\Drivers\3688\googledrivefs3688.inf`

What a vote of confidence!

Thanks for your great work, and Happy New Year.

Fidel

![Dokan](https://user-images.githubusercontent.com/15338956/147921959-301c33c9-7ddd-4acf-a3ef-9fbc29a2086b.JPG)
`

**Comment by Liryna** [comment]
Hi @fiddyschmitt ,

It is the case! They kind of have their own version with a few difference.
Their repository is here https://github.com/google/google-drive-dokany
Disclosure: I am actually in their team in working on this dokan version.

**Comment by fiddyschmitt** [comment]
That's great, thanks for confirming!

I must say, it seems much more stable than when I used it back in 2018.
