### ISSUE TITLE
There was a problem copying large files from the virtual disk to the local disk letter

### ISSUE THREAD

**Issue by 382215852** [dokan-dev/dokan-dotnet#286]
When I copy a large file to the local drive letter, the large file needs to be downloaded from the server. The download time is more than 90 seconds. During this period, windows pops up the copy progress window. The remaining time in the pop-up window: calculating, When my big file download is completed, the windows pop-up window will pop up

Title: an interrupted operation
Content: an unexpected error prevented you from copying the file. Error 0x800705aa: insufficient system resources to complete the requested service

Then, after I click Retry, the file is normally copied to the local drive letter, but later when I edit the file and drag it to the virtual disk to overwrite the file in the virtual disk, windows prompts that the file resources are occupied

Double click to open this large file (the download time is more than 90 seconds), but it can be opened normally.

**Comment by Liryna** [comment]
If you are using a sample here, they are just not adapted for long requests that would end up timeout after 90sec by the kernel.
If you are using your own implementation, you can call `DokanResetTimeout` to request more timeout to the kernel to process it.

**Comment by 382215852** [comment]
> If you are using a sample here, they are just not adapted for long requests that would end up timeout after 90sec by the kernel. If you are using your own implementation, you can call `DokanResetTimeout` to request more timeout to the kernel to process it.

thank you!it works
