### ISSUE TITLE
How can I listen to the event of copying from virtual disk to local disk?

### ISSUE THREAD

**Issue by leizzzz** [dokan-dev/dokan-dotnet#287]
Movefile() will only detect the event that the virtual disk moves to the virtual disk. What should I do to detect the copy / move event from the virtual disk to the local disk letter

**Comment by Liryna** [comment]
Hi @leizzzz ,

Please see https://stackoverflow.com/questions/45570786/how-can-i-detect-copying-files-from-dokan-drive-to-the-same-dokan-drive
Let me know if you have further questions 👍

**Comment by leizzzz** [comment]
> Hi @leizzzz ,
> 
> Please see https://stackoverflow.com/questions/45570786/how-can-i-detect-copying-files-from-dokan-drive-to-the-same-dokan-drive Let me know if you have further questions +1

Although the problem has not been completely solved, thank you for your help

**Comment by Liryna** [comment]
As I said you can let me know if you have further questions and I will reopen the ticket.

**Comment by leizzzz** [comment]
> As I said you can let me know if you have further questions and I will reopen the ticket.

When copying to the local drive letter, for example, when copying from dokan's mounted drive letter to the desktop, writefile() will not be triggered

**Comment by Liryna** [comment]
Dokan only allows you to get the event to the virtual disk created. You can only get the read event generated by explorer during the copy from the virtual disk to the local.

**Comment by leizzzz** [comment]
> Dokan only allows you to get the event to the virtual disk created. You can only get the read event generated by explorer during the copy from the virtual disk to the local.

Thanks for your help
