### ISSUE TITLE
ExecutionEngineException while testing

### ISSUE THREAD

**Issue by maltesermailo** [dokan-dev/dokan-dotnet#289]
So, I'm writing a moderately sized application for a school project. Unfortunately, during testing, I encounter crashes of the application all the time while fixing those bugs. (Side point, it's the Dokan portion of the application, the rest was already tested, so I can't try other things to mitigate this). When the debugger kills the application when it encounters a bad exception, it doesnt seem to call my Cleanup method in OnStop() of the Service, so I'm guessing the application isn't shutting down gracefully. Trying to restart the application after fixing the bug won't work then, since the app will crash with ExecutionEngineException directly after Mounting and before Windows will read the root directory. This is impacting my debug session with a lot of restarts and I would like to know if there is anything I can do or anything to look out.

Additionally I tried unmounting the file system with DokanCTL.exe but it neither can retrieve the mount point list nor can it unmount the specified drive resulting in this:
.\dokanctl.exe /u X:
Driver path: 'C:\WINDOWS\system32\drivers\dokan2.sys'
Send global Release for X:
DokanError: Ioctl 0x92010 failed with code 122 (ERROR_INSUFFICIENT_BUFFER) on Device \\.\Dokan_2
Failed to unmount: X:
Unmount status = 1

**Comment by Liryna** [comment]
Are you able to run the native samples that are part of the installer ? Same question with the DotNet samples.

Do you have any crashes with those ?

**Comment by maltesermailo** [comment]
I updated the Nuget from 2.0.1 to 2.0.1.1 and now it seems to be working. Although it had no call stack. It was just EngineExecutionException in unknown module without any stack trace. That's what perplexed me.
