### ISSUE TITLE
KeepAlive logic

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokan-dotnet#292]
this is  a question more than an issue:

in the changelog of dokany 2 is stated that the legacy keepalive logic have been removed, but as I'm trying to migrate our implementation I've found that i receive no error from the compiler...
I'm doing something wrong ? it's just ignored ? or there is a new logic that accept the same inputs from the old api ?

**Comment by Liryna** [comment]
It is a kernel library logic change which does not affect the user implementation. It just mean it is one of the reasons we broke backward compatibility.
It is normal that it is invisible for the user implementation.
