### ISSUE TITLE
Slightly longer files

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokan-dotnet#294]
As i was investigating a bug in our implementation, I've found out that the problem is reproducible also with the mirror.
Probably it's a dokan-net problem or even a dokany...
The simplest way to reproduce this is to use the test code I've wrote:

```csharp
private static void CreateMemoryMappedFile(String path)
{
    var dataLength = 250;
    var padding = 250;
    var paddedLength = dataLength + padding;
    var fileLength = (Environment.ProcessorCount * paddedLength) - padding;
    if (System.IO.File.Exists(path)) System.IO.File.Delete(path);
    using (var mmf = MemoryMappedFile.CreateFromFile(path, System.IO.FileMode.Create, null, fileLength))
    {
        var tasks = Enumerable.Range(0, Environment.ProcessorCount).Select(n => Task.Run(() =>
        {
            var buffer = new byte[dataLength];
            for (int i = 0; i < dataLength - 1; i++)
            {
                buffer[i] = (Byte)(n + 1);
            }
            var position = paddedLength * n;

            using (var accessor = mmf.CreateViewAccessor(position, dataLength))
            {
                accessor.WriteArray(0, buffer, 0, buffer.Length);
            }
        })).ToArray();
        Task.WaitAll(tasks);
    }
    Debug.Assert(new System.IO.FileInfo(path).Length == fileLength);
}
```

this simply use a memory mapped file to write simultaneously different portions of the file, the file size should be precisely the one expected, but it gets rounded to the next power of 2, which makes me and my colleague think that somewhere we receive a buffer length instead of the actual size of the data to write.

This is not reproducible using something like notepad, but it is consistent with any other drive than dokan

**Comment by Liryna** [comment]
The buffer pool is normally not used if the length is not a power of two.
https://github.com/dokan-dev/dokan-dotnet/blob/b4ee9a72e54b357ed938d54d3eecf41cedd5202a/DokanNet/BufferPool.cs#L94-L100

>Probably it's a dokan-net problem or even a dokany...

That's a good question, can you try on the C mirror/memfs if the issue is present ?

When you enable the logs, what write size is requested ?

**Comment by TrabacchinLuigi** [comment]
can't do it right now, but I'm sure i was writing files with a power of two length, they where 6k and 5750 bytes long.
Small files, and the written file resulted being 8191bytes or 0x1FFF, i think tomorrow i can provide more feedback, is the mirror in c still delivered with the setup ?

**Comment by Liryna** [comment]
Yes mirror and memfs are still in the installation folder. Or you can get them from the zip if you prefer.

**Comment by TrabacchinLuigi** [comment]
Sorry i got confused on the power of two 🤦🏼‍♂️
So with C implementation of mirror i get the expected file size 5750, and i was noticing that the disk file size instead is 8k or 2^13,
which is ok, it's due to the sectors size... 
Probably since i got confused before, 8191 was just the index of the last byte.
So the theory is .net version write the padding to the sector as part of the file in some case?

**Comment by Liryna** [comment]
Great! At least we know it is a C# issue.

>So the theory is .net version write the padding to the sector as part of the file in some case?

I am not aware of a specific code to do that 🤔 would need to look at the logs see if the driver request get changed by the wrapper

**Comment by TrabacchinLuigi** [comment]
not sure it's the right thing: [output](https://gist.github.com/TrabacchinLuigi/16ac953666176fe7b7123a0e4d991e41)

**Comment by Liryna** [comment]
That's the native logs and it is sadly missing the write size....well let's look at the dotnet one https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/DokanOperationProxy.cs#L451-L457

It needs to be turned on by setting the [ConsoleLogger](https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/Logging/ConsoleLogger.cs) during [Mount](https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/Dokan.cs#L55)

**Comment by TrabacchinLuigi** [comment]
![A breakpoint](https://i.imgur.com/VtsKZNF.png)
A breakpoint is worth a thousand logs, here we receive a buffer that is way longer than the data to be written but we have no way to tell how much of that buffer we need to copy into the destination

**Comment by Liryna** [comment]
There is a Write of 4096 at offset 4096 so that seems logic to end with a 8196 file size.
When you run the same test against mirror with the logs enabled, what are the write size / offset ? are they the same

**Comment by TrabacchinLuigi** [comment]
[Here](https://gist.githubusercontent.com/TrabacchinLuigi/4cf3f650123edc27e8b701005cf3870c/raw/ae7f064ac91197356bbde2aaed4526a79f257d63/mirror%2520custom%2520output.txt) a new updated more concise log with a custom output

```csharp
public NtStatus WriteFile(string fileName, byte[] buffer, out int bytesWritten, long offset, IDokanFileInfo info)
{
    var a = $"buffer length is {buffer.Length} and  offset is {offset}";
    var b = String.Join(" ", buffer.Select(x => x.ToString("X2")));

    Console.WriteLine();
    Console.WriteLine();
    Console.WriteLine(a);
    Console.WriteLine(b);
    Console.WriteLine();
    Console.WriteLine();
...
}
```

**Comment by TrabacchinLuigi** [comment]
I can confirm that the pooling of buffers isn't involved since the unsafe implementation yields the same results

**Comment by Liryna** [comment]
In your logs there is a print saying the length 8192 before it even starts to write. From where does it comes from ?

**Comment by TrabacchinLuigi** [comment]
i belive it's the existing file, it deletes it before writing, but i can delete it and update the logs to be less confusing

**Comment by TrabacchinLuigi** [comment]
i've updated the log... but if i use the unmanaged version the logs looks the same, the file doesn't ...

**Comment by TrabacchinLuigi** [comment]
[unsafe logs](https://gist.github.com/TrabacchinLuigi/bf98ff411030c4ae0504bad9b1f884f8/raw/d7a37b547e7ba231e1623f9458b1f03eaa12e32d/mirror%2520native%2520custom%2520output.txt) 
those ones are wildly wrong, but the file size is respected this time... it's like it wrote on the same memory more than once... 
Also i don't understand how it can respect the file size since it still writes 4096bytes starting from 4096

**Comment by Liryna** [comment]
It is actually the user filesystem that needs to check if it is a PagingIo and only write until the end of the file whatever the size was provided. The reason is that only the user filesystem know the real file size. Yes Dokan Kernel could have known by caching the filesize from a previous GetFileInfo request but we just do not want to take the risk to not have the latest info.
https://github.com/dokan-dev/dokany/blob/master/samples/dokan_memfs/memfs_operations.cpp#L344-L366
This is not documented in the library header but it is a well-known aspect of Windows (which they document)
https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.h#L345-L363
We could probably add a hint in the doc to follow Microsoft documentation for PaginigIo.
and also make the C# mirror support that case https://github.com/dokan-dev/dokan-dotnet/blob/master/sample/DokanNetMirror/Mirror.cs#L303

@TrabacchinLuigi sorry took me time to remember this 🤦

**Comment by TrabacchinLuigi** [comment]
i'll provide a pr for this, but i think i've got another bug.
