### ISSUE TITLE
In the Windows 10 operating system, deleting a file does not call the DeleteFile request.

### ISSUE THREAD

**Issue by 382215852** [dokan-dev/dokan-dotnet#297]
In the Windows 10 operating system, deleting a file does not call the DeleteFile request.
Is there any solution？To request DeleteFile .

**Comment by Liryna** [comment]
Please see the documentation and especially around DeleteOnClose https://github.com/dokan-dev/dokan-dotnet/blob/master/sample/DokanNetMirror/Mirror.cs#L253
