### ISSUE TITLE
Why is DokanException internal?

### ISSUE THREAD

**Issue by voltagex** [dokan-dev/dokan-dotnet#30]
I'd like to throw in the constructor of my filesystem if the file I'm loading can't be found (e.g. to mount a tar file).

**Comment by Liryna** [comment]
I don't really understand, could you give a example ?

**Comment by voltagex** [comment]
```csharp
public class Operations : IDokanOperations
        public Operations(string TarFile)
        {
            if (!File.Exists(TarFile))
            {
                throw new DokanException(...);
            }
...
```

Instead I can throw from the mounter exe, it doesn't change much - just wondering.

**Comment by Liryna** [comment]
Ok I see !
I don't this is the purpose of DokanException to be used like in your exemple.
It is only used in case the C part of dokan have failed.
