### ISSUE TITLE
Parameter name confusion in  DokanNet.IDokanOperations.ReadFile()/WriteFile()

### ISSUE THREAD

**Issue by thechosensausage** [dokan-dev/dokan-dotnet#306]
The `offset` parameter in  `DokanNet.IDokanOperations.ReadFile()` stands for the position of the file to start reading.
However, in `System.IO.Filestream`, `offset` stands for the byte offset in array at which the read bytes will be placed. Same goes for the `Write()` method. This is quite confusing.

Could you change the parameter name to something like position or startPosition?

**Comment by Liryna** [comment]
The **Async** Read/Write `System.IO.Filestream` indeed use the `offset` naming for the buffer position but here ReadFile & WriteFile are sync which requires to `Filestream.Seek` that use the `offset` name for setting the file position.

Naming it `position` or `startPosition` could still be understood as the position in the buffer.

I believe we should just have a clear documentation that states the type of `offset` it is which seems to be the case https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/IDokanOperations.cs#L104
That said, I don't have a strong opinion. If someone find a better name 👍 or doc. Feel free to propose a change.
