### ISSUE TITLE
How to pass extra context

### ISSUE THREAD

**Issue by qiandi** [dokan-dev/dokan-dotnet#307]
The FindFiles method reads a list of files via the API, with some extra information that I need to pass to CreateFile.  I want to be able to pass a Guid to get some extra information when CreateFile gets, currently only the filename.

Is there any support please?

**Comment by Liryna** [comment]
Hi @qiandi ,

Unfortunately that's not possible. There is no context shared between Win32 `FindFirstFile` and `CreateFile`.
