### ISSUE TITLE
Filesystem notifications seemingly don't fire when they are supposed to (Windows 10, net6.0-windows)

### ISSUE THREAD

**Issue by yodadude2003** [dokan-dev/dokan-dotnet#310]
Hello, 
I am having an issue with the most recent version of DokanNet (was happening with the previous version, too) where whenever I create, delete, or update files/directories in my mounted filesystem, I have to refresh the Windows Explorer view of the tree to see the changes reflected, even when the changes are triggered by Windows Explorer itself (i.e creating a new text file or folder). 

You can see all of my code here. I used the Mirror sample as a starting point and worked from there. Relevant code is in ArchiveOperations.cs and Program.cs. 
https://github.com/yodadude2003/DATOneArchiver/tree/dokan-driver/DATOneDriver

I don't know if its my code, or yours 😅

**Comment by Liryna** [comment]
If a file is created inside the virtual volume, you should not have any issues.
It is only if the file is created outside of it like in the remote storage that it is virtually showing locally that your fs has to notify the change by using the extra API.

To see if it is your fs the issue, you can try to reproduce with the DotNet sample and the native one.
If they work, you will need to find out what is the difference.

**Comment by yodadude2003** [comment]
Okay, sounds good. I'll update you later this week once I have a chance to do that.

**Comment by yodadude2003** [comment]
Turns out I had time today xD
I tried to run the mirror sample and it works as expected. Seems like there is something I am missing in my own code. There are many differences so it will be difficult to narrow down exactly what the problem is 🥴

If I feel like pursuing this, I will post on this thread with the solution I find to help others who might happen upon this. 
Otherwise consider this issue closed. Thanks :)

**Comment by Liryna** [comment]
Don't hesitate to use procmon tool to compare the difference between the working sample and yours.
Like record the event when creating a simple file and see from there.

**Comment by yodadude2003** [comment]
Thank you for the suggestion! That will be helpful

**Comment by yodadude2003** [comment]
After hours of debugging, I found that the root cause of the issue was the fact that I hadn't implemented the FindFilesWithPattern method. 

I had done so purposefully because the documentation mislead me, it said that the dokan library would handle it. Perhaps it should be made more clear that implementors must still include an implementation, just that they can use the Dokan pattern helper to simplify the code. 

This is how my code ended up looking:
```csharp
        public NtStatus FindFiles(string filePath, out IList<FileInformation> files, IDokanFileInfo info)
        {
            return FindFilesWithPattern(filePath, "*", out files, info);
        }

        public NtStatus FindFilesWithPattern(string filePath, string searchPattern, out IList<FileInformation> files, IDokanFileInfo info)
        {
            var node = archive.Root.Get(filePath, false);
            if (node == null)
            {
                files = null;
                return DokanResult.FileNotFound;
            }
            else if (node.Children == null)
            {
                files = null;
                return DokanResult.NotADirectory;
            }

            files = node.Children.Values
                .Where(n => DokanHelper.DokanIsNameInExpression(searchPattern, n.Name, true))
                .Select(n => new FileInformation
                {
                    Attributes = n.Children != null ? FileAttributes.Directory : FileAttributes.Normal,
                    FileName = n.Name,
                    Length = n.Stream?.Length ?? 0,
                }).ToList();

            return DokanResult.Success;
        }
```

**Comment by Liryna** [comment]
Indeed! There is a TODO but no issue or documentation 😢 I created #311
https://github.com/dokan-dev/dokan-dotnet/blob/2e16d06534f04a7cf5188819b320ed65ae65154e/DokanNet/DokanOperationProxy.cs#L655

Thanks @yodadude2003 for sharing the info!

**Comment by yodadude2003** [comment]
Ah that's fair enough. You're welcome! 😁👍
