### ISSUE TITLE
Does it only support running in the console?

### ISSUE THREAD

**Issue by qiandi** [dokan-dev/dokan-dotnet#312]
The same code is normal in the console, but it reports a memory error when running on wpf.(both wpf and console are netcore)

**Attempted to read or write protected memory. This is often an indication that other memory is corrupt.**

Through the log, it is found that some unknown files and folders appear in fileName in the CreateFile method, such as desktop.ini, .git, HEAD, folder.jpg, AutoRun.inf, etc.

_Remarks: Except one is console and one is wpf, other information is the same_

**Comment by qiandi** [comment]
I found this diff: wpf files list with two more non-existing folders .git and HEAD

**Comment by qiandi** [comment]
I found this diff: wpf files list with two more non-existing folders .git and HEAD.

But I don't know how these two files come from, because my file list is read by the API interface.

**Comment by Liryna** [comment]
Hi @qiandi ,

No the library is not limited to console. Could you debug to find out what is returning this error ?
The unknown files and folders are normal. It is the system checking whether they exist.

**Comment by qiandi** [comment]
It's because of my bug
