### ISSUE TITLE
Is FileSystemSecurity affects something in GetFileSecurity method?

### ISSUE THREAD

**Issue by stroev-ao** [dokan-dev/dokan-dotnet#322]
I'm trying to prevent execution of executable files by adding FileSystemAccessRule that deny ExecuteFile right for current user but exe files still runs. How can I reach my goal? Is it possible at all?

**Comment by LTRData** [comment]
It is actually really easy. Just block CreateFile calls that ask for execute access on files. I do that here for example:
https://github.com/LTRData/dokan-dotnet/blob/3368a7bc53d553474abe4cb70db9425cc85b6feb/DiscUtils.Dokan/DokanDiscUtils.cs#L443
