### ISSUE TITLE
Does the driver have compatibility issues with server 2022?

### ISSUE THREAD

**Issue by 239573049** [dokan-dev/dokan-dotnet#323]
Does the driver have compatibility issues with server 2022?

**Comment by 239573049** [comment]
I use drivers in server 2022, but for some unknown reason I cannot use the copy folder

**Comment by Liryna** [comment]
I am not aware of any server 2022 issues. Could you explain what you mean by copy folder ? Can it be repro with the samples and the native samples ?

**Comment by 239573049** [comment]
When I was using the driver in 2022, I was unable to copy the file to my system for unknown reasons, but in win11 and server2019, there is no problem. The error code is 0x80070057

**Comment by Liryna** [comment]
Windows server 2022 probably send different requests to Dokan during copy which is forwarded to your implementation. I would suggest looking at what happens during the copy and see if there is some error or improper data returned that could be the root cause.

**Comment by 239573049** [comment]
> Windows server 2022 probably send different requests to Dokan during copy which is forwarded to your implementation. I would suggest looking at what happens during the copy and see if there is some error or improper data returned that could be the root cause.

He got the error code 0x80070057

**Comment by Liryna** [comment]
I imagine this is the error prompt by Explorer ? I was referring to the mirror or your filesystem implementation activity.

**Comment by 239573049** [comment]
> I imagine this is the error prompt by Explorer ? I was referring to the mirror or your filesystem implementation activity.

How do I need to observe it

**Comment by Liryna** [comment]
You could use [Procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) with a filter on explorer to see what is happening and match the activity in the dokan logs.

**Comment by 239573049** [comment]
> You could use [Procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) with a filter on explorer to see what is happening and match the activity in the dokan logs.

Ok, I'll try
