### ISSUE TITLE
FILE SIZE  BUG

### ISSUE THREAD

**Issue by snikeguo** [dokan-dev/dokan-dotnet#328]
![image](https://user-images.githubusercontent.com/20830435/230713851-7d12c8ce-5772-43ca-b3a1-d12481fdb6f7.png)

**Comment by Liryna** [comment]
@snikeguo There is a high chance this is an issue in your implementation between the information returned by findfiles and getfileinformation.

**Comment by snikeguo** [comment]
04/09/2023 13:01:02 - [Dokan] [David]FindFiles:add item:\E\Test\B_false_app_test_flashdriver_erase.s19,size:3604476
04/09/2023 13:01:02 - [Dokan] [David]FindFiles:add item:\E\Test\LaoMaoTao.7z,size:1213467906
04/09/2023 13:01:02 - [Dokan] [David]FindFiles:add item:\E\Test\test.txt,size:291

```
 public NtStatus FindFiles(string fileName, out IList<FileInformation> files, IDokanFileInfo info)
        {
            MyDebug($"[David]FindFiles:{fileName}");
            files = new List<FileInformation>();
            try
            {
                var dirInfo = ExplorerService.GetItemInfo(fileName).Result;
                List<ItemInfo> items = null;
                if (dirInfo.ItemType == ItemType.File)
                {
                    info.IsDirectory = false;
                    items=new List<ItemInfo>();
                    items.Add(dirInfo);
                    MyDebug($"[David]FindFiles:this is a file:{dirInfo.FullName},size:{dirInfo.Size}");
                }
                else
                {
                    info.IsDirectory = true;
                    items = ExplorerService.GetSubItemInfos(fileName).Result as List<ItemInfo>;
                }
               

                foreach (var item in items)
                {
                    var dfi = new FileInformation();
                    dfi.FileName = PathManager.GetItemName(item.FullName);
                    dfi.LastAccessTime = DateTime.Now;
                    dfi.CreationTime = null;
                    dfi.LastWriteTime = null;
                    MyDebug($"[David]FindFiles:add item:{item.FullName},size:{item.Size}");
                    if (item.ItemType == ItemType.Directory)
                    {
                        dfi.Attributes = FileAttributes.Directory;
                        dfi.Length = 0;
                    }
                    else
                    {
                        dfi.Attributes = FileAttributes.Normal;
                        dfi.Length = item.Size;//trace output :the item 's size is 291
                    }
                    files.Add(dfi);
                }
            }
            catch (Exception)
            {

                return NtStatus.Error;
            }
            
            return NtStatus.Success;
        }
```
test.txt 's size is 291 bytes

**Comment by snikeguo** [comment]
@Liryna But when I created an folder, everything worked fine
![image](https://user-images.githubusercontent.com/20830435/230755756-3460a267-0187-44d8-92e0-de62ac65572b.png)

**Comment by snikeguo** [comment]
@Liryna  this is my test code:
https://github.com/snikeguo/DoKanyTest
Merci beaucoup!

**Comment by Liryna** [comment]
@snikeguo This is working as expected. Explorer round the size to 1KB for small size. You can try to reproduce on your local disk and you should see the same.

**Comment by snikeguo** [comment]
@LirynaI mean, this file is only 291 bytes, but the property panel of this file shows 3.43MB.

**Comment by snikeguo** [comment]
@Liryna Test.txt is a text file, but the property panel shows that it is a folder. I clearly set the attribute as fileattributes.normal.

**Comment by Liryna** [comment]
I unfortunately don't have time to look into the code. Please compare with the dokany sample the difference of behavior with your implementation. If you are capable to reproduce the issue with the sample I will be happy to look into it.

**Comment by snikeguo** [comment]
@Liryna Test.txt is a text file, but the property panel shows that it is a folder. I clearly set the attribute as fileattributes.normal.

**Comment by snikeguo** [comment]
![Uploading IMG_20230410_093606.jpg…]()
