### ISSUE TITLE
Locking the entire application on mount

### ISSUE THREAD

**Issue by ZolfSchultz** [dokan-dev/dokan-dotnet#330]
Good afternoon I'm just learning in c#. I am making my disk mount application using wpf. I pasted the mount code from the RegistryFS example, but when I ran the line of code

using (var dokanInstance = dokanBuilder.Build(rfs))
                    {
                        mre.WaitOne();
                    }

the disk is mounted in windows explorer, but the application in wpf is blocked and nothing can be done with it. Wait, please tell me what can be fixed so that there is no blocking of the entire application

**Comment by Liryna** [comment]
Hi @ZolfSchultz ,

`mre.WaitOne();` is blocking the Thread to keep alive `dokanInstance` inside the `using`. This Thread needs to run for your UI to be available. You should store somewhere the `dokanInstance` and not use `using` with `WaitOne`.
