### ISSUE TITLE
The volume label is incorrect

### ISSUE THREAD

**Issue by stroev-ao** [dokan-dev/dokan-dotnet#358]
![image](https://github.com/dokan-dev/dokan-dotnet/assets/86775842/04e1b47e-cbe4-44aa-8c28-81f8ac6753b8)
I set the volume label via the constructor before mounting the disk. Sometimes when I open Explorer the newly mounted virtual disk has the volume label "DOKAN" like in the screenshot. After that I refresh Explorer and only then the correct volume label is displayed.

**Comment by Liryna** [comment]
This is expected but rare if the communication between the kernel and library is too slow to setup
https://github.com/dokan-dev/dokany/blob/master/sys/volume.c#L52-L74

**Comment by stroev-ao** [comment]
Thank you for your reply.
