### ISSUE TITLE
Don't know how to mount the DokanInstance...

### ISSUE THREAD

**Issue by Silloky** [dokan-dev/dokan-dotnet#360]
I've got the following code :
```csharp
var fs = new DavFS(
      _server,
      _token,
      _mountPoint,
      _remotePath
);

var logger = new ConsoleLogger("[Dokan] ");

var dokan = new Dokan(logger);

DokanInstanceBuilder builder = new DokanInstanceBuilder(dokan)
    .ConfigureLogger(() => logger)
    .ConfigureOptions(options => new DOKAN_OPTIONS
    {
        Options = DokanOptions.DebugMode | DokanOptions.StderrOutput | DokanOptions.RemovableDrive,
        MountPoint = _mountPoint,
    });

DokanInstance dokanInstance = builder.Build(fs)
```

DavFS is defined in another file.

So, I've got a DokanInstance object, but how do I mount it ?

Both DokanInstance and Dokan classes don't have any .Mount() method...

I don't understand how to run the instance !

**Comment by Liryna** [comment]
Hi @Silloky ,

[Build(fs)](https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/DokanInstanceBuilder.cs#L86-L93) will instantiate and return a [DokanInstance](https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/DokanInstance.cs#L61-L73) which peform the mount for you

**Comment by Silloky** [comment]
Thanks for your answer !
Oh, so Build automatically mounts it ?

**Comment by Liryna** [comment]
This is correct

**Comment by Silloky** [comment]
Okay thanks !
