### ISSUE TITLE
Write Operation Timeout

### ISSUE THREAD

**Issue by shlatchz** [dokan-dev/dokan-dotnet#37]
I have a timeout problem that only occurs on Win8, during a copy session:

"insufficient system resources exist to complete the requested service"

I've seen that from Dokan v. 0.8.0 you support:

 The timeout per device has been implemented. The DokanOptions has a new property Timeout (Milliseconds)

Can I change this property in the .NET version? or is it editable only in the C version?

Thanks!

**Comment by Liryna** [comment]
The implementation is currently pending
https://github.com/dokan-dev/dokan-dotnet/pull/36

**Comment by shlatchz** [comment]
Cool :+1:

**Comment by Liryna** [comment]
@shlatchz But if I remember you can already call the fonction resetimeout during the write process to give you more time.

**Comment by shlatchz** [comment]
Thanks, it helped!

    info.TryResetTimeout(1000 * 60 * 60 * 12);
