### ISSUE TITLE
Dokan crash on DokanOperations.FindStreams function (not implemented)

### ISSUE THREAD

**Issue by aktivo** [dokan-dev/dokan-dotnet#39]
I use installed DokanInstall_0.8.0_redist-RC2.exe with dokan-dotnet-master on Windows 8.1 Pro x64. 
I develop my own file system. I need bypass DokanOperations function FindStreams because when i click with right mouse button  on folder in mounted drive and select propreties, dokan crash on FindStreams function. I use DokanNetMirror example implementation.

public NtStatus FindStreams(string fileName, out IList<FileInformation> streams, DokanFileInfo info)
        {
            streams = new FileInformation[0];
            return Trace("EnumerateNamedStreams", fileName, info, DokanResult.NotImplemented);
        }

Windows message: "Dokan has stopped working' Close program / Debug program.

**Comment by Liryna** [comment]
Hello @aktivo ,

The dokan-net master branch is more updated than the DokanInstall_0.8.0_redist-RC2.exe release.
Could you use this nuget package ?
https://www.nuget.org/packages/DokanNet/1.0.8-rc2
Or change you branch to this commit: https://github.com/dokan-dev/dokan-dotnet/commit/8c1ffd21dd68efe26b6e1383a4176a89e8b4c22c

**Comment by aktivo** [comment]
It works perfectly. Thanks you for help.

**Comment by Liryna** [comment]
No problem :)
