### ISSUE TITLE
Browsing drive in CMD

### ISSUE THREAD

**Issue by entropin** [dokan-dev/dokan-dotnet#4]
Hi, I'm developing a filesystem application using the mirror demo as a reference and noticed that my application can't list files in the file system while browsing it in CMD.

I want back to see, and this do not work in the original examples ether.

$n:
$dir > "Insufficient system resources exist to complete the requested service."
and the c# mirror application crashed.

(Am developing on windows 7)

**Comment by Liryna** [comment]
Hi,

Do you have any call trace of the crash ?

**Comment by entropin** [comment]
Will send it to you as soon as i get home.

**Comment by Maxhy** [comment]
Also, I just tried and it is working as excepted with DokanNetMirror. Did you try with latest driver version or which version are you using?

**Comment by fjch1997** [comment]
Hi,

Has the issue been resolved? Or is it actually a bug of Dokan? I'm considering to start a project using Dokan and I hope it will work as a normal file system will.

**Comment by Liryna** [comment]
Unable to reproduce it and no news from @entropin.
```
C:\>m:
M:\>dir
 Volume in drive M is DOKAN
 Volume Serial Number is 1983-1116

 Directory of M:\

12/18/2009  01:54 PM    <DIR>          .
12/18/2009  01:54 PM    <DIR>          ..
07/29/2015  10:48 AM    <DIR>          Liryna
07/14/2009  09:49 AM    <DIR>          Public
               0 File(s)              0 bytes
               4 Dir(s)     536,870,912 bytes free
```

**Comment by fjch1997** [comment]
Nice. I'm glad to find this open source project. Before this I was going to use the Callback File System which is labeled 10000+ USD
