### ISSUE TITLE
Typo in "RegistoryFS", should be RegistryFS

### ISSUE THREAD

**Issue by nicolas-raoul** [dokan-dev/dokan-dotnet#40]
Just a typo, but it might cause some confusion.

**Comment by Liryna** [comment]
:disappointed: Oh, I have even not seen...Thank you @nicolas-raoul :+1:

**Comment by nicolas-raoul** [comment]
Thanks for fixing it so fast!

Oh, by the way, I implemented [CmisDrive](https://github.com/aegif/CmisDrive) using Dokan.net, feel free to link to it if you want :-)

Cheers!
Nicolas
