### ISSUE TITLE
BSOD With Recent dokany

### ISSUE THREAD

**Issue by shlatchz** [dokan-dev/dokan-dotnet#41]
Hello,

Recent Dokany + Latest Dokan DotNet = BSOD

    Application: DokanNetMirror.exe
    Framework Version: v4.0.30319
    Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFFBDD7657F (00007FFFBDA80000) with exit code 80131506.

BSOD:
![bsod](https://cloud.githubusercontent.com/assets/4594463/11158785/264de0cc-8a63-11e5-8f0c-bf196cfe11b8.png)

**Comment by Liryna** [comment]
New CreateFile is not implemented.
I have begun to do it but I have an issue that I need to fix.

**Comment by Liryna** [comment]
I have changed the wrapper but did not reflect it on the samples & the tests (no time for now).
Tell me if it work on your side :smiley:

**Comment by Liryna** [comment]
I have changed all samples.
Could you try ?

I will try to fix the test tomorrow and will make a nuget release after your feedback.

**Comment by shlatchz** [comment]
Mirror seems to work now :+1:
