### ISSUE TITLE
Move Tests Create/OpenDirectory to CreateFile

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokan-dotnet#42]
Hello @viciousviper ,

Sorry to both you but I have some issue to move the tests to the next CreateFile, I was hopping you could help me a little :smiley: 
Now CreateFile handle the create & open directory.

I have try to fix it here: https://github.com/dokan-dev/dokan-dotnet/commit/caa2b182b698a0b8c7036c5527c71a01da245694
But appveyor or my testing environnement are unable to start a single test :(

As I understood, the CreateFile operations has to be changed to handle the Create/Open directory request.

Here is the Mirror CreateFile output I got when creating and opening a folder:
```
//CreateDirectory New folder
CreateFile('\Users\liryna\Desktop\New folder', {<null>, False, True, False, False, #4264, False, False}, [ReadData, Synchronize], [ReadWrite], [CreateNew], [2097152], [Normal]) -> Success

//OpenDirectory New folder
CreateFile('\Users\liryna\Desktop\New folder', {<null>, False, True, False, False, #4264, False, False}, [Execute, Synchronize], [ReadWrite], [Open], [None], [0]) -> Success
```

**Comment by viciousviper** [comment]
No problem - I'll check this out.

**Comment by viciousviper** [comment]
Ok, I'll still working on it but it's looking a bit more complicated than I first thought.
What is this "2097152" constant anyway? I can't find any DokanNet.FileAccess member matching this value.

**Comment by Liryna** [comment]
This options argument is a part of outFileAttributesAndFlags created here: DokanMapKernelToUserCreateFileFlags 
https://github.com/dokan-dev/dokany/blob/15343707589097d1b6941946506a5b9dac5d4eda/dokan/dokan.c#L706
So values of outFileAttributesAndFlags  can be FILE_WRITE_THROUGH, FILE_SEQUENTIAL_ONLY, FILE_RANDOM_ACCESS....
When I say it is a part: 
https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/DokanOperationProxy.cs#L179

**Comment by viciousviper** [comment]
Hi Liryna,

I made some headway with fixing the unit test suite - please see my checkin https://github.com/viciousviper/dokan-dotnet/commit/7c50dd02f98159a35f0f0dc9c6dc291d031d5691.
I've also taken the liberty of introducing a new `FileOptions` constant named `OpenReparsePointOptions` because the MSDN reference you provided clearly states that 0x0**02**00000 corresponds to `FILE_FLAG_OPEN_REPARSE_POINT` whereas `FILE_FLAG_BACKUP_SEMANTICS` is actually 0x0**20**00000.

**Comment by Liryna** [comment]
Haha :smile: You are right ! I will make the tests as you requested this weekend.

**Comment by viciousviper** [comment]
@Liryna: You can probably close this after https://github.com/dokan-dev/dokan-dotnet/pull/43

**Comment by Liryna** [comment]
:+1:
