### ISSUE TITLE
Multi-threaded ReadFile and C# Streams

### ISSUE THREAD

**Issue by Rambalac** [dokan-dev/dokan-dotnet#46]
Maybe that's not Dokan.Net problem, but I'm not sure how it can be solved reliably and efficiently. 

ReadFile has Offset parameter and presumes operation is atomic and buffer will be filled from that file offset even if another thread run ReadFile from different position.

But C# Streams have Position and Read separate.

In case of Windows Explorer file coping after one CreateFile calls ReadFile from multiple threads. In C# If another thread Stream.Position setter happens between other thread's Stream.Position and Stream.Read you get copied garbage from wrong positions of original file. I believe Mirror also has such problem, just try read files bigger 3Mb (Windows Explorer copy block size is about 500Kb) though in its case Position and Read gap is smaller than in mine.

For now I have two workarounds.
1. Create separate Streams for each thread where ReadFile called. Wasting resources.
2. Block on Position set and Read. Bad for efficiency.

**Comment by Liryna** [comment]
Hello @Rambalac ,

Mirror is a simple example. If performance are an issue for you, you have to change your logic and use something like a cache file or something that fit your needs.
Each request (open, read, cleanup,close), can store data in DokanFileInfo.Context for helping you managing it.

"Windows Explorer copy block size is about 500Kb" Where did you get this information ? For information, it is the kernel who directly request the read/write size.

**Comment by Rambalac** [comment]
```
thread1: CreateFile -------------------------- thread1: info.Context = File.Open
thread1: ReadFile(,,offset: 0,,)  ------------ thread1: info.Context.Position = 0
thread2: ReadFile(,,offset: 500000,,)  ------- thread2: info.Context.Position = 500000
                                               thread1: info.Context.Read(buf, 0, length) // Garbage
                                               thread2: info.Context.Read(buf, 0, length)
```

I get size from ReadFile method, each buffer length is exactly 512Kb.

**Comment by Liryna** [comment]
Ok but sorry I don't understand, what is the goal of your issue ?

**Comment by Rambalac** [comment]
Issue is your Mirror sample is not thread safe and does not work properly with simple file copy in Windows Explorer.
Goal is to make it working in Windows Explorer copy and any other applications reading files in multiple thread.

By the way to copy files Windows Explorer starts 4 threads for each, so calls 4 ReadFile semi-simultaneously for the same file after one CreateFile.

**Comment by Liryna** [comment]
@Rambalac No, if there is 4 request of read from Explorer, there is 4 createfile and therefore 4 context of Streams so no issue. 
If you are scare that Explorer call 4 read from one file descriptor, each kernel request are queue so you will have each read one by one. 


Mirror is perfectly working with Explorer and more advanced request.

**Comment by Rambalac** [comment]
Actually there is one difference with original Mirror. I mount it as
```
mirror.Mount("n:\\", DokanOptions.DebugMode|DokanOptions.NetworkDrive|DokanOptions.StderrOutput, 5);
```

And if you modify ReadFile like this
```C#
            else // normal read
            {
                var stream = info.Context as FileStream;
                stream.Position = offset;

                Thread.Sleep(200);
                if (stream.Position != offset)
                    Console.WriteLine("Wrong Position!!! Should be " + offset + " but is " + stream.Position);

                bytesRead = stream.Read(buffer, 0, buffer.Length);
            }
```

You will see a lot of warnings.

**Comment by Rambalac** [comment]
Actually with fixed drive it happens too after browsing in Win Explorer a lot.
By the way, I'm using Win7

**Comment by Liryna** [comment]
Can you try with:

```
info.TryResetTimeout(500);
Thread.Sleep(200);
if (stream.Position != offset)
	Console.WriteLine("Wrong Position!!! Should be " + offset + " but is " + stream.Position);
```

**Comment by Rambalac** [comment]
I can try it in 14 hors.
Is there any reliably way to prevent it? I'm making driver for Aamazon Cloud Drive and its latency is far from even local network. For example, I can detect wrong position, because of timeout, or just check time before and after. Which is better?

Same context got reused in different thread. 
Should I return some special bytesRead and timeout Status?
 Is it important to keep buffer untouched by timeouted thread?

**Comment by Liryna** [comment]
You can try to grow the buffer size See: https://github.com/dokan-dev/dokan-dotnet/issues/38
Or cache your files, or chrono your request and call info.TryResetTimeout when you need more time.

I know that differenet peoples have been able to handle such situation.

**Comment by viciousviper** [comment]
I believe this behavior is a manifestation of Win32 Overlapped I/O.
See e.g. https://msdn.microsoft.com/en-us/library/windows/desktop/aa365683%28v=vs.85%29.aspx for more details, especially the section starting with the phrase *The system does not maintain the file pointer on asynchronous handles to files and devices ...*
AFAIK there is no direct support for Overlapped I/O in .NET, so you'll have to roll your own implementation of a scatter/gather file buffer.

**Comment by Rambalac** [comment]
Growing buffer just delay first response.
I can not cache file being cached.

Well, actually .NET has Overlapped I/O, it's async. So I will try it.

**Comment by Liryna** [comment]
It would be interesting @Rambalac if you could provide a sample with overlapping that show multiple calls of readfile with the same info. If it is confirmed, I will change the documentation like you requested.

From the microsoft documentation about Overlapping, dokan is handling properly the request. 
https://msdn.microsoft.com/en-us/library/windows/hardware/dn613924%28v=vs.85%29.aspx

**Comment by Rambalac** [comment]
Sample is the same but with lock
```C#
 else // normal read
            {
                var stream = info.Context as FileStream;
                lock(stream){
                stream.Position = offset;

                Thread.Sleep(200);
                if (stream.Position != offset)
                    Console.WriteLine("Wrong Position!!! Should be " + offset + " but is " + stream.Position);

                bytesRead = stream.Read(buffer, 0, buffer.Length);
               }
            }
```

No warnings as without lock.

**Comment by Liryna** [comment]
Oh sorry I wasn't clear. I was talking about a sample that make overlapped read.(like a test that read a file in the mirror)

**Comment by viciousviper** [comment]
> Seems like Position is still used in async part of ReadAsync.

No kidding. :grin:

**Comment by Rambalac** [comment]
Ok, here is some test https://github.com/Rambalac/DokanNet.OverlappedTest
It creates file with 5 blocks of ```blockSize``` bytes filled with byte value 1 to 5 by number of block
First it reads from real C:\ drive
Then reads from N:\ Dokan Mirror drive

Real C: has no any problem all bytes are correct

If ```blockSize``` if about 1Kb Mirror has no problem
if ```blockSize``` is about 8Mb Mirror reads wrong data
if ```blockSize``` is about 1Mb there is strange error with Win32Api code 6 (Invalid handle) during some random ReadFile

**Comment by viciousviper** [comment]
I can confirm this behavior. This start to go south for me at `blockSize = 1 << 18` equivalent to 256k. 
Haven't had the time for any deeper analysis, though.

**Comment by viciousviper** [comment]
I've tried to capture the overlapped read/write situation into some additional tests in the DokanNet.Tests project - please see #48 for details.
Unfortunately I can't reliably reproduce the error pattern from Rambalac's demo in these tests. While I do get occasionalerrors in the ...WithVariableSizes... tests on OverlappedTest.cs, it is not true that all test runs for buffer sizes of 8MB fail.
It is the case, however, that `ReadFileEx()`/`WriteFileEx()` don't return correct values for `dwNumberOfBytesRead`/`dwNumberOfBytesWritten` in their callback methods. I had to comment out the associated checks in the test code because those would fail consistently.

@Rambalac: Could you try running the new Overlapped tests on your environment and report back?

**Comment by Rambalac** [comment]
I had to set Timeout to 1 minute and QTAgent32 crashes every time.
[results4.zip](https://github.com/dokan-dev/dokan-dotnet/files/72072/results4.zip)

By the way, I have a library ProcessThreads to run something, test for example, in separate process so it will try to retrieve exception or console output at least. Helps if test crashes agent with something like StackOverflow :)

**Comment by viciousviper** [comment]
@Rambalac: Only 13 passed tests looks pretty desolate. Since both Appveyor and the build environments of Liryna and myself are able to run the existing Dokan.NET tests with far more success there appears to be some systematic problem in your environment/settings or some as yet unknown problem in our setups. Could you please check if your "Default Processor Architecture" is set correctly (VS2015 menu Test/Test Settings/Default Processor Architecture)?

Thanks for recommending ProcessThreads, I'll look into this.

**Comment by Rambalac** [comment]
@viciousviper: I used mstest in console with your DokanNet.testsettings. It has Force 32bit.

**Comment by viciousviper** [comment]
@Rambalac: Force 32bit sounds wrong.
However, if you're referring to the setting named "Run tests in 32 bit or 64 bit process" in the "Hosts" configuration section of the .testsettings file, then I've found this to be irrelevant for testing from within VS2015, which is what I always do.
Maybe you can improve your results in the mstest console by switching this setting to "Run tests in 64 bit process on 64 bit machine".

**Comment by Liryna** [comment]
Doc has been added: https://github.com/dokan-dev/dokany/commit/15bb0e4753e611d99bdbd1a982b3ef7c5d63723a

**Comment by Liryna** [comment]
Can this be close @Rambalac ?

**Comment by Rambalac** [comment]
Probably yes.

**Comment by maurosampietro** [comment]
@Rambalac I'm facing the same issue.. can you please tell how did you solve the problem?

**Comment by Rambalac** [comment]
Either make atomic seek and read using something like lock, or use pool of streams.

**Comment by maurosampietro** [comment]
Ok i'm trying that
