### ISSUE TITLE
Thumbnails not generating correctly

### ISSUE THREAD

**Issue by MelcherSt** [dokan-dev/dokan-dotnet#52]
Using the Mirror sample I experience an issue where thumbnails for picture files fail to generate correctly; only a smal horizontal stripe of the original image is visible and the rest of the thumbnail remains grey. Note that these pictures are JPEG files and fairly large in size (about 6Mb). Any clue as to why this happens?

Do note that thumbnails for these files generate correctly in their normal directory (not the mirror disk).

**Comment by Liryna** [comment]
Hi @MelcherSt ,

Did you try with the C mirror ? Do you have the same behaviour ?

**Comment by MelcherSt** [comment]
I've now tried the C mirror. It shows exactly the same behaviour.

**Comment by Liryna** [comment]
Oh thats possible! DId you try with dokan 1.0.0 BETA ?

**Comment by MelcherSt** [comment]
Yes, I tried with both 1.0.0 BETA and 0.8

**Comment by Liryna** [comment]
With the 1.0.0 mirror C, did you enable the mount manager ? ( /g option)

**Comment by MelcherSt** [comment]
I now also tried with the mount manager. Sadly, it's still not working. I do not see any read failures, but often times opening an image results in the picture viewer showing me a grey image instead of the original. Also, something else worth noting; while opening a folder for the first time, I actually see the thumbnails generating but quickly changing to grey. Not sure what that means, but it seems they can't be saved or so?

**Comment by Liryna** [comment]
@MelcherSt I have been able to reproduce the issue.
I think it is an issue of heavy createfile/read calls but I cannot say what is failing. Even without dokan, explorer seems to have issue to create Thumbnails sometimes.

This need to be more investigate.

**Comment by Liryna** [comment]
@MelcherSt , we are going to continue the discution in the ticket https://github.com/dokan-dev/dokany/issues/154 if you want it.

The issue is more related to dokan than dokan wrapper.
