### ISSUE TITLE
Meaning of line 92 in mirror.cs

### ISSUE THREAD

**Issue by Eumeltier76** [dokan-dev/dokan-dotnet#53]
Hello,

I translated the C# mirror example to VB.NET.

I don't understand the meaning of line 92
new DirectoryInfo(path).EnumerateFileSystemInfos().Any(); // you can't list the directory

As far as I see because the return value is not used, this line has no effect?

Martin

**Comment by Liryna** [comment]
Hi @Eumeltier76 ,

EnumerateFileSystemInfos will throw if the user application does not have the rights to access it:
https://msdn.microsoft.com/en-us/library/dd383504(v=vs.110).aspx
`SecurityException	The caller does not have the required permission. `

**Comment by Eumeltier76** [comment]
Ah, I see. It is a trigger for the execption :-)

**Comment by Liryna** [comment]
Yes :smiley:
