### ISSUE TITLE
Saving Modified PDFs with Acrobat Reader DC

### ISSUE THREAD

**Issue by shlatchz** [dokan-dev/dokan-dotnet#54]
When I save the pdf on the dokany mirror, I get a valid CreateFile request:

	CreateFile status = 3221225524 - lastError = 2
	###Create 0135
	CreateFile : C:\Temp\B\10.pdf
	  AccountName: , DomainName: -PC
			ShareMode = 0x0
			AccessMode = 0x12019f
			FILE_READ_DATA
			FILE_READ_ATTRIBUTES
			FILE_READ_EA
			READ_CONTROL
			FILE_WRITE_DATA
			FILE_WRITE_ATTRIBUTES
			FILE_WRITE_EA
			FILE_APPEND_DATA
			SYNCHRONIZE
			STANDARD_RIGHTS_READ
			STANDARD_RIGHTS_WRITE
			STANDARD_RIGHTS_EXECUTE
			FlagsAndAttributes = 0x80
			FILE_ATTRIBUTE_NORMAL
			CREATE_ALWAYS

Whereas, when I try to save it on the dokannet mirror, I get:

    CreateFile('\10.pdf', {<null>, False, False, False, False, #9876, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [Normal]) -> ObjectNameNotFound

Maybe CreateAlways is missing on DokanNet?

**Comment by Liryna** [comment]
We make a simple mapping from the CreateFile CreateDisposition to FileMode C# enum.
https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/DokanOperationProxy.cs#L181

Did you try a sample that make a CREATE_ALWAYS to see if it work ?
If it work, the issue have to come to somewhere else.

**Comment by shlatchz** [comment]
You're right, it's something else...

I ran:

	int main()
	{
		WORD wResId = 101;
		LPCWSTR lpszOutputPath = L"M:\\test.bmp";
		HRSRC hrsrc = FindResource(NULL, MAKEINTRESOURCE(wResId), RT_BITMAP);
		HGLOBAL hLoaded = LoadResource(NULL, hrsrc);
		LPVOID lpLock = LockResource(hLoaded);
		DWORD dwSize = SizeofResource(NULL, hrsrc);
		HANDLE hFile = CreateFile(lpszOutputPath, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
		DWORD dwByteWritten;

		//Write BITMAPFILEHEADER
		BITMAPFILEHEADER bfh;
		bfh.bfType = 0x4d42;
		bfh.bfSize = dwSize + sizeof(BITMAPFILEHEADER);
		bfh.bfOffBits = sizeof(BITMAPFILEHEADER) + sizeof(BITMAPINFOHEADER);
		bfh.bfReserved1 = bfh.bfReserved2 = 0;
		WriteFile(hFile, &bfh, sizeof(bfh), &dwByteWritten, NULL);

		WriteFile(hFile, lpLock, dwSize, &dwByteWritten, NULL);
		CloseHandle(hFile);
		FreeResource(hLoaded);
		return 0;
	}

and the mirror received:

    CreateFile('\test.bmp', {<FileStream>, False, False, False, False, #32188, False, False}, [WriteData, AppendData, WriteExtendedAttributes, ReadAttributes, WriteAttributes, ReadPermissions, Synchronize], [None], [Create], [None], [Normal]) -> Success

**Comment by Liryna** [comment]
Did you find a difference in the calls before CreateFile ?
For me if he request to Open, it mean that he got somewhere the information that the file already exist.

**Comment by shlatchz** [comment]
All the output that concerns the pdf:

	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #3144, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [Normal]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #3144, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [Normal]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #3144, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [Normal]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #4164, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [2097152], [0]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #4164, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [2097152], [0]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #4164, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [Normal]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #4164, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [Normal]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #4164, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [Normal]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #4164, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [Normal]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #4164, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [Normal]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #3144, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [0]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #3144, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [2097152], [0]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #3144, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [0]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #3144, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [2097152], [0]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #3144, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [0]) -> ObjectNameNotFound
	CreateFile('\file system behavior overview.pdf', {<null>, False, False, False, False, #3144, False, False}, [ReadAttributes], [ReadWrite, Delete], [Open], [2097152], [0]) -> ObjectNameNotFound

and in dokany:

http://pastebin.com/vnmYCTLG

**Comment by Liryna** [comment]
In mirror.c, the file is created and working ? or is it corrupted ?
If it is corrupted, try to run the mirror with one thread.

**Comment by shlatchz** [comment]
In mirror.c it works perfectly.
In mirror.cs it doesn't. I also tried with 1 thread and it didn't work.

**Comment by Liryna** [comment]
Ok
From what I see in C# and C, there is a lots of call to `file system behavior overview.pdf` with Open.
After a time the C get a CREATE_ALWAYS but don't know what can be the difference.

You really have only this logs for C# ?

**Comment by shlatchz** [comment]
Here is the unfiltered log from C#:

http://pastebin.com/ddL1nVbV

**Comment by Liryna** [comment]
@shlatchz could you make a test with the new mirror ?

**Comment by Liryna** [comment]
Feel free to comment if you have any update.
