### ISSUE TITLE
DokanFileInfo.GetRequestor() takes 11 seconds

### ISSUE THREAD

**Issue by Rambalac** [dokan-dev/dokan-dotnet#56]
I want to prevent users other than mounter from accessing folders structure and file content.
DokanFileInfo.GetRequestor() is too slow to use in security check in every FindFile or CreateFile as it takes 11 seconds on each execution.
Is there any other way to check if requestor is the same user as mounter?

**Comment by Rambalac** [comment]
For now I made workaround using ProcessId which takes 100ms including WMI request.

**Comment by Maxhy** [comment]
If you want to add this kind of restriction this is the correct way, but I believe you should change the approach. Wouldn't mounting the drive for only a specific user better?
Mounting a drive for current user and not globally is currently not supported but on the global TODO. It should directly be handled by the driver.

**Comment by Rambalac** [comment]
Now I made access only for user mounted drive, but I was thinking to implement full ACL, fortunately Amazon Cloud Drive allows to store metadata. So just hard limited access for mounter will not work for me too.
Is GetRequestor slow because of DokanOpenRequestorToken or new WindowsIdentity? I believe just IntPtr token should be enough. Some how it's about the same slow as TryResetTimeout.

**Comment by Liryna** [comment]
Hum hard to say I have never check the speed of them.
Could you look at the times of `DokanOpenRequestorToken ` and `WindowsIdentity` separatly ?

**Comment by Rambalac** [comment]
Just tried it at home on Windows 10 with latest commit, it does not work at all. Always returns token -1.

**Comment by Liryna** [comment]
It seems to only work with `CreateFile`
See https://github.com/dokan-dev/dokany/blob/15343707589097d1b6941946506a5b9dac5d4eda/dokan/access.c#L50

**Comment by Rambalac** [comment]
Ok, Tested in Windows 7, DokanOpenRequestorToken is 11 seconds and yes, it works only in CreateFile. Looks like there is no other alternative than use ProcessId though not sure how it will work with impersonation which I believe is used for something like network share.

**Comment by Liryna** [comment]
I have change my local C# mirror and added `info.GetRequestor();`for each `CreateFile` calls.
Also added Stopwatch in `GetRequestor`

Code:
```
public WindowsIdentity GetRequestor()
{
	try
	{
		Stopwatch stopWatch = new Stopwatch();
		stopWatch.Start();
		IntPtr ptr = NativeMethods.DokanOpenRequestorToken(this);
		stopWatch.Stop();

		TimeSpan ts = stopWatch.Elapsed;
		Console.WriteLine(String.Format("{0:00}:{1:00}", ts.Seconds, ts.Milliseconds / 10));
		stopWatch.Reset();

		stopWatch.Start();
		WindowsIdentity winId = new WindowsIdentity(ptr);
		stopWatch.Stop();
		ts = stopWatch.Elapsed;
		Console.WriteLine(String.Format("{0:00}:{1:00}", ts.Seconds, ts.Milliseconds / 10));
		stopWatch.Reset();


		Console.WriteLine(winId.Name);
		return winId;
	}
	catch
	{
		return null;
	}
}
```

Results for all calls:
```
00:00
00:00
DESKTOP-RBPTIQA\liryna
```

My virtual Win10 is very slow and the calls take no times.
Does your computer is using an Active Directory ?

**Comment by Rambalac** [comment]
Yes, Window 7 is in domain.

**Comment by Liryna** [comment]
Therefore it is the domain request that is slow.

**Comment by Rambalac** [comment]
But there is no point in anything related to domain. There should just user token, SID or at least domain name\user name. I get user SID from processId field in less then 100ms and that's including whole query to WMI.

**Comment by Liryna** [comment]
I do not know much about `WindowsIdentity` but as I can see, it request a lot of informations to the domain. https://msdn.microsoft.com/fr-fr/library/system.security.principal.windowsidentity_properties%28v=vs.110%29.aspx
This informations can take times to request.

The Dokan code that provide the ptr of the user is fast.
The Windows `WindowsIdentity` object is slow.

I have no idea how to make it faster.

**Comment by Rambalac** [comment]
Slow part is not new WindowsIdentity, but DokanOpenRequestorToken

**Comment by Rambalac** [comment]
new WindowsIdentity actually takes 0ms

**Comment by Liryna** [comment]
Could you provide logs of this code https://github.com/dokan-dev/dokan-dotnet/issues/56#issuecomment-173117194 with the kernel logs with times https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#dokan-driver.

**Comment by Rambalac** [comment]
I can try it tomorrow

**Comment by Rambalac** [comment]
I tried to build it but it's not the same as in documentation. For example all sys and dlls have -1 suffix, like dokan-1.sys. Renaming makes dokanctl unable to do anything, but they work with -1. As for Windows 7 I copied x64/WIndows7Debug/dokan-1.sys to system32/drivers and 2 dlls from x64/Debug to system32. But mirron in dokan.net does not want to work because of  "load a program with an incorrect format".

**Comment by Liryna** [comment]
You need to rename `dokan.dll` to `dokan-1.dll` in this C# file:
https://github.com/dokan-dev/dokan-dotnet/blob/96e4e3448ee435a2dfb884add47d165146bc195b/DokanNet/Native/NativeMethods.cs#L8

dokanctl should be able to install driver with `dokanctl /i d`
https://github.com/dokan-dev/dokany/blob/master/dokan_control/dokanctl.c#L33

**Comment by Liryna** [comment]
I have updated dokan-net in a new branch with the changes for 1.0.0
https://github.com/dokan-dev/dokan-dotnet/commit/6465f1137ac73ad5b5afb35c036a2c19016b1a09

**Comment by Rambalac** [comment]
Actually I did only dokanctl.exe /i a and it was ok showing path to sys 
Just tried dokanctl /i d and 
    PS D:\dev2\dokany\x64\Debug> .\dokanctl.exe /i d
    Driver path: 'C:\Windows\system32\drivers\dokan-1.sys'
    Installing driver...
    DokanServiceInstall: Service (Dokan-1) installed
    DokanServiceControl: Failed to start service (Dokan-1). error = 1275
    DokanServiceInstall: Service (Dokan-1) start failed
    Driver install failed

But the second time it says  Service (Dokan-1) is already installed

**Comment by Liryna** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms681383%28v=vs.85%29.aspx

```
ERROR_DRIVER_BLOCKED
    1275 (0x4FB)
    This driver has been blocked from loading.
```

Try to remove with `dokanctl /r d`, reboot and try `dokanctl /i d`

**Comment by Rambalac** [comment]
Driver is installed, I had to disable driver sign check
```
PS D:\dev2\dokany\x64\Debug> .\dokanctl.exe /i d
Driver path: 'C:\Windows\system32\drivers\dokan-1.sys'
Installing driver...
DokanServiceInstall: Service (Dokan-1) installed
DokanServiceControl: Service (Dokan-1) started
DokanServiceInstall: Service (Dokan-1) started
Driver installation succeeded!
```

But DokanNet 1.0.0 branch still not working
```
Unhandled Exception: System.BadImageFormatException: An attempt was made to load
 a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at DokanNet.Native.NativeMethods.DokanMain(DOKAN_OPTIONS& options, DOKAN_OPER
ATIONS& operations)
```

**Comment by marinkobabic** [comment]
How did you compile the branch x64 or x86? Depending on how the branch is compiled a different dokan-1.dll is used.

**Comment by Rambalac** [comment]
Batch build - Select all - Rebuild

**Comment by Liryna** [comment]
This error mean that you are using a dokan-1.dll with a different architecture that your C# application.
(ex: Mirror.exe run in x64 and you have in the same folder a x86 dokan-1.dll).

**Comment by Rambalac** [comment]
Actually if I run Dokan.Net Mirror in x86, error become ```The specified module could not be found. (Exception from HRESULT: 0x8007007E)```

Ok, I cleaned everything, rebooted, rebuilt, reinstalled, rebooted and now Dokan.
Now Dokan.Net Mirror starts, I added GetRequestor into CreateFile. 
Not every CreateFile takes 11 seconds but every folder change
During that 11 seconds I see many kernel messages
```
[8508] _client_device_change_is_enable_pathW(EXCEPTION_EXECUTE_HANDLER)
```
[kernel.txt](https://github.com/dokan-dev/dokan-dotnet/files/106195/kernel.txt)
[mirror.txt](https://github.com/dokan-dev/dokan-dotnet/files/106196/mirror.txt)

**Comment by Rambalac** [comment]
By the way, that PC is in domain in Japanese company. Not sure if it's important, it should not if there is no problem with Unicode and file names work without problem.

**Comment by Liryna** [comment]
o_O I have no idea where does this message come from. There is nothing in dokan that could create this log.

I will try to make a test in Windows 7 like you.

Do you have the possibility to make a test without domain ?

**Comment by Rambalac** [comment]
Without domain I have only Windows 10.

**Comment by Liryna** [comment]
Ok

Could you provide kernel logs ? (the one you provided is only the C mirror)
https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#dokan-driver

**Comment by Rambalac** [comment]
Enabled all check boxes
[kernel.txt](https://github.com/dokan-dev/dokan-dotnet/files/106285/kernel.txt)
[mirror.txt](https://github.com/dokan-dev/dokan-dotnet/files/106284/mirror.txt)

**Comment by Liryna** [comment]
But this it not the dokan kernel logs :disappointed: 

it looks like that: http://pastebin.com/HgNJG16Y
To enable them: https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#dokan-driver

**Comment by Rambalac** [comment]
Oh, /d 9
Ok. This?
[kernel.txt](https://github.com/dokan-dev/dokan-dotnet/files/107546/kernel.txt)
[mirror.txt](https://github.com/dokan-dev/dokan-dotnet/files/107547/mirror.txt)

**Comment by Liryna** [comment]
Thank you @Rambalac thats the good one logs.

In mirror.txt, it seems that your issue did not happened. (all timer are at 00:00)
In kernel.txt, DokanGetAccessToken take no time:
```
00126873	169.14575195	[DokanFS] ==> DokanGetAccessToken	
00126874	169.14575195	[DokanFS] <== DokanGetAccessToken
```

But we can still see:
```
00037534	70.38326263	[13024] _client_device_change_is_enable_pathW(EXCEPTION_EXECUTE_HANDLER)	
00037535	70.38334656	[13024] _client_device_change_is_enable_pathW(EXCEPTION_EXECUTE_HANDLER[0]	
```
It always take 1 second of your runtime. I have no idea of what is it, I can only say that It is not a dokan output.

I really think that the behaviour you face have nothing connected with GetRequestor otherwise you would have always the issue.

**Comment by Rambalac** [comment]
I removed old mirrot.txt file because forgot to remove account name.
And anyway I also forgot to increase buffer for Mirror console, 11seconds were scrolled out.
Here is new one where DokanGetAccessToken timings are 11 seconds. It's not every CreateFile, but every folder browsing in one or two CreateFile among dozens happen that time
[kernel.txt](https://github.com/dokan-dev/dokan-dotnet/files/109096/kernel.txt)
[mirror.txt](https://github.com/dokan-dev/dokan-dotnet/files/109095/mirror.txt)

**Comment by Liryna** [comment]
There is :confused: 1353 calls of `DokanGetAccessToken` in kernel.txt
Could you help me to find a `DokanGetAccessToken` that take 11 seconds in it ?

**Comment by Rambalac** [comment]
Ok, another logs, should be easier to see
[kernel.txt](https://github.com/dokan-dev/dokan-dotnet/files/109362/kernel.txt)
[mirror.txt](https://github.com/dokan-dev/dokan-dotnet/files/109361/mirror.txt)

**Comment by Liryna** [comment]
Oh Thank you @Rambalac ! that's much clear with the times !

Well, none of the `DokanGetAccessToken` take times in the kernel logs.
But we can see a link with the mirror 11 seconds time and `client_device_change_is_enable_pathW` in the kernel logs.
I really don't know what is making it and could be also linked that it only happen when you change directory.

Just for testing, could you disable GetRequestor call for all directory request and `\`?

**Comment by Rambalac** [comment]
Added 
```
if (!pathIsDirectory) info.GetRequestor();
```
it still takes 11 secs for some files like desktop.ini

**Comment by Liryna** [comment]
@Rambalac Sorry, I have no more ideas. Could you try on a clean windows 7 without domain and after with domain to see if it is not your system?

**Comment by Rambalac** [comment]
Sorry, I dont control domain.
By the way, TryResetTimeout takes the same 11 sec. Fortunately I could set timeout in mount.

**Comment by Liryna** [comment]
I have installed a Windows 7, added it to a domain and impossible to reproduce your issue :(

I really have no more ideas, I would say it is link with your system for now...

**Comment by marinkobabic** [comment]
Please open WinObj.exe and check if there are some special filters attached to the mounted device object. http://download.sysinternals.com/files/winobj.zip

**Comment by Rambalac** [comment]
I can try it on Monday.

**Comment by Rambalac** [comment]
Not sure what should I look for. ATT?
![image](https://cloud.githubusercontent.com/assets/7804519/12713037/a1515eee-c90f-11e5-903b-65fd221e1e87.png)

**Comment by marinkobabic** [comment]
It looks fine, only the FltMgr is attached. If you need a drive just for the current logged in user, you can now use the actual source code a build it your self. There is a new option DOKAN_OPTION_CURRENT_SESSION. This allows you to create the mount point resp. drive letter visible only to the user which executes the mount operation. From my point of view, this is the way to go in your particular case.

**Comment by Rambalac** [comment]
But I want to implement real ACL

**Comment by Liryna** [comment]
@Rambalac what you face is linked to your environment. I have made the test in different windows and I was not able to reproduce this behaviour. You should find what software is interacting in a way with dokan to create your issue.

And specially `_client_device_change_is_enable_pathW`

Do you really not have a virtual machine to make you test or in another computer ?

**Comment by Liryna** [comment]
Hi @Rambalac ,

Have you been able to fix or get more informations about your issue ?

**Comment by Liryna** [comment]
Feel free to reopen if you have new informations about it
