### ISSUE TITLE
Disk size with Removable Options

### ISSUE THREAD

**Issue by shlatchz** [dokan-dev/dokan-dotnet#57]
When I set the disk to removable drive, and change the following in the sample:

	public NtStatus GetDiskFreeSpace(out long free, out long total, out long used, DokanFileInfo info)
	{
		used = 5497345047671;
		total = 5497345047671;
		free = 5497345047671;
		return Trace("GetDiskFreeSpace", null, info, DokanResult.Success, "out " + free.ToString(), "out " + total.ToString(), "out " + used.ToString());
	}

and try to execute:

    xcopy C:\Temp\E\2\* H:\A\B\*

I get:

    Insufficient disk space on current disk.
    Insert another disk and type <Return> to continue...

This only happens with the removable drive option.
Both network and fixed work well, and only the removable option has a problem with 5TB disks...

**Comment by Liryna** [comment]
Have you been able to see from which size this behaviour begin to happen ?

It is probably a Windows limitation for this type of device...but I find nothing on the documentation about `FILE_REMOVABLE_MEDIA` and I don't have 5TB disks to see the normal behaviour...

**Comment by shlatchz** [comment]
Anything above 1TB (1024GB) doesn't work...

**Comment by Liryna** [comment]
I have been able to reproduce the situation but also it is only xcopy that have this behaviour. Other commands that I tested work.

I don't think this is a dokan issue but more about xcopy limitation.

Thank you for the report @shlatchz , it will help people having this behaviour in the futur.

Feel free to reopen if you have new informations about it.
