### ISSUE TITLE
Mirror Example not working with MS Word 2016

### ISSUE THREAD

**Issue by gds-mthompson** [dokan-dev/dokan-dotnet#58]
Hi,

Using the Mirror Example, with Office 2016.

1.) Create a new Word Document and Save it to  a Mirror Drive - Works Fine
2.) Modify the new Word Document and Save it again (Same name and path).  Get a permissions error.  

Were just getting started with Dokan.  Any / help suggestions would be appreciated.

**Comment by Liryna** [comment]
Hi @gds-mthompson ,

The C# sample is kind of 'simple'.
The C mirror handle more case, can you try on it ?
https://github.com/dokan-dev/dokany/wiki/Use%20Mirror%20exemple

Otherwise there is a ticket that could help you: https://github.com/dokan-dev/dokan-dotnet/issues/27

**Comment by gds-mthompson** [comment]
Hi - Thanks for the quick response - much appreciated.

I've checked the C Mirror - It works fine.

This looks very similar to Issue #27.  
Word Does not crash.  If I go to file save as  it does let me save as a different filename.

However I do not get the Out of memory error message described in Issue #27.

The exact error we are getting is:
"Permission to the document you are attempting to replace is currently restricted.  If you want to save this file, please use another file name."

Let me know if I can provide any other information.
Thanks again.

**Comment by Liryna** [comment]
Can you provide C# debug logs ? (have to enable it with flag in the mount)

**Comment by gds-mthompson** [comment]
I'm using                 mirror.Mount("o:\\", DokanOptions.DebugMode, 5);

I've modified Mirror.cs so that as well as writing to console it saves to file.
(This is the only change ive made)


I then did the following:
[dump.txt](https://github.com/dokan-dev/dokan-dotnet/files/103257/dump.txt)

Created a Word Document, Saved it.
Cleared out the log file.  
Hit Save.

Thanks again, if you need anything else - just ask.

**Comment by Liryna** [comment]
Humm there is not error. All open access return Success.

I think Words is using Alternate Data Streams that is not implemented in the C# mirror.
Can you add logs in here -> https://github.com/dokan-dev/dokan-dotnet/blob/7fa8ca4dd709d93155ac0915aefbd7977fbd413e/sample/DokanNetMirror/Mirror.cs#L538
Normally it should already be log but to be sure...

For info, there was a pull request that implement it but the dependacy was too heavy: https://github.com/dokan-dev/dokan-dotnet/pull/34

**Comment by gds-mthompson** [comment]
Logging was already at that line.  I added an additional line which was never logged.  Ive also put a break point at that line - 
NtStatus FindStreams(string fileName, IntPtr enumContext, out string streamName, out long streamSize, DokanFileInfo info)
Never gets called when this problem occurs.

Thanks.

**Comment by gds-mthompson** [comment]
Neither of the FindStreams methods are hit when this problem occurs.

**Comment by Liryna** [comment]
I have not idea for now :(

Mirror C & C# logs should be compared to see the difference.
(I don't really have the time to do it this week so if you could make the research it would be nice)

**Comment by marinkobabic** [comment]
NtStatus GetFileSecurity
NtStatus SetFileSecurity

The methods above are executed during the save process and how do you handle them?

**Comment by gds-mthompson** [comment]
Hi Marinkobabic. 
I'm using the latest mirror.cs.   
Those methods look like:

      public NtStatus GetFileSecurity(string fileName, out FileSystemSecurity security, AccessControlSections sections, DokanFileInfo info)
        {
            try
            {
                security = info.IsDirectory
                               ? (FileSystemSecurity)Directory.GetAccessControl(GetPath(fileName))
                               : File.GetAccessControl(GetPath(fileName));
                return Trace("GetFileSecurity", fileName, info, DokanResult.Success, sections.ToString());
            }
            catch (UnauthorizedAccessException)
            {
                security = null;
                return Trace("GetFileSecurity", fileName, info, DokanResult.AccessDenied, sections.ToString());
            }
        }

        public NtStatus SetFileSecurity(string fileName, FileSystemSecurity security, AccessControlSections sections, DokanFileInfo info)
        {
            try
            {
                if (info.IsDirectory)
                {
                    Directory.SetAccessControl(GetPath(fileName), (DirectorySecurity)security);
                }
                else
                {
                    File.SetAccessControl(GetPath(fileName), (FileSecurity)security);
                }
                return Trace("SetFileSecurity", fileName, info, DokanResult.Success, sections.ToString());
            }
            catch (UnauthorizedAccessException)
            {
                return Trace("SetFileSecurity", fileName, info, DokanResult.AccessDenied, sections.ToString());
            }
        }



Thanks for helping!

**Comment by gds-mthompson** [comment]
Liryna - Ive just realised Trace wasn't set when I produced that log file. New one here (Much bigger now).
I'm going to try and produce the c++ log file for the same operation and compare.

Thanks.
[WordFailWrite.txt](https://github.com/dokan-dev/dokan-dotnet/files/103388/WordFailWrite.txt)

**Comment by marinkobabic** [comment]
CreateFileProxy : \Temp\doc1.docx Throw : The process cannot access the file 'C:\Temp\doc1.docx' because it is being used by another process.

The file is for some reason still open even it was closed before.

**Comment by gds-mthompson** [comment]
Thanks very much - Quite right.  That's a Big leap in the right direction.  Ill see if I can find where it gets locked.

**Comment by gds-mthompson** [comment]
Hi... Ive got a bit more information.  
I get an exception being thrown in Mirror.cs,  CreateFile.  On the line:
info.Context = new FileStream(path, mode, readAccess ? System.IO.FileAccess.Read : System.IO.FileAccess.ReadWrite, share, 4096, options);

System.ArgumentOutOfRangeException - Enum value was out of legal range.  Parameter name: options

The Value of options is 2097152 - Which is not valid.

**Comment by Liryna** [comment]
Thanks for the feedback !
Could you try this fix ? https://github.com/dokan-dev/dokan-dotnet/commit/3242e95e0d4796644038ee47b2b415b1e3e3ea4d

**Comment by gds-mthompson** [comment]
The Good news is that I no longer get that exception thrown.  The fix seems to have helped it.  I do still get the second Exception Marinkobabic pointed out.  This seems to be an improvement but word still fails to save.

Ill continue trying to diagnose the second (Marinkobic) exception now.

**Comment by Liryna** [comment]
Can you try to override share variable to FileShare.ReadWrite in the mirror ?

**Comment by gds-mthompson** [comment]
I no longer get either exception thrown, however still get the permission error.

Thanks.

**Comment by gds-mthompson** [comment]
Just wondering - Has anyone else tried Word against the latest doken-Net recently?  (Mirror File System or otherwise)?

**Comment by Liryna** [comment]
Never tried :smile: I don't have Words on my VM

**Comment by Rambalac** [comment]
I tried Word with my Amazon Cloud Drive driver. It works. Could it be a problem in Mirror because of async/overlapped file access Word is using?

**Comment by Liryna** [comment]
@Rambalac from his log it dont seems to be the issue but we can try, @gds-mthompson could you test by adding lock in read & write like this ?
```
                lock (info.Context) // Overlapped I/O
                {
                    var stream = info.Context as FileStream;
                    stream.Position = offset;
                    bytesRead = stream.Read(buffer, 0, buffer.Length);
                }
```

**Comment by Rambalac** [comment]
Mine is 2010

**Comment by gds-mthompson** [comment]
Thanks for the suggestion Rambalac.  
That didn't appear to make any difference. 

@Rambalac - Is there a copy of your Dokan Implementation anywhere I can try with Office 2016?

**Comment by gds-mthompson** [comment]
Looking around, you can download a Preview Version Of Office 2016 from:
http://www.techtimes.com/articles/50762/20150505/you-can-now-preview-microsoft-office-2016-where-to-dowload-and-what-to-know.htm
(There is an install Key on the page).

**Comment by Rambalac** [comment]
@gds-mthompson  Yes, but you need Amazon account. https://github.com/Rambalac/ACDDokanNet
I can try 2016 in 3 hours.

**Comment by gds-mthompson** [comment]
@Rambalac - Source for Amazon drive doesn't build.  Missing AmazonSecret.cs
(I have an Amazon Account)

**Comment by Rambalac** [comment]
You have to create AmazonSecret.cs in fill missing fields with your app secrets. Amazon does not allow to publish them though does not punish if you do it.

**Comment by Rambalac** [comment]
Yep, 2016 works too. Created small docx, saved it to ACD, restarted to be sure, reopened file without any problem.

**Comment by gds-mthompson** [comment]
Did you try changing the document then saving it again (Same filename).  That seems to be the most problematic.

**Comment by Rambalac** [comment]
Yes, tried, no problem.

**Comment by Liryna** [comment]
@gds-mthompson Have you been able to get more information about your issue ?

**Comment by gds-mthompson** [comment]
I'm afraid not.  The timescales we were working to meant we had to adopt a commercial component.   However I am keen to still get Dokan.NET working (Long term I believe it offers a better solution).  I'm at a loss how to progress the issue now. Ill try getting the latest and testing again just to see if anything has changed.

**Comment by marinkobabic** [comment]
Is this a virtual machine you are working on? Please download the process monitor from sysinternals. Keep it running while you are performing the operations. In process monitor you can turn on advanced mode. Please post here the log of the monitor. Maybe you have to set the filter to path contains yourfile without any extension. 

This is a fixed drive or a removable drive?  What are the device characteristics you use? Remote file support?  Do you use ACL support?

**Comment by Liryna** [comment]
This should be tested again with the last mirror changes and when the RC3 will be released with the Oplock changes.

**Comment by gds-mthompson** [comment]
Ive just tried it wil latest DokanY(1.0.0 RC2) and .NET mirror.

It seems much, much better now.  Please give me a few more days to do a bit more testing after which I suspect this issue can be marked as resolved.

Thanks for your help!

**Comment by andysyncplicity** [comment]
I noticed that RC2 is still the most current installer available for download.

I'm not sure what the Oplock changes are. Are they driver changes, and thus require an RC3 installer?

Or, are they C# layer changes an can easily be built from source?

**Comment by Liryna** [comment]
@andysyncplicity It is dokan driver changes and need to be tested before release a RC3.

**Comment by Liryna** [comment]
RC3 Released: https://github.com/dokan-dev/dokany/releases/tag/v1.0.0-RC3

If there is not progress, It will probably need https://github.com/dokan-dev/dokany/issues/152

**Comment by Liryna** [comment]
I had the time to make the test and test with excel/word passed.
