### ISSUE TITLE
Copying files with altstreams

### ISSUE THREAD

**Issue by shlatchz** [dokan-dev/dokan-dotnet#59]
Whenever you copy a file from Dropbox to dokan, the file has extra altstream and the following message pops up:

![image](https://cloud.githubusercontent.com/assets/4594463/12675427/d46b5728-c692-11e5-95f2-bd5c78d6329a.png)

Because the altstream cannot be copied to dokan. Is there a way to suppress this messages, and just continue?

**Comment by Liryna** [comment]
Does it work with the C mirror ?
The C mirror implement the altstreams.

**Comment by shlatchz** [comment]
It doesn't. 

You can only get the name of the stream but not its content, or am I wrong?

**Comment by Liryna** [comment]
It work :)

```
> echo coucou > lol.text
> echo coucou > lol.txt:yes.txt
> dir /R
 Volume in drive M is DOKAN
 Volume Serial Number is 1983-1116

 Directory of M:\Liryna\Desktop

01/29/2016  04:55 AM    <DIR>          .
01/29/2016  04:55 AM    <DIR>          ..
01/27/2016  06:01 AM                 6 dfgd.txt
01/29/2016  04:46 AM         3,617,120 iview441g_x64_setup.exe
01/29/2016  04:55 AM                 0 lol.txt
                                     9 lol.txt:yes.txt:$DATA
01/29/2016  04:45 AM    <DIR>          VBOXSVRx64
               3 File(s)      3,617,126 bytes
               3 Dir(s)     536,870,912 bytes free
```

Can you try to change the FS to FAT or NTFS for your test ?
https://github.com/dokan-dev/dokany/blob/master/dokan_mirror/mirror.c#L1123

**Comment by shlatchz** [comment]
Copying lol.txt to M:\ with CMD works without a prompt,
but when you try to copy it with Windows Explorer, you see the prompt.
Try copying it from C:\ to M:\ in Windows Explorer.

**Comment by Liryna** [comment]
`Copying lol.txt to M:\ with CMD works without a prompt,`
does the stream is still there when dir /R ?

`but when you try to copy it with Windows Explorer, you see the prompt.`
Can you try to change the FS to FAT or NTFS for your test ?
https://github.com/dokan-dev/dokany/blob/master/dokan_mirror/mirror.c#L1123

**Comment by shlatchz** [comment]
> does the stream is still there when dir /R ?

No.

> Can you try to change the FS to NTFS for your test ?

I changed to NTFS and the prompt still pops up.

**Comment by Liryna** [comment]
Can you look into the logs if there is a reason or error that windows cannot create the altstream ?

**Comment by shlatchz** [comment]
[Log](http://pastebin.com/QHAZsLRg)

I've noticed that for:

    CreateFile : C:\Temp\lol.txt\:yes.txt:$DATA

CreateFile returned an error code..

    CreateFile status = 3221225524 - lastError = 123

**Comment by Liryna** [comment]
@shlatchz Well his is right...C:\Temp\lol.txt\:yes.txt:$DATA is a invalid name

**Comment by shlatchz** [comment]
That's the name that shows up after dir /R

**Comment by Liryna** [comment]
There is a `\` before `:` is it normal ?

**Comment by shlatchz** [comment]
Oh, I haven't noticed :)

**Comment by shlatchz** [comment]
@Liryna , If I'm not wrong, DokanNet doesn't support reading alt streams at all.
Can I in some way, suppress the message and just skip the alt stream writing?

**Comment by Liryna** [comment]
@shlatchz DokanNet support alternative streams. But it is the software that need to implement the alternative stream  listing and create read write... And also enable the dokan option at Mount for alternative stream. 

You have this message because the C# mirror don't have the dokan option enabled and therefore windows tell you that the copies is not going to be total.

**Comment by shlatchz** [comment]
After enabling it in DokanNet, I didn't get a CreateFile request with the altstream, but the prompt doesn't show up anymore!

**Comment by Liryna** [comment]
Good to hear that it fixed your issue  :+1:

**Comment by shlatchz** [comment]
In Win10, it does request to write/read the AltStream (While in Win7, it doesn't):

    [CreateFile()] F:\DokanInstall_0.8.0_redist.exe\:Zone.Identifier:$DATA, Access: ReadData, WriteData, AppendData, WriteExtendedAttributes, WriteAttributes, ReadPermissions, Synchronize, Share: ReadWrite, Delete, Mode: Create, Options: SequentialScan, Attributes: 0, DeleteOnClose: False & False & False, BlobName: , Handle: 272

But with that annoying backslash before the colon...
