### ISSUE TITLE
Add FindFilesWithPattern operation

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokan-dotnet#60]
FindFilesWithPattern should be implemented in the wrapper.

https://github.com/dokan-dev/dokan-dotnet/blob/6e8d3e0f7884ae7a255000b287ee3913dee99e17/DokanNet/Native/DOKAN_OPERATIONS.cs#L18

**Comment by dimov-cz** [comment]
+1

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokan-dotnet/commit/c5f35bbdb7f7c346bc896396be06d5bed8b30a27
