### ISSUE TITLE
The main project file (.csproj) is incorrect in the last commit

### ISSUE THREAD

**Issue by luanmm** [dokan-dev/dokan-dotnet#7]
In the last commit (b7f3670ec8f6c489b44370e9343826e88cf33d6c), where DokanError class has been renamed to DokanResult, the .csproj file wasn't updated. Then, the respective files wasn't renamed in the project and is now missing.

I'm not a project contributor to publish the solution, so I'm submitting this issue. Hope it helps.

By the way: nice project, guys! Congratulations on your effort!

**Comment by Liryna** [comment]
:ok_hand: Thank you
