### ISSUE TITLE
BadImageFormatException in samples

### ISSUE THREAD

**Issue by traubisoda** [dokan-dev/dokan-dotnet#70]
Hi!

When I try to run either sample from visual studio 2015, I get a System.BadImageFormatException in Dokan.cs line 102:
int status = NativeMethods.DokanMain(ref dokanOptions, ref dokanOperations);
I tried with x86 and x64 build targets, but the error is the same.
What could be the reason behind this?

**Comment by Liryna** [comment]
Hi @traubisoda ,

Your application is running in a different version (x86/x64) than the dokan1.dll he is using.
```
        if (IntPtr.Size == 8)
            return "x64";
        else
            return "x86";
```
and check which dll is he using.
