### ISSUE TITLE
Folder creation with elevated permissions

### ISSUE THREAD

**Issue by traubisoda** [dokan-dev/dokan-dotnet#71]
Hi!

I'm using dokan-dotnet version 1.0.8. When I try to create a folder, in the explorer context menu, under New, I only have the folder option with the admin rights icon (shield). If I click that, I won't be asked about the folder name, but a "New folder" will be automatically created. If I run the mirror example, it works as expected and I'll be prompted to give the folder a name. 
What could be the reason behind this behavior?

Thanks in advance!

**Comment by Liryna** [comment]
Hi @traubisoda ,

Since this is not an issue, can you create a topic in the google group for your request:
https://groups.google.com/forum/#!forum/dokan

Thank you !
