### ISSUE TITLE
Volume label changing

### ISSUE THREAD

**Issue by Rambalac** [dokan-dev/dokan-dotnet#76]
Is it possible to make changing of Volume label in Explorer? For now it says any new label is invalid.

Also there is some strange bug with volume labels in 1.1.0.0-rc2 with docany 1.0.0-RC2. For few seconds after mount when drive appears label is some random text, like part of some path. Then it changes to title I set in GetVolumeInformation. This is probably docany's problem. Tested in Windows 7

**Comment by Liryna** [comment]
Hello @Rambalac ,

Updating volume label in explorer is currently not implemented. It is also more related to dokan driver than dotnet :smiley: 

`For few seconds after mount when drive appears label is some random text, like part of some path.`
Can you run the C# Mirror and take a screen of it ? Does it happen with C Mirror ?

**Comment by Rambalac** [comment]
Just tried C# Mirror. It's the same 11 seconds, now it happens every start 
```
04/04/2016 14:30:11 - [Mirror] Mount('', {<null>, False, False, False, Fal
04/04/2016 14:30:22 - [Mirror] GetVolumeInformation('', {<null>, False, Fa
```
That means no fix, right?

**Comment by Rambalac** [comment]
By the way, I found my company PC has some special software to prevent USB drives use. Never needed real USB drives so found it only accidentally when tried to make Removable device.

**Comment by Liryna** [comment]
@Rambalac there was no fix because since we did not found the reason and we have not been able to say if it was dokan issue or your environment.

Your usb security could be the reason for example.

**Comment by Liryna** [comment]
Issue reopen in dokany https://github.com/dokan-dev/dokany/issues/216
