### ISSUE TITLE
info.context question

### ISSUE THREAD

**Issue by maurosampietro** [dokan-dev/dokan-dotnet#78]
Since CreateFile is the first function called, inside that function i set a value to info.Context.
On subsequent calls to other functions like SetEndOfFile, ReadFile or WriteFile that variable sometimes is null, sometimes is not. 
I read on dokan documentation that the context should remain the same in everything between CreateFile and CloseFile so can you please help me understand how it actually works?

**Comment by Liryna** [comment]
Hi @maurosampietro ,

it is right, the context should be the same between CreateFile and CloseFile.

You should also know that there could be different context for the same file. The system is offen going to call CreateFile a multiple time in the same moment. Therefore you will have one new context for each request.
Ex:
```
#1 CreateFile \test.txt
#2 CreateFile \test.txt
#1 Write 
#2 Lock
#1 CloseFile
#2 CloseFile
```

**Comment by maurosampietro** [comment]
I create a new WriteStream every time CreateFile w/ FileMode.CreateNew is called. How do you usually manage this situation to avoid 'file already in use' exceptions?

(I never get Lock function called but it may not be a problem now)

**Comment by Liryna** [comment]
You have to handle sharing mode with https://msdn.microsoft.com/fr-fr/library/system.io.fileshare%28v=vs.110%29.aspx at open.

**Comment by maurosampietro** [comment]
So i'm already doing the right way :) thank you!

**Comment by maurosampietro** [comment]
I'm sorry to bore you but i have a few other question in order to complete my file system...

Suppose i want to copy a file i have on my desktop called 'file.dat' to my volume. The final destination path is '\subdir1\subdir2\'. I open explorer browse to this destination folder and paste my file.dat.

In debug i see  CreateFile  is called w/ FIleMode.CreateNew parameter but the path is missing the actual name of the file: i receive ''\subdir1\subdir2\' but i expected ''\subdir1\subdir2\file.dat' in order to properly create the file. What's happening here?

**Comment by Liryna** [comment]
At first the device open the folder ''\subdir1\subdir2\' to be sure that it exist and only after it is going to call you with '\subdir1\subdir2\file.dat'.

Do you check if the request is made for a directory ?
https://github.com/dokan-dev/dokan-dotnet/blob/master/sample/DokanNetMirror/Mirror.cs#L83
https://github.com/dokan-dev/dokan-dotnet/blob/master/sample/DokanNetMirror/Mirror.cs#L121

**Comment by maurosampietro** [comment]
I write on Console any request of create file. I don't seem to receive the proper  '\subdir1\subdir2\file.dat' request

**Comment by Liryna** [comment]
Humm so there should be something wrong in your implementation before this call.
It is pretty hard for me to give you advice at this point :cry: 

Did you start your project by editing the mirror ?

**Comment by maurosampietro** [comment]
You seem quite sure it's something related to my implementation so I'll will investigate some more. Back to you if this persists. thank you.

**Comment by marinkobabic** [comment]
@maurosampietro You can pass in a ConsoleLogger when doing the mount. So you don't need to log your self.

**Comment by Liryna** [comment]
@maurosampietro do you still have issues or I can close the ticket ?
