### ISSUE TITLE
Unable to save files

### ISSUE THREAD

**Issue by AnguisCaptor** [dokan-dev/dokan-dotnet#79]
When trying to save a file in notepad, I won't be able to save the file in the mounted dokan mirror
I'm just trying to save it in a folder but nothing really happens when hitting "Save"

The log is from the point I hit Save
Log: http://pastebin.com/RHXNxm5d

I noticed as well that when hitting the "save" button, "." will append at the end of the save location
So when hitting the save a few times it will come out as "N:\PerfLogs\\.\\.\\.\\."
Using the latest release of Dokany, running windows 8.1 x64

**Comment by Liryna** [comment]
Hi @AnguisCaptor ,

Correct ! This happen since https://github.com/dokan-dev/dokan-dotnet/commit/9e8660f2d36f2e03c2f270befe6a8ed1180a2302
I will look into it why

**Comment by Liryna** [comment]
It was not linked by the last commit at then end :smiley: 

Fixed with https://github.com/dokan-dev/dokan-dotnet/commit/cb3d963f6d0a4ed307cc6c405283f20c57d43996

**Comment by AnguisCaptor** [comment]
Confirmed working, thanks for the quick fix, awesome project btw :smiley:
