### ISSUE TITLE
C# Mirror Example can't save file with MS Journal.exe

### ISSUE THREAD

**Issue by superhq** [dokan-dev/dokan-dotnet#80]
Hi,
using sample code (master branch):
1.open 1.jnt file
2.modify it 
3.press save button
MS Journal.exe program is waiting for response always.
I test it in C mirror, and it work fine.
the log file in C mirror as follows:
[c_mirror_log.txt](https://github.com/dokan-dev/dokan-dotnet/files/258854/c_mirror_log.txt)
the log file in C# mirror as follows:
stdout:
[c#_mirror_log_stdout.txt](https://github.com/dokan-dev/dokan-dotnet/files/258865/c._mirror_log_stdout.txt)
stderr:
[c#_mirror_log_stderr.txt](https://github.com/dokan-dev/dokan-dotnet/files/258867/c._mirror_log_stderr.txt)

In c_mirror_log.txt  a *.tmp file is created when saving 1.jnt, but in c#_mirror_log_stderr.txt,there is not temp file created, and the invalid handle error(6) occurs many times.

**Comment by superhq** [comment]
I test the newest version(1.1.0.0-rc3), but the same result.
debug it in vs, and exceptions output many times:

引发的异常:“System.IO.FileNotFoundException”(位于 mscorlib.dll 中)
引发的异常:“System.ArgumentException”(位于 mscorlib.dll 中)
引发的异常:“System.ArgumentException”(位于 DokanNetMirror.exe 中)
引发的异常:“System.IO.FileNotFoundException”(位于 mscorlib.dll 中)
引发的异常:“System.ArgumentException”(位于 mscorlib.dll 中)
引发的异常:“System.ArgumentException”(位于 DokanNetMirror.exe 中)
引发的异常:“System.IO.FileNotFoundException”(位于 mscorlib.dll 中)
引发的异常:“System.ArgumentException”(位于 mscorlib.dll 中)

Sorry, My VS output some characters that you may not understand.
"引发的异常" means:raise exception.
"位于xxx中" means:in xxxx.

Any advice and suggestions will be greatly appreciated.

**Comment by Liryna** [comment]
Hi @superhq ,

I just made a test and I have no issue when opening a JNT file:
```
05/11/2016 22:30:39 - [Mirror] CreateFile('\Users\liryna\Desktop\1.jnt', {<Object>, False, False, False, False, #2420, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [0]) -> Success
05/11/2016 22:30:39 - [Mirror] GetFileInformation('\Users\liryna\Desktop\1.jnt', {<Object>, False, False, False, False, #2420, False, False}) -> Success
Cleanup('\Users\liryna\Desktop\1.jnt', {<Object>, False, False, False, False, #2420, False, False} - entering
05/11/2016 22:30:39 - [Mirror] Cleanup('\Users\liryna\Desktop\1.jnt', {<null>, False, False, False, False, #2420, False, False}) -> Success
05/11/2016 22:30:39 - [Mirror] CloseFile('\Users\liryna\Desktop\1.jnt', {<null>, False, False, False, False, #2420, False, False}) -> Success
```

I think your issue come from your environnement, could you try to take a look where and why this exception are happening ? (call stack and such)

Also, did you install the dokan 1.0.0-rc3 AND the pull the new master of this repository ?

**Comment by superhq** [comment]
@Liryna Did you modify the file and save it?
I have install dokan 1.0.0-rc3 and user the newest dokan-dotnet code.

**Comment by superhq** [comment]
@Liryna Did you modify the file and save it?
I have install dokan 1.0.0-rc3 and user the newest dokan-dotnet code.
when I save it, the log repeat the following lines always:
> 05/12/2016 14:19:42 - [Mirror] Cleanup('\', {<null>, False, True, False, False,
> #4, False, False}) -> Success
> 05/12/2016 14:19:42 - [Mirror] CloseFile('\', {<null>, False, True, False, False
> , #14004, False, False}) -> Success
> 05/12/2016 14:19:42 - [Mirror] CreateFile('\', {<null>, False, True, False, Fals
> e, #14004, False, False}, [ReadData, Synchronize], [ReadWrite, Delete], [Open],
> [None], [Normal]) -> Success
> 05/12/2016 14:19:42 - [Mirror] FindFilesWithPattern('\', {<null>, False, True, F
> alse, False, #14004, False, False}) -> Success
> 05/12/2016 14:19:42 - [Mirror] Cleanup('\', {<null>, False, True, False, False,
> #4, False, False}) -> Success
> 05/12/2016 14:19:42 - [Mirror] CloseFile('\', {<null>, False, True, False, False
> , #14004, False, False}) -> Success
> 05/12/2016 14:19:42 - [Mirror] CreateFile('\', {<null>, False, True, False, Fals
> e, #14004, False, False}, [ReadData, Synchronize], [ReadWrite, Delete], [Open],
> [None], [Normal]) -> Success

**Comment by Liryna** [comment]
Ok I have the same issue when saving.
I will not be able to debug it until some time, can you try to see what is creating this Exception and why ?

**Comment by superhq** [comment]
I think I find out something wrong.
when save the .jnt file, the Journal.exe program will create *.tmp file first.
At this time, in CreateFile method, the mode value is **CreateNew** but the access value is **ReadData | ReadExtendedAttributes | ReadAttributes | ReadPermissions | Synchronize** , so call FileStream method will throw exception.

> DokanNetMirror.exe!DokanNetMirror.Mirror.CreateFile(string fileName, DokanNet.FileAccess access, System.IO.FileShare share, System.IO.FileMode mode, System.IO.FileOptions options, System.IO.FileAttributes attributes, DokanNet.DokanFileInfo info) 行 208	C#
>  	DokanNet.dll!DokanNet.DokanOperationProxy.ZwCreateFileProxy(string rawFileName, System.IntPtr SecurityContext, uint rawDesiredAccess, uint rawFileAttributes, uint rawShareAccess, uint rawCreateDisposition, uint rawCreateOptions, DokanNet.DokanFileInfo rawFileInfo) 行 187	C#

**Comment by superhq** [comment]
I modify ZwCreateFileProxy method in DoaknOperationProxy.cs,add:
`                if((FileMode)CreationDisposition == FileMode.CreateNew)
                {
                    rawDesiredAccess |= (uint)(FileAccess.WriteData|FileAccess.AppendData|FileAccess.WriteExtendedAttributes|FileAccess.WriteAttributes);
                }`
It may not  reasonable, only for testing. And then, I set a breakpoint in DeleteFileProxy method,do the following:

1. open 1.jnt
2. write something
3. saving


No error occur before leaving DeleteFileProxy method, but when the DeleteFileProxy  return（result is success）, Journal.exe program show a error message box.
Could you please give me some advice？Thank you.

**Comment by Liryna** [comment]
Humm does all other request from Journal.exe succeed also ?
It would be interesting to compare with the mirror C what is happening.

On such situation it is hard to know exactly what the software is expecting.

Can you just also try to run mirror with only one thread ? (it is a mount option)
