### ISSUE TITLE
Error on removable drive eject

### ISSUE THREAD

**Issue by o2genum** [dokan-dev/dokan-dotnet#84]
Windows 10. I'm trying to eject my filesystem drive mounted with DokanOptions.RemovableDrive flag, but the unmount does not happen and Unmounted() is not called. I get "An error occured while ejecting ..." error.

As I see in device.c from dokany:
```
case IOCTL_STORAGE_EJECT_MEDIA: {
    DDbgPrint("   IOCTL_STORAGE_EJECT_MEDIA\n");
    DokanUnmount(dcb);
    status = STATUS_SUCCESS;
  } break;

```
There should happen an automatic unmount, I see, but it does not happen. I haven't tried dokany itself with C interface.

**Comment by Liryna** [comment]
Hi @o2genum ,

Dokan does not support eject mechanisme as you imagine.
In other word, `IOCTL_STORAGE_EJECT_MEDIA` is not called when using eject button.

**Comment by Liryna** [comment]
Close the ticket since it should be in Dokany core repository
