### ISSUE TITLE
dokan-dotnet umount fail

### ISSUE THREAD

**Issue by kanuvic** [dokan-dev/dokan-dotnet#88]
I am testing the C# mirror code using thread. 

```CS
    private void button_start_Click(object sender, RoutedEventArgs e)
        {
            Mirror mirror = new Mirror("E:");
            (thread = new Thread(new ThreadStart(() => mirror.Mount("N:", DokanOptions.DebugMode | DokanOptions.RemovableDrive, 5)))).Start();
        }
```

I use the following code to umount the driver:
```CS
    private void button1_Click(object sender, RoutedEventArgs e)
        {
            bool res = true;
            try
            {
                thread.Abort();
                res = Dokan.Unmount('N');
                if (!res)
                {
                    Console.WriteLine("Unmount failed");
                }
                res = Dokan.RemoveMountPoint("N:");
                if (!res)
                {
                    Console.WriteLine("Remove mount point failed");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
```

I always get the output "Unmount failed". However, the mounted driver does disappear in my File Explorer.

The problem is that when I close the application, I always get an error in the debug output " (0xc0000005) 'Access violation'".

When I use DebugView, I can only get the following output:

[5436] ERROR: Exception in Command Processing for EventSource Microsoft-Windows-UTC-Presence: An instance of EventSource with Guid a19fdc69-a626-5289-be4d-1f508a8c9a3b already exists.  
[5436] ERROR: Exception in Command Processing for EventSource Microsoft-Windows-UTC-Presence: An instance of EventSource with Guid a19fdc69-a626-5289-be4d-1f508a8c9a3b already exists.  
[3404] 
[3404] *** HR originated: -2147024774
[3404] ***   Source File: d:\iso_whid\x86fre\base\isolation\com\copyout.cpp, line 1391
[3404] 
[3404] 
[3404] *** HR propagated: -2147024774
[3404] ***   Source File: d:\iso_whid\x86fre\base\isolation\com\identityauthority.cpp, line 278
[3404] 
[3404] 
[3404] *** HR originated: -2147024774
[3404] ***   Source File: d:\iso_whid\x86fre\base\isolation\com\copyout.cpp, line 1391
[3404] 
[3404] 
[3404] *** HR propagated: -2147024774
[3404] ***   Source File: d:\iso_whid\x86fre\base\isolation\com\identityauthority.cpp, line 278
[3404] 
[6312] ADOBE_READLOGGER_CMD:PAUSE_LOG
[3404] 
[3404] *** HR originated: -2147024774
[3404] ***   Source File: d:\iso_whid\x86fre\base\isolation\com\copyout.cpp, line 1391
[3404] 
[3404] 
[3404] *** HR propagated: -2147024774
[3404] ***   Source File: d:\iso_whid\x86fre\base\isolation\com\identityauthority.cpp, line 278
[3404] 
[4508] Failed to install WH_DEBUG hook err = 1428

If I use `dokanctl.exe /u N`, then the application can exit without error.
Can anyone help me with this? Thanks.
I am using Dokan 0.8, and the Dokan-Donet was installed using the PM command.
My system is Win7 64bit.

**Comment by kanuvic** [comment]
I change to the following declaration in DokanNnet and replace the DokanNet.dll in my project, it also fails.
```
[DllImport(DOKAN_DLL, ExactSpelling = true, CharSet = CharSet.Auto)]
public static extern int DokanUnmount([MarshalAs(UnmanagedType.LPWStr)]char driveLetter);
```

If I do not use 'Dokan.Unmount('N');' and only use 'Dokan.RemoveMountPoint("N:");', it still fails.

**Comment by Liryna** [comment]
Hi @kanuvic ,

With dokan 0.8.0 you have to use nuget stable release, is that the case ?

Otherwise, we are doing the same as you on DokanNet Test and there is no issue.
https://github.com/dokan-dev/dokan-dotnet/blob/768e3d26328e6b9da14931e273d7357c12fe300b/DokanNet.Tests/Mounter.cs#L30-L32

Probably this has been fixed since 0.8.0 or it is something in your environement/application.

**Comment by marinkobabic** [comment]
Try also to change the order of this  two lines to

res = Dokan.Unmount('N');
thread.Abort();

The thread will terminate automatically if unmount is done. In other case it sounds like killing the process in task manager.

**Comment by kanuvic** [comment]
> with dokan 0.8.0 you have to use nuget stable release, is that the case ?
yes, I install it using 
`PM> Install-Package DokanNet`
and its version is 1.0.8.0

>Otherwise, we are doing the same as you on DokanNet Test and there is no issue
yes, I am doing exactly the same thing as you do in the code. 
Can you check the return value of your code? Thanks

**Comment by kanuvic** [comment]
> Try also to change the order of this two lines to

I tried it before, and it was not working

**Comment by Liryna** [comment]
Return value are correct, you can see here: https://ci.appveyor.com/project/Liryna/dokan-dotnet/build/1.0.0-187/job/cwqlau47os0xlit8#L186 that all test pass without error and crash

**Comment by kanuvic** [comment]
> Return value are correct

In Dokan driver, return (int)0 means success. However, in Dokan-Donet, the return value is bool. Therefore, value 0 is converted to false. This explains why I get an error. Do you think my explanation is correct?

**Comment by kanuvic** [comment]
Another problem is that when my program calls Dokan.Unmount('N') and exits, I notice that there is still a thread in DokanNet.dll which has not exited yet (This thread may also be in Dokan1.dll).
If my program exists before the thread in the dll exits, I will have an 'Access violation' error. 

Is there any way for my program to safely exit?

**Comment by marinkobabic** [comment]
Please can you prepare a small example and post the link to the zip file here?

Did you run it on another machine with the same result?

**Comment by Liryna** [comment]
DokanUnmount and RemoveMountPoint return type have been fixed:
https://github.com/dokan-dev/dokan-dotnet/commit/c1a02f875ad859a82e8d8df12871ce07c0df60cd

**Comment by kanuvic** [comment]
Thanks everyone. I upgraded to RC3 from 0.8. I can exit without problems now.
