### ISSUE TITLE
XML Documentation Comments

### ISSUE THREAD

**Issue by magol** [dokan-dev/dokan-dotnet#89]
Why is it no [XML Documentation Comments](https://msdn.microsoft.com/en-us/library/b2s063f7.aspx) for any methods?
If there were, it would be easier for me as a beginner to understand the code.

**Comment by Liryna** [comment]
I don't have the time to do it, so if anyone can create a pull request for it, it would be very appreciate !

**Comment by Liryna** [comment]
Hi @magol ,

I have added some documentation as requested
see https://github.com/dokan-dev/dokan-dotnet/commit/1eb1462794662757174d8f6920c9cf0e83865a0c 

Does you think this is enough or did I miss a part that you would like that a comment ?

**Comment by magol** [comment]
Great job. It helps a lot for a beginner like me.

I have commented on some points that I would like some clarification.
Then maybe you can use <see> to reference other parts of the code, but it may not be as important in the first iteration.

In fact I have myself spent some time on this, see [my branch](https://github.com/magol/dokan-dotnet/tree/XmlComments/DokanNet)
It's been really educational to try to figure out how everything fits together. My comments might be a bit more lengthy than your comments. I think I have a little too much information.

Please look at what I have done. Maybe we can put together our comments to some middle ground.

**Comment by Liryna** [comment]
Oh you hidded this from me @magol !
Thats a great surprise ! :+1: 

Thank you for the review, I made some changes https://github.com/dokan-dev/dokan-dotnet/commit/58ab042f806e89219078783e05b42cd8c96cb08b
There is only allocationUnitSize & sectorSize where I haven't changed much :cry: it is pretty hard to explain.

I will look at your comments to put them together as you proposed when I get some time. :smiley:

**Comment by Liryna** [comment]
@magol I merged all your changes.
See https://github.com/dokan-dev/dokan-dotnet/commit/04ddec12448296ee57159e74a93615b592e55dd6

Thanks again for your contribution !

Do you see any part this should be added or improve ?
DokanOperationProxy could be made for dokan contributors but I think most of the object used by users are now described.

**Comment by magol** [comment]
My ambition was to make it a little more ready first, but it took a little longer than planned.
Good merge between our comments. :-)

Something I thinking about is whether it is possible to automatically generate .md files based on the XML comments. Today is the API-documentation on the website pretty poor.

**Comment by magol** [comment]
I was thinking in the first place to generate documentation to add to dokan-dotnet.
But it would be even better if the documentation is generated from the C++ code.

According [MSDN](https://msdn.microsoft.com/en-us/library/ms177246.aspx) it is possible to use XML comments in C++  to. With a parameter to the compiler, an XML file is created during compilation containing all comments. And there is tools to transform this XML file to .md format.

**Comment by Liryna** [comment]
This should be made ! :+1:

**Comment by Liryna** [comment]
@magol do you think this can be closed ?

**Comment by Liryna** [comment]
Doxygen added https://github.com/dokan-dev/dokan-dotnet/commit/c960ef2ae1df0cc2046a7f8a1bfd28d6e4ece581

Need to find a way to store it cleanly on gh-pages

**Comment by magol** [comment]
Yes, it can be closed, it is now XML comments for most parts.
Then I hope we can use Doxygen to generate documentation from this, like in [#313](https://github.com/dokan-dev/dokany/issues/313)

Edit: Moved the answer it to the right thread :-)

**Comment by Liryna** [comment]
Dokan-dotnet documentation is now pushed auto by appveyor https://github.com/dokan-dev/dokan-dotnet/commit/fb80a9786dc035f474159fdd94cdcf89610bd90c
The documentation is in this repository https://github.com/dokan-dev/dokan-dotnet-doc
And can be read from here https://dokan-dev.github.io/dokan-dotnet-doc/html/

I will add the doc link to the readme.

**Comment by Liryna** [comment]
Added to readme https://github.com/dokan-dev/dokan-dotnet/commit/76e1c3137603d6b413369dacc2cacfba2e14f2be

At the build time you can also see in red color the current documentation missing https://ci.appveyor.com/project/Liryna/dokan-dotnet/build/1.0.0-235/job/wcvapptdeu9nk9tq#L417

**Comment by magol** [comment]
Amazing that there is now a doxygen page of dokan-dotnet too :-)
Good work.
