### ISSUE TITLE
Handle unknown date in FileInformation

### ISSUE THREAD

**Issue by magol** [dokan-dev/dokan-dotnet#90]
When I don't know the creation or modification date of the files, what should I set the `LastWriteTime` and `CreationTime` in `FileInformation` to?

According to [the documentation for FILE_BASIC_INFORMATION](https://msdn.microsoft.com/en-us/library/windows/hardware/ff545762(v=vs.85).aspx) I understand that I should set it to `-1`, but `DateTime` don't have any `-1`. The most logical I can think of is `DateTime.MinValue` or `default(DateTime)`, but that generate an `System.ArgumentOutOfRangeException` when `DokanOperationProxy.AddTo` use `DateTime.ToFileTime()`. 

I suggest that `DokanOperationProxy.AddTo` check for `DateTime.MinValue` and then set it to `-1`.

**Comment by Liryna** [comment]
Hi @magol ,

I agree with the proposition, if you can provide a pull request for it, it would be nice !

It should be handle here by a helper:
https://github.com/dokan-dev/dokan-dotnet/blob/40740f2f50c437e5f5fdb9e7729e780d3c6ba9b0/DokanNet/DokanOperationProxy.cs#L335
https://github.com/dokan-dev/dokan-dotnet/blob/40740f2f50c437e5f5fdb9e7729e780d3c6ba9b0/DokanNet/DokanOperationProxy.cs#L471

I never try with -1 value so it should be also tested to be sure of the FS behaviour.

**Comment by magol** [comment]
I was wrong with `-1`, it is only used when you don't wan't to update the date.

According to [WIN32_FILE_ATTRIBUTE_DATA structure](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365739(v=vs.85).aspx), you must use `0` if  the underlying file system does not support date.

**Comment by Liryna** [comment]
I changed FileInformations to accepte NULL DateTime as proposed here https://github.com/dotnet/coreclr/issues/6186#event-724927526
https://github.com/dokan-dev/dokan-dotnet/commit/7d0028fbda1814fa261f5a708ed807535954b845
