### ISSUE TITLE
System.Diagnostics.Debug vs OutputDebugString

### ISSUE THREAD

**Issue by magol** [dokan-dev/dokan-dotnet#96]
Is it any reason that [`OutputDebugString `](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363362(v=vs.85).aspx) is used instead of corresponding [`System.Diagnostics.Debug.WriteLine`](https://msdn.microsoft.com/en-us/library/system.diagnostics.debug.writeline(v=vs.110).aspx) in [DebugViewLogger.cs](https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/Logging/DebugViewLogger.cs#L50)?

If `Debug.WriteLine` is used, you don't have to change anything in the project settings to see the log output.

**Comment by Liryna** [comment]
:+1: this change would be alright for me.
if @marinkobabic has nothing against it

**Comment by marinkobabic** [comment]
What happens in your case when the assembly is compiled as release? Do you still see any output?

**Comment by marinkobabic** [comment]
If the idea is to see the output only when it's a debug compilation so please create a new logger like DebugWriteLogger. DebugViewLogger creates an output in the DebugView application independing of compilation type.

**Comment by Liryna** [comment]
`Debug.WriteLine`  only print if `DEBUG` flag is enabled.
Thank you @marinkobabic for the highlight, we will keep `OutputDebugString` therefore.

**Comment by magol** [comment]
Ahh, than you @marinkobabic for pointing this out for me :-)

But, one way is to select solution based on the `DEBUG` flag
```C#
#if DEBUG
    System.Diagnostics.Debug.WriteLine(message.FormatMessageForLogging(category, _loggerName));
#else
    OutputDebugString(message.FormatMessageForLogging(category, loggerName));
#endif
```

**Comment by marinkobabic** [comment]
What is the benefit of doing it so? See the logging information in the visual studio output?  

I can imagine that DebugWriteLogger would be an option because the output would be there if DEBUG and otherwise not.
