### ISSUE TITLE
Add alreadyExists param to CreateFile

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokan-dotnet#99]
Maybe we can add a new parameter to `CreateFile`, and then let `ZwCreateFile `use `SetLastError`:
```C#
NtStatus CreateFile(string fileName, FileAccess access, FileShare share, FileMode mode,
            FileOptions options, FileAttributes attributes, out bool alreadyExists, DokanFileInfo info);
```

This would avoid C# devs to call
```
public const int ERROR_ALREADY_EXISTS = 183;
[DllImport("kernel32.dll", SetLastError = true)]
static extern void SetLastError(uint dwErrorCode);
...
SetLastError(ERROR_ALREADY_EXISTS);
```
when parameter `mode==FileMode.OpenOrCreate | FileMode.Create` and the file specified in `fileName `already exist before `return NtStatus.Success`.

**Comment by marinkobabic** [comment]
Makes no sense. You have the NtStatus FileExists so return this one. If somebody uses mirror so you could create a separate library like  https://github.com/UweKeim/ZetaLongPaths and do the stuff there. Makes the interface clear and can be used optionally if needed. If somebody uses for example ftp mirror, the library would not be used. 

All the windows api stuff would reside in this new library. The code would then look like:

return fs.CreateFile

fs is the new lib. Maybe even a separate nuget package of dokan-net.

The new library must ensure that paths longer than 255 are supported.

**Comment by Liryna** [comment]
@marinkobabic currently on C mirror, we do SetLastError(ERROR_ALREADY_EXISTS); when we succeed to open the file.
The flag is retrieved by dokan library to know if the file that has been successfully open was already existing or not.
https://github.com/dokan-dev/dokany/blob/033f24177535193a3dbbf3e22c5697c9175f323f/samples/dokan_mirror/mirror.c#L372

It is true that maybe we should just return NtStatus.FileExists in case of success for (creationDisposition == OPEN_ALWAYS || creationDisposition == CREATE_ALWAYS) and remove the SetLastError(ERROR_ALREADY_EXISTS);  logic

**Comment by marinkobabic** [comment]
@Liryna 
What if somebody uses ftp mirror?  Do you also in this case set the last error. This makes absolutely no sense to me. To return the correct state would be the correct approach.

**Comment by Liryna** [comment]
Ok so better to remove the SetLastError logic and directly return NtStatus FileExists that will be converted to STATUS_SUCCESS and set Create.Information as we already do.
https://github.com/dokan-dev/dokany/blob/b3fe867d6555627ca3d1e55430c3b7efd7b262fa/dokan/create.c#L324

@marinkobabic did I understood correctly your point ?

**Comment by marinkobabic** [comment]
Based on the actual interface this would make sense. Otherwise we would have NtStatus and the additional flag which would confuse the user of the interface. 

The consumer of dokan-net should never deal with windows api. Therefore I would follow the approach mentioned above. This way the consumer would have a library if mirroring local file system. All they need to pass in is an optional base directory or otherwise the full kocal path for each operation.

**Comment by magol** [comment]
Using a return flag is much cleaner solution than my suggestion with a new parameter. :-)

The problem is that `NtStatus.FileExists` is equal to `0xc0000035`, and has the error flag set. It's wrong to return an error flag when everything is actually correct.

I suggest to define a custom NtStatus to return. See https://msdn.microsoft.com/en-us/library/cc231200.aspx

**Comment by Liryna** [comment]
SetLastError(ERROR_ALREADY_EXISTS); in CreateFile logic has been replace by directly returning STATUS_OBJECT_NAME_COLLISION
https://github.com/dokan-dev/dokany/commit/5afc31a79397e94700668a8ca8bac8f26d1bf740

@magol I am not a big fan of creating custom NTSTATUS also :cry: 
Even if it has the error flag, since there is no sense to return NtStatus.FileExists when it is a CreateFile that ask you to open a existing file or to create it, better to reuse it :D

C# changes will be made when new dokan release will be made.

**Comment by marinkobabic** [comment]
@magol
From .Net point of view it's just a state which tells that the file already exists. Based on context the state may be an error or success. 

Just add it to the documentation to make it clear when to return which state.

**Comment by Liryna** [comment]
Changes made https://github.com/dokan-dev/dokan-dotnet/commit/773df6eb8fc87e27193556d3b24d7e16b78a1a72
One appveyor test will fail until next release.
